### ISSUE TITLE
failed to build with "error MSB8066"

### ISSUE THREAD

**Issue by SafalKumar** [real-logic/simple-binary-encoding#1004]
I am getting an error while building in windows
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): e
rror MSB8066: Custom build for 'C:\Users\USER1\Desktop\Work\new\simple-binary-encoding\sbe-samples\src\main\cpp\cppbuil
d\Debug\CMakeFiles\6666cd76f96956469e7be39d750cc7d9\baseline.rule;C:\Users\USER1\Desktop\Work\new\simple-binary-encodin
g\sbe-samples\src\main\cpp\cppbuild\Debug\CMakeFiles\0d32063f0a28c99e1e03b1788321f1ed\examples_codecs.rule;C:\Users\USE
R1\Desktop\Work\new\simple-binary-encoding\sbe-samples\src\main\cpp\CMakeLists.txt' exited with code 1. [C:\Users\USER1
\Desktop\Work\new\simple-binary-encoding\sbe-samples\src\main\cpp\cppbuild\Debug\examples_codecs.vcxproj]
I took the following steps:-
1.git clone https://github.com/real-logic/simple-binary-encoding.git
2.cd simple-binary-encoding\sbe-samples\src\main\cpp 
3.mkdir -p cppbuild/Debug
4. cd cppbuild/Debug
5.cmake ../..
6. cmake --build . --clean-first
7. ctest
 But I got the above error after executing the step 6

**Comment by vyazelenko** [comment]
Try the following:

1. git clone https://github.com/real-logic/simple-binary-encoding.git

1. cd simple-binary-encoding

1. Run `cppbuild/cppbuild.cmd`

This is what we run in CI.
