### ISSUE TITLE
enum values that are java keywords do not have a token appended when the system property sbe.keyword.append.token  is specified

### ISSUE THREAD

**Issue by louear** [real-logic/simple-binary-encoding#1007]
example enum type definition:

```
        <enum name="MyEnum" encodingType="uint8">
            <validValue name="false">0</validValue>
            <validValue name="true">1</validValue>
        </enum>

```

here the enum values false and true are java keywords.
When running SbeTool with the system property sbe.keyword.append.token set to a suffix, the tool doesn't  append the suffix to the generated java enum.
It would be nice if a token was appended for enum values too.

**Comment by vyazelenko** [comment]
Fixed with https://github.com/real-logic/simple-binary-encoding/pull/1008.
