### ISSUE TITLE
Java Generated DTO fields for char fields aren't given public scope

### ISSUE THREAD

**Issue by jiteshvassa** [real-logic/simple-binary-encoding#1012]
@ZachBray - thanks for the new DTO functionality - looks very useful.

I tried using it but noticed that char based fields don't have the public access scope applied.

e.g. given a schema containing:

```
<type name="char16" primitiveType="char" length="16" />

<sbe:message name="MyType" id="1">
  <field name="charField" id="1" type="char16" />
</sbe:message>
```

The DTO contains:
```
void charField(String value)
```
Rather than:
```
public void charField(String value)
```
This means that its not possible to set the field in the DTO.

**Comment by ZachBray** [comment]
Hi @jiteshvassa, thank you for spotting that. I'll look into fixing the generator.

**Comment by jiteshvassa** [comment]
Thanks for the quick turnaround @ZachBray
