### ISSUE TITLE
[C++] Symbol duplication when using precedence checks

### ISSUE THREAD

**Issue by szymonwieloch** [real-logic/simple-binary-encoding#1030]
When you enable precedence checking (sbe.enable.precedence.checks=true) the generated code is invalid. The problem described here is related to the two defined string arrays: 

```
const std::string MessageType::STATE_NAME_LOOKUP[6];
const std::string MessageType::STATE_TRANSITION_LOOKUP[6];
```

Unfortunately they are not DECLARED but also DEFINED. When you define a variable in C++ it gets a linkable symbol. If you include the same header into multiple *.cpp files, the same symbol gets defined multiple times. During linking that of course fails as the linker has multiple definition of the same symbol and it just can't make the decision which one to use.

This is a major problem as not being able to include the same header file in multiple cpp files means that you for example cannot have unit tests unless you resort to major hacks.

### To reproduce

Generate C++ code for any schema with precedence checks enabled.  include THE SAME message header into two different *.cpp files and use it in some way inside to create dependency on the symbols. Compile and link. 

### Solution

Instead of using static arrays, you should use `constexpr` arrays:

```
static constexpr const char * STATE_NAME_LOOKUP[]= {...};
static constexpr const char * STATE_TRANSITION_LOOKUP[]= {...};
```

I have tested this solution by "fixing" the generated code in Python. It results in many strings getting "inlined" and does not cause any symbol confilcts.

**Comment by nbradac** [comment]
It's a good solution.  Just committed the fix.
