### ISSUE TITLE
Encoding number of group fields

### ISSUE THREAD

**Issue by qed-** [real-logic/simple-binary-encoding#109]
Suggestion: if the number of group fields were encoded in the stream, it would improve the forwards/backwards compatibility story.

e.g. if a new group field is added to the end of a schema that contains a data field, I don't think this can be made compatible with an old decoder as it can't know where the data field starts. 

If it knew how many group fields were serialized it could skip any that it didn't understand. It could thus still read data arriving after the group. As things stand a data field effectively prevents adding groups in later versions unless I'm missing something.

Doing the same for data fields would also allow old decoders to determine the message length written by newer versions and therefore where the next message starts if multiple messages were streamed to the buffer.

**Comment by mjpt777** [comment]
This type of change should be address to the FIX standards body.  

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

**Comment by haydenflinner** [comment]
It looks like this landed in rc2. So to sum up, it's possible, but the code isn't generated for you, each decoding program needs to hard-code the walk itself, as documented [here](https://github.com/real-logic/simple-binary-encoding/issues/109#issuecomment-41393393)?

**Comment by mjpt777** [comment]
This did not land in RC2. It is including in the upcoming 2.0 specification. RC2 referred to the second release candidate for the first specification.
