### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by theiceguy** [real-logic/simple-binary-encoding#116]
We're talking utopia, If we could extend this concept all the way to browser clients (ie via websockets).

**Comment by benjchristensen** [comment]
I'm exploring this right now. I have an ES6/Typescript client in Node and am experimenting with WebSockets with Reactive Streams semantics. I've got a nasty ascii based WebSocket Frame protocol right now that works and am looking at making it binary. I can do it by hand, but SBE on both sides seems like what I could use.

I don't see the SBE limitations as an issue, as the way we're considering this is:

- the WebSocket protocol is binary, with fixed length fields for the protocol of messages back and forth, and then the last field is a variable length byte[] for the application payload
- the application payload could itself be JSON, MsgPack, SBE, whatever

**Comment by odeheurles** [comment]
Hey Ben, good to see you here :)

Martin has been talking about a new version of the SBE spec so we will have some work to do to upgrade all languages. JavaScript is not supported right now but it's not a huge amount of work to port it. 

The new SBE spec makes it a lot more general purpose so it could be a good choice to implement binary encoding over WebSockets.

Martin do you have some plans / timeline regarding SBE vNext?

I will check today at the office if somebody has some time to spend on this, that would definitly be very useful for the work we do at Adaptive as well..

Would you have a bit of bandwidth on your side to contribute Ben?

**Comment by tmontgomery** [comment]
@benjchristensen Nice to hear you are looking at this! If Node is the target, then that makes things easier for generation of the codecs. I've had thoughts on how best to separate the access of fields from the layout for JavaScript codecs.

@odeheurles Martin and I would like to spend some time and simplify things and do an SBE RC3 spec compliant version. We also have some cleanup we want to do. But it all depends on our commitments and how they develop for the rest of the year.

**Comment by benjchristensen** [comment]
> new version of the SBE spec

I'm quite interested in that. We have really been liking SBE for the things we've been doing recently, but could use some collaboration and possible the new spec to take it into other places, such as Javascript/Typescript and service definitions. 

Is there a Github issue for discussing the new spec?

> Would you have a bit of bandwidth on your side to contribute Ben?

Yes. My team is actively working on these things right now so we have a window of time where we are open to adopting new tech such as this, and contributing time to make it work.

> If Node is the target

Node is a target. We also need to support the browser though.

**Comment by donmendelson** [comment]
The SBE Release Candidate 3 spec is available on the FIX Trading Community site
http://www.fixtradingcommunity.org/pg/structure/tech-specs/high-performance-specifications
That site requires a free user ID to view some resources and participate in forums.

In the future, you can expect to see FIX technical resources posted to a GitHub project with approved specs and working documents accessible to everyone. The FIX organization is working on licenses and governance policies for an open source world. I'd be interested in any suggestions about that.

**Comment by tmontgomery** [comment]
Supporting the browser is quite possible. Especially if specifically using HTML5. Having different codec generators for browsers (even different ones) and Node should be pretty easy.

**Comment by mjpt777** [comment]
Specs are now on GitHub.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

**Comment by rafalpiotrowski** [comment]
Hi,
WIP on generating SBE codecs for the web
https://github.com/rafalpiotrowski/simple-binary-encoding
 branch: typescript-support

Soon will publish DirectBuffer implementations

I have small working example but now I am concentrating on implementing the test cases as other implementations

If you want to get involved drop me a msg
