### ISSUE TITLE
how to generate nested namespaces ?

### ISSUE THREAD

**Issue by chenlucan** [real-logic/simple-binary-encoding#121]
how to use sbe tool to generate code with nested namespace ?
I'm expecting generated cpp code like:
namespace a { namespace b { 
...
}  // namespace b
}  // namespace a

I tried the following command, it generated "namesapce a/b", which is not what I want.

java -Dsbe.target.language=cpp98 -Dsbe.target.namespace=a/b -jar sbe.jar templates.xml

Thanks

**Comment by zaphoyd** [comment]
nested namespaces would be useful for us as well.

**Comment by vdidenko** [comment]
See PR #351
