### ISSUE TITLE
sbe.target.language value for c++ stubs

### ISSUE THREAD

**Issue by gilgale** [real-logic/simple-binary-encoding#137]
Hi,

What should the value of the 'sbe.target.language' option be for the SbeTool to
generate c++ stubs ?

Thanks

**Comment by himanshu24x77** [comment]
Hi, 
what should be the correct syntax for generating C++ stubs:

i am using below command it fails:

 java -sbe.target.language=cpp98 -jar sbe-1.0.1-RC2.jar example-schema.xml

**Comment by mjpt777** [comment]
You are missing the "-D" from the Java system properties.

`-Dsbe.target.language=cpp98`

**Comment by himanshu24x77** [comment]
Thanks you :100:  :+1:
