### ISSUE TITLE
C++ generated code breaks strict-aliasing rules

### ISSUE THREAD

**Issue by aligature** [real-logic/simple-binary-encoding#145]
See a simple explanation of strict-aliasing rules here:
http://blog.regehr.org/archives/959

C++ code generated from your test example (examples/resources/example-schema.xml):
```XML
<type name="ModelYear" primitiveType="uint16"/> 
```
looks like this (cpp98/code_generation_test/Car.hpp):
```C++
sbe_uint16_t modelYear(void) const
{
    return SBE_LITTLE_ENDIAN_ENCODE_16(*((sbe_uint16_t *)(buffer_ + offset_ + 4)));
}
Car &modelYear(const sbe_uint16_t value)
{
    *((sbe_uint16_t *)(buffer_ + offset_ + 4)) = BE_LITTLE_ENDIAN_ENCODE_16(value);
    return *this;
}
```

This code breaks strict-aliasing rules and may be treated as creating undefined behavior.  For example, code like this may be incorrectly reordered by the compiler or even removed completely.  We have seen issues like this in production compiled code.

I suggest changing the casting behavior to use memcpy instead as the blog referenced above indicates.

Additional background:
Both GCC and Clang allow you to specify **-f-no-strict-aliasing** to disable this optimization thought it may cause some performance degradation.  At this point in time, both the linux kernel and building Clang itself use **-f-no-strict-aliasing**.

**Comment by tmontgomery** [comment]
There is a much better explanation [here](http://cellperformance.beyond3d.com/articles/2006/06/understanding-strict-aliasing.html).

The relevant part of the [C99 spec](http://web.archive.org/web/20071217161234/http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf) that mentions this, `6.5 Expressions`, also has an important part that mentions `character type` which pertains to the mechanisms in place with SBE.

I've made several changes to unit tests and to one place in the OTF decoder, but I believe the general usage is safe as is. (As far as I can tell).

As of now, there are __no__ strict aliasing warnings being given with clang (Mac) now gcc 4.9.2 (Ubuntu) and hopefully that will continue. I have no reason to believe these are false negatives by the compiler.

So, at this stage, we'll leave it to the users to compile codecs with `-fno-strict-aliasing` if desired.

Additional points: it doesn't look like clang (on Mac) currently warns on strict aliasing. Or at least until it is really dangerous.
