### ISSUE TITLE
C++ Warning

### ISSUE THREAD

**Issue by aasaimuthu** [real-logic/simple-binary-encoding#150]
Hi,
   Sbetool generated codec messages which gives compiler error and warning like below in 32 bit machine
we have to fix these errors and warning everytime when we freshly generate the codec message from sbetool.

Is it possible to fix these warning and errors in sbebool itself while generating or can you provide the common macro for those warnings and errors?
So that we can change one place and easy for us to manage for long term.

/com_cme_globexmessaging_marketdata/PRICE.hpp:41: error: integer constant is too large for âunsigned longâ type
./com_cme_globexmessaging_marketdata/PRICE.hpp:51: error: integer constant is too large for âlongâ type
In file included from com_cme_globexmessaging_marketdata/AdminHeartbeat12.hpp:18,

./com_cme_globexmessaging_marketdata/FLOAT.hpp:41: error: integer constant is too large for âunsigned longâ type
./com_cme_globexmessaging_marketdata/FLOAT.hpp:46: error: integer constant is too large for âlongâ type

com_cme_globexmessaging_marketdata/SnapshotFullRefresh38.hpp:162: warning: this decimal constant is unsigned only in ISO C90
com_cme_globexmessaging_marketdata/SnapshotFullRefresh38.hpp:172: warning: this decimal constant is unsigned only in ISO C90

com_cme_globexmessaging_marketdata/SnapshotFullRefresh38.hpp:378: error: integer constant is too large for âlongâ type
com_cme_globexmessaging_marketdata/SnapshotFullRefresh38.hpp:388: error: integer constant is too large for âlongâ type

Thanks & Regards,
Aasai

**Comment by tmontgomery** [comment]
A lot has changed and this does not seem to happen now with moving to C++11. So, closing.
