### ISSUE TITLE
size_t for sizes in C++98

### ISSUE THREAD

**Issue by steve-o** [real-logic/simple-binary-encoding#153]
Just to have it noted, size_t should be preferred instead of int for data sizes.

**Comment by donmendelson** [comment]
We are getting reports from a static analysis tool about signed to unsigned conversion in generated FrameCodec.hpp and TokenCodec.hpp. Changing all offsets and buffer lengths consistently to size_t would resolve this.

**Comment by tmontgomery** [comment]
Going to raise this priority up a bit. Lots of changes to the codecs should be done. And this is one.

**Comment by tmontgomery** [comment]
All codec generation has been rewritten to account for type sizes and signedness. Also, OTF has been totally rewritten. This includes all offsets and lengths to be `std::uint64_t` types so that not only signedness, but size, can be asserted.
