### ISSUE TITLE
MSVC2010 warnings with codegen output

### ISSUE THREAD

**Issue by steve-o** [real-logic/simple-binary-encoding#154]
These should be hushed up or fixed:

```
warning C4244: '=' : conversion from 'const sbe_uint64_t' to 'int', possible loss of data
warning C4244: 'return' : conversion from 'sbe_uint64_t' to 'int', possible loss of data
warning C4244: 'initializing' : conversion from 'sbe_int64_t' to 'int', possible loss of data
```

The code is anything dealing with `position_ = position`  It appears an error that the member variable is an `int` and not `sbe_uint64_t`.

```
warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

The constant `-2147483648` is a `long` and should have an `L` suffix to keep it so.

**Comment by falconair** [comment]
I'm getting a similar error in VS 2015:

    ...warning C4244: 'return' : conversion from 'sbe_uint64_t' to 'int', possible loss of data

And the error is in the following function:

    int size(void) const
    {
        return position() - offset_;
    }

Where position() is defined as:

    sbe_uint64_t position(void) const
    {
        return position_;
    }

**Comment by mjpt777** [comment]
This has long since been cleaned up.
