### ISSUE TITLE
Cross language acceptance tests?

### ISSUE THREAD

**Issue by odeheurles** [real-logic/simple-binary-encoding#16]
I haven't checked yet all the tests but do we have or plan to have some acceptance tests to check that all languages respect strictly the SBE spec?

I was thinking for instance something like that:
 - we define a set of schemas for those tests, using all functionalities of SBE
 - we write tests checking that for pre-defined input we get the expected, well known result (for instance if I encode this well defined car I'm supposed to get this exact byte array). 
 - those acceptance test scenarios could be defined by us or by the guys creating the SBE spec so other implementers can reuse those same tests.

This could be very useful I think to check:
 - edge cases (null values)
 - little/big endian support
 - get the same level of test coverage and confidence with each language

Ideally the build could
 - codegen those pre-defined schemas to all languages
 - run the tests for each language 

What do you think?

**Comment by mjpt777** [comment]
Closing for now due to inactivity.
