### ISSUE TITLE
Have an interface interface for common generated methods

### ISSUE THREAD

**Issue by guillaume-alvarez** [real-logic/simple-binary-encoding#160]
All Java messages classes generated by SBETool contain some common methods:
```java
public MyMessage wrapForEncode(final DirectBuffer buffer, final int offset)
public MyMessage wrapForDecode(final DirectBuffer buffer, final int offset, final int actingBlockLength, final int actingVersion)
public int size()
```
Would it be possible to have them declared in an interface, implemented by all generated messages? For instance
```java
public interface SBEMessage {
 SBEMessage wrapForEncode(final DirectBuffer buffer, final int offset);
 SBEMessage wrapForDecode(final DirectBuffer buffer, final int offset, final int actingBlockLength, final int actingVersion);
 int size();
}
```

It would permit to easily separate message encoding/decoding (needs to know the message type) and transmission layer (only needs to manipulate buffers and offsets) when using the generated code.

**Comment by mjpt777** [comment]
If you use Java 8 you can duck type this with your own interface and a method reference.
