### ISSUE TITLE
[C++] Invalid copy constructor in generated messages

### ISSUE THREAD

**Issue by arnetheduck** [real-logic/simple-binary-encoding#164]
When copying a message, the copied message will contain a pointer to the original message (positionPtr_), which causes crashes or issues when traversing groups using the copy.

**Comment by tmontgomery** [comment]
This should be handled now that copy constructor and copy assignment operators generated.

**Comment by tamboril** [comment]
I think this was regressed as a result of PR #391.  I depend heavily on copies due to the immuability of the flyweights.  After going from a really old build prior to PR #391 to 1.7.0, all that code is broken now.
