### ISSUE TITLE
[C#] DirectBuffer subclassing support

### ISSUE THREAD

**Issue by qed-** [real-logic/simple-binary-encoding#173]
The C# DirectBuffer class is marked as sealed and has no virtual members so cannot be subclassed. The Java DirectBuffer is not final and has no final members so supports subclassing. Could the C# version be unsealed to match?

My use case is to support dynamically growing a buffer if it is smaller than required to encode a message. There is a comment in checkLimit() in DirectBuffer.java that suggests overriding this method is the intended approach. 

There might be a performance argument not to use virtual methods but there are conflicting statements online about whether it makes any difference (the same IL is generated in both cases), it would obviously need to be benchmarked.

**Comment by mjpt777** [comment]
Closing for now as C# is no longer supported unless someone wants to port the RC3 code.
