### ISSUE TITLE
Message validation before sending

### ISSUE THREAD

**Issue by odeheurles** [real-logic/simple-binary-encoding#19]
One thing that I've found very painful with protobuff, at least the .net version, is that it does not check that "required" fields have been properly honored during serialisation.

This means that when you start integrating 2 systems it's not the sender who is getting errors, but the receiver.. And those errors are not always simple to diagnose. 

Ideally we would want to fail fast and apply post serialisation checks (a bit like post conditions in design by contract).

We could have a structure in each flyweight which tracks required fields have been properly set during encoding and some check method to call once encoding is complete:

 - resetForEncode
 - writeSomeProperty
 - writeOther
 - ....
 - checkMessageValidity

Of course this is to balance with performance implications but it could make life of SBE users better. Also, like design by contract, we could turn off the check step once released and use it only during internal testing phase..

What do you think?
Is "required" the only thing to check or is there anything else we should/could validate?

**Comment by mjpt777** [comment]
I think a good option would be have an aspect validate message encoding/decoding based on IR. This could be a future enhancement.
