### ISSUE TITLE
Allow BlockLength to add padding before repeating groups

### ISSUE THREAD

**Issue by bkaraus** [real-logic/simple-binary-encoding#203]
From the SBE spec RC2:

> In order to force messages or groups to align on byte boundaries or map to an existing data 
> structure, they may optionally be specified to occupy a certain space with a blockLength
> attribute in the message schema. The extra space is padded at the end of the message or 
> group. If specified, blockLength must be greater than or equal to the sum of the sizes of 
> all fields in the message or group.
> The blockLength attribute applies only to the portion of message that contains fix-length 
> fields; it does not apply to variable-length data elements of a message.
> Extra octets specified for padding should be filled with binary zeros.

As far as I can tell, the OTF decoder currently does not respect messages with a BlockLength greater than the sum of the lengths of the fixed-length fields. This causes problems with CME's MDP feed.

**Comment by mjpt777** [comment]
The Java OTF decoder honours the block length.
