### ISSUE TITLE
Read-only Direct Buffers?

### ISSUE THREAD

**Issue by ifesdjeen** [real-logic/simple-binary-encoding#208]
Hi,

First of all, thanks a lot for a great library. Extremely useful and fun to use.

I was wondering, how useful could be a Read-Only direct buffer. In our use-case, we can't really use heap buffers due to performance issues, although in several cases we need to make sure that whatever the buffer we've got over the network isn't going to change while being read. 

Would this feature be useful, if I implement a `asReadOnlyBuffer` in `DirectBuffer` class? Please, share your thoughts.

**Comment by mjpt777** [comment]
Now available with the `DirectBuffer` interface.

**Comment by ifesdjeen** [comment]
w00t!
