### ISSUE TITLE
Encoding Primitives

### ISSUE THREAD

**Issue by mmcilroy** [real-logic/simple-binary-encoding#214]
Looking at the C++ source it seems that primitives are encoded using the native encoding of the hardware. For example you have no control over whether a signed 32 bit integer is represented using twos complement or a sign bit. Likewise for floats, the spec specifies they should be encoded according to IEEE 754, but there are no guarantees this is so - you are assuming the hardware supports this.

Is this correct? Are there any plans to enhance this in the future or is this a deliberate tradeoff in order to increase performance?

**Comment by mjpt777** [comment]
Closing this due to no further action being requested.
