### ISSUE TITLE
variable-maxlength type

### ISSUE THREAD

**Issue by marksantos** [real-logic/simple-binary-encoding#217]
To have the benefits of both fixed & variable string:

- A type is defined with a max length
- The code generator generates similar to fixed-length type but also encodes the size as prefix to the data (similar to variable type).   Exception is raised if data being copied exceeds the specified length.

This doesn't force the client to perform any padding, the field can be random-accessed, the flyweight can query its size.    (The cost is a few unused bytes depending on variance of field data length)

**Comment by mjpt777** [comment]
A length accessor has been added to variable length strings/vardata. I've also provided convenience methods to get and set strings on vardata. 

This additional support does not make sense for array data especially in the context of variable byte character encoding.
