### ISSUE TITLE
SBE over Aeron

### ISSUE THREAD

**Issue by sirinath** [real-logic/simple-binary-encoding#226]
It would be useful to have our of the box support SBE over Aeron if this can be added as a feature.

**Comment by tmontgomery** [comment]
FYI. There is a very nice integration of SBE over Aeron now.

**Comment by clifford** [comment]
Is there an example of using SBE with Aeron?

**Comment by mjpt777** [comment]
Aeron uses SBE extensively in the Archive and Cluster modules which can serve as examples.

**Comment by clifford** [comment]
Thanks Martin
