### ISSUE TITLE
Nested Groups C++

### ISSUE THREAD

**Issue by bstrysik** [real-logic/simple-binary-encoding#230]
I was testing adding additional groups to the end of the example schema. I found that if you add a group after a nested group, the additional group is put inside of the nested group.

For example, if I switch the order of the groups in the example so that the nested group comes first as shown below.

\<group name="performanceFigures" id="9" dimensionType="groupSizeEncoding">
              \<field name="octaneRating" id="10" type="Ron"/>
              \<group name="acceleration" id="11" dimensionType="groupSizeEncoding">
                  \<field name="mph" id="12" type="uint16"/>
                  \<field name="seconds" id="13" type="float"/>
                  \<field name="speed" id="14" type="SpeedText"/>
              \</group>
\</group>
\<group name="fuelFigures" id="15" dimensionType="groupSizeEncoding">
           \<field name="speed" id="16" type="uint16"/>
            \<field name="mpg" id="17" type="float"/>
\</group>

The generated C++ code has the class fuelFigures as a inside of the performanceFigures class. The fuelFigures class should be outside of the performanceFigures class.

**Comment by thomasj02** [comment]
+1

**Comment by mjpt777** [comment]
The issue existed for both C++ and Java. Can you please retest?
