### ISSUE TITLE
Incorrect encoding for bitset in Python

### ISSUE THREAD

**Issue by algo-dogs** [real-logic/simple-binary-encoding#235]
It looks like 'set' methods for a bitset in python have incorrect implementation, after a bit has been set, bits isn't returned to buffer, instead input parameter is written to buffer.

e.g. 
```
def setFinal(self, value):
    bits = struct.unpack_from('<B', self.buffer_, self.offset_)[0]
    bits = (bits | ( 0x1L << 0)) if value > 0 else (bits & ~(0x1L << 0))
    struct.pack_into('<B', self.buffer_, self.offset_, value)
    return self
```

As I understand, line 531 in PythonGenerator.java should be fixed.

**Comment by mmcilroy** [comment]
Submitted a pull request for this

**Comment by tmontgomery** [comment]
PR #276 merged.
