### ISSUE TITLE
SbeOftDecoder

### ISSUE THREAD

**Issue by transact100** [real-logic/simple-binary-encoding#237]
Hello,
  I am trying to run the examples/cpp98/SbeOtfDecoder.cpp and examples/cpp98/SbeExample.cpp.
I am able to compile SbeOtfDecoder but I am not able to generate a .sbeir file to pass to it. Which xml file in the repository is the "message-declarations-file.xml" for the example: 
$ java -Dsbe.ir.filename=<message-declarations-file.sbeir> -jar sbe.jar <message-declarations-file.xml>

As for the SbeExample.cpp. It includes baseline/MessageHeader.hpp and baseline/Car.hpp. Where is the baseline directory?

Let me know if additional information is needed.
Thanks

**Comment by SkyWitit** [comment]
You are gonna have it when you run code generator using SbeTool

**Comment by transact100** [comment]
Ok. 
I am not to familiar with java.
I ran this:
javac uk/co/real_logic/sbe/SbeTool.java
Which generated all these .java and .class files in the sbe/ directory. Did I miss something?

**Comment by SkyWitit** [comment]
I use sbe for java so I have maven plugin that does code generation, according to readme file, you can use ant build for cpp examples

**Comment by tmontgomery** [comment]
The paths and command lines are in the build.xml file. Check under the `examples:java` target to see what the steps are. You can run that from ant and it will do what you want. To run it by hand, just do the steps it is doing.

In short, the `.sbeir` file is generated from the schema via the SbeTool main at the same time as the codecs are generated. So, it is: (1) run SbeTool with appropriate paths and options, (2) compile example and OTF example, and (3) run examples.

**Comment by transact100** [comment]
Thanks fellas. I got side tracked with the documentation and got out of order.
Let me give this a go and let you know if I have any more questions.

Thanks again. Greatly appreciate it.

**Comment by tmontgomery** [comment]
No worries. If this makes sense, feel free to close.

**Comment by transact100** [comment]
Thanks guys.
