### ISSUE TITLE
install on redhat

### ISSUE THREAD

**Issue by rollen1960** [real-logic/simple-binary-encoding#239]
I receive  
[mariorollino@dev-feed simple-binary-encoding-master]$ ant cpp
Buildfile: build.xml

init:

cpp:compile:
       [cc] Starting dependency analysis for 2 files.
       [cc] 2 files are up to date.
       [cc] 0 files to be recompiled from dependency analysis.
       [cc] 0 total files to be compiled.

gtest:unzip:
    [unzip] Expanding: /home/mariorollino/WS/SBE/src/simple-binary-encoding-master/test/lib/gtest-1.7.0.zip into /home/mariorollino/WS/SBE/src/simple-binary-encoding-master/target/test/cpp

gtest:compile:
       [cc] Starting dependency analysis for 2 files.
       [cc] 2 files are up to date.
       [cc] 0 files to be recompiled from dependency analysis.
       [cc] 0 total files to be compiled.

build:

dist:

cpp:test:codegen:
     [java] Exception in thread "main" org.xml.sax.SAXParseException; systemId: file:/home/mariorollino/WS/SBE/src/simple-binary-encoding-master/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:629)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:685)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2175)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:573)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:575)
     [java]     at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:541)
     [java]     at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:252)
     [java]     at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:627)
     [java]     at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:643)
     [java]     at uk.co.real_logic.sbe.xml.XmlSchemaParser.validate(XmlSchemaParser.java:71)
     [java]     at uk.co.real_logic.sbe.SbeTool.validateAgainstSchema(SbeTool.java:179)
     [java]     at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:124)

BUILD FAILED
/home/mariorollino/WS/SBE/src/simple-binary-encoding-master/build.xml:868: The following error occurred while executing this line:
/home/mariorollino/WS/SBE/src/simple-binary-encoding-master/build.xml:631: Java returned: 1

Total time: 2 seconds

this java exception

with 

[mariorollino@dev-feed simple-binary-encoding-master]$ javac -version
javac 1.7.0_75

Please help me.

Thank

**Comment by tmontgomery** [comment]
What version of ant are you using?

**Comment by rollen1960** [comment]
Linux dev-feed.fineco.it 2.6.18-398.el5 #1 SMP Tue Aug 12 06:26:57 EDT 2014 i686 i686 i386 GNU/Linux

Red Hat Enterprise Linux Server release 5.11 

Apache Ant version 1.6.5 compiled on August 30 2006

Java from redhat standard:
java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (rhel-1.13.5.0.el5_11-i386)
OpenJDK Client VM (build 23.25-b01, mixed mode)

New Java installation:
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) Client VM (build 24.75-b04, mixed mode, sharing)

Thank for help

**Comment by tmontgomery** [comment]
See #224 . Your ant version is quite old.

**Comment by rollen1960** [comment]
thanks I will probe on Ubuntu 13.10
