### ISSUE TITLE
it possible to decode this ?

### ISSUE THREAD

**Issue by rollen1960** [real-logic/simple-binary-encoding#241]
I try to decode cme data with the sbe decoder.
Sometime I receive a error from decode:

message = 350 0B002A0001000500A3FB0777DCE9CC13010000200006C
01C3D090000000019000000AF37040062580100010000000000000000000000C007703D170000001900000092BB0800DAE102000100000001000000000000004
02C4206000000000F000000F804000070E20100030000000000000000000000C0BEF02D170000000F0000005B8F0D0094DF0600010000000000000000000000C
03B4703000000000A000000C16A06000A49020001000000000000000000000040AFEB30170000000A0000003DF10C00EA1A06000100000000000000000000001
000000000000008000000000000000019000000000000000000000000000000190000000000000000000000000000000100000000000000E605D026C40000000
2000000000000004B0BD026C40000000C0000000000000000000000000000000F0000000000000000000000000000000A0000000000000000000000000000000
A00000000000000 exception Error buffer too short at offset 354

Help me please.

Thank

The cme template is here
ftp://ftp.cmegroup.com/SBEFix/Production/Templates/

**Comment by tmontgomery** [comment]
If this is the C++ codec, then it is probably due to the buffer being too short. You should check the length of the buffer to make sure it is long enough to decode.

**Comment by rollen1960** [comment]
The cme template is here
ftp://ftp.cmegroup.com/SBEFix/Production/Templates/

**Comment by rollen1960** [comment]
If you think the length of the buffer in the function "listener.resetForDecode ( buffer , length) ;"
there are "homemade" decoder that can decode the message correctly.
If exists within the library a maximum buffer size that can be passed, I did not find this value.

**Comment by kino71** [comment]
Hello, we might have a lead on this.
Accordingly to CME, the message should be :
0B00
2A00
0100
0500
A3FB0777DCE9CC13   --transact time
01  --match event indicator (5799) (binario = 00001)
0000  ??????????' (I didn't understand where this come from)
2000 (blockLength)
06   (numInGroup)
C01C3D0900000000 ([270]="155000000") (-7 default)
19000000   ([271]="25" )
AF370400   ([48]="276399")
62580100   ([83]="88162" )
01000000   ([346]="1" )
00         ([5797]="0" )
           ([279]="0" )   *constant*
           ([269]="2" )  *constant*

00000000000000  PADDING
The next item in group starts with :
C007703D17000000  [270]="99815000000") (-7 default)
.....

SbeOtfDecoder get this one wrong.
Interestingly if we modify the PADDING above by removing 6 octets ( becoming 00) SbeOtfDecoder works.

Any thoughts ?

**Comment by donmendelson** [comment]
Note that one of the composite types for repeating group dimension in that message schema is padded to make the following block align on an 8 byte boundary.
```xml
<composite name="groupSize8Byte" description="8 Byte aligned repeating group dimensions" sinceVersion="5" semanticType="NumInGroup">
<type name="blockLength" description="Length" primitiveType="uint16"/>
<type name="numInGroup" description="NumInGroup" primitiveType="uint8" offset="7"/>
</composite>
```
Make sure that the decoder is using the correct group dimension and is honoring the offset attribute.

**Comment by kino71** [comment]
Actually it's the second element of previous group : 

group name="NoMDEntries" id="268" description="Number of Trade Summary entries" blockLength="32" dimensionType="groupSize">

to be wrong
Somehow the decoder expect a different padding between item 0 and item 1
