### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by kino71** [real-logic/simple-binary-encoding#242]
Hello ,
when I start build with "ant", I get :

    [javac] Compiling 57 source files to /home/administrator/simple-binary-encoding-master/target/main/java/classes
    [javac] /home/administrator/simple-binary-encoding-master/main/java/uk/co/real_logic/sbe/xml/MessageSchema.java:20: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;

and many other errors alike

any hint ?
Thanks

**Comment by mjpt777** [comment]
You need to build now by running the Gradle script.

$ ./gradlew
