### ISSUE TITLE
compiling SBE

### ISSUE THREAD

**Issue by kino71** [real-logic/simple-binary-encoding#243]
Hello, I'm getting this when I try : 

./gradlew
......
Could not resolve all dependencies for configuration ':runtime'.
> Could not find uk.co.real-logic:Agrona:0.2.1-SNAPSHOT.
  Searched in the following locations:
      file:/home/cme/.m2/repository/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/maven-metadata.xml
      file:/home/cme/.m2/repository/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/Agrona-0.2.1-SNAPSHOT.pom
      file:/home/cme/.m2/repository/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/Agrona-0.2.1-SNAPSHOT.jar
      https://repo1.maven.org/maven2/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/Agrona-0.2.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/uk/co/real-logic/Agrona/0.2.1-SNAPSHOT/Agrona-0.2.1-SNAPSHOT.jar
  Required by:
      uk.co.real-logic:sbe:1.0.4-RC2-SNAPSHOT

Thanks

**Comment by mjpt777** [comment]
You need to have Agrona build local as a dependence. I've updated the project to pull the latest Agrona 0.3 from Maven Central.

**Comment by kino71** [comment]
Yes, I did the same modifying build.gradle.
Now, how do I compile cpp (it was ant cpp  / ant cpp:test etc.)
I'm a bit lost, is there some docs somewhere to go through the build process ?

thanks!

**Comment by mjpt777** [comment]
The build process is a bit in transition and needs a little love and documentation. I'll leave @tmontgomery to update on how to best do that.

**Comment by tmontgomery** [comment]
C++ is now entirely cmake based build. I've updated things to make them work for me on Mac. As well as update the README. Will need some more checks for other platforms as I have time.

**Comment by asinitsyn** [comment]
Do you plan to modify ant build as well to support Argona dependency?

**Comment by tmontgomery** [comment]
@asinitsyn Not at this time. The current plan is to go forward with gradle and CMake.

Is ant your preferred build? Or just curious?

**Comment by asinitsyn** [comment]
Our main build tool is ant and I don't have gradle installed. Not a big deal. Will install gradle. 
I am more concerned with Java 7 support. Also do you plan to continue deploying latest version to maven repository? The last one was 1.0.3-RC2 back in Sept 2014. Tnx

**Comment by tmontgomery** [comment]
When the build gets to a good point in the migration, definitely will push a new release. Also, we are looking at Java 7 vs. 8 as well from #244 

BTW, the gradle wrapper should download automatically. So, it shouldn't need to be pre-installed.

**Comment by mjpt777** [comment]
I'm going to close this issue for now. We have an action to remove the old Ant build and are discussing if Java 7 should be supported for future releases. RC2 can be fetch from Maven. It is likely an future support that would cover RC3 would be Java 8 or greater now that Java 7 is end of life.
