### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by lbredeso** [real-logic/simple-binary-encoding#244]
I was hoping to be able to use SBE on a project that's stuck on Java 7, but it looks like the codecs generated by SbeTool for my schema all end up using uk.co.real_logic.agrona.concurrent.UnsafeBuffer, and Agrona requires Java 8.

Is there a path to using SBE with Java 7 that I'm missing?

**Comment by mjpt777** [comment]
Good point. Agrona should not really need anything that is Java 8. We should consider removing anything Java 8 from it.

**Comment by mjpt777** [comment]
BTW we have probably drifted into this because we want SBE to integrate well with Aeron without requiring copies. Aeron really needs Java 8 to make its wait-free concurrent algorithms work.

You should also note the Java 7 is about to end of life next month and will not be supported by Oracle. You'll then be exposed to security vulnerabilities.

**Comment by lbredeso** [comment]
Given that, I'm assuming you won't spend time making Agrona Java 7 compatible, correct?

**Comment by mjpt777** [comment]
We are discussing if it is worth supporting Java 7. We see lots of people who are stuck on it. We have to balance that against the goal of Agrona, SBE, and Aeron being peformance. Being on Java 8 is key for those serious about performance.

**Comment by lbredeso** [comment]
Did your team make a decision on Java 7 support?  I have considered attempting an Agrona pull request for Java 7 support (fixing the compile errors), but wouldn't want to waste my time if it's not a direction you want the project to go.

**Comment by mjpt777** [comment]
I'm tempted to support Java 7 by producing a cut down version of Agrona that can compile to Java 7 but want to get the other guys views. We could push a Java 7 and Java 8 version separately to Maven Central.

**Comment by lbredeso** [comment]
But if they're published as separate Agrona artifacts, wouldn't you need separate versions of sbe published to Maven Central as well?  Maybe that's not a big deal actually.

**Comment by RichardWarburton** [comment]
Not necessarily. If we split the library so that the Java 8 version of the library is "java 8 extensions" and it have it depend upon a "java 7 core" then SBE can depend upon the core. People who want Java 8 features can depend upon the extensions.

**Comment by mjpt777** [comment]
Going forward we will support Java 8+ to have good integration with Aeron. We don't have time to support multiple versions and Java 7 is now end of life.
