### ISSUE TITLE
CME groups with NoMDEntries>1

### ISSUE THREAD

**Issue by kino71** [real-logic/simple-binary-encoding#245]
Hello,
sorry to open a new request, this is related to #241.
We're using cpp decoder.

We have found that CME messages with repeating group (tested with message id=32 and id=42), every entry of the group beyond the first isn't decoded properly if there is some padding to blockLength (which is 32 in the mentioned messages).
To have the messages decoded we had to increase (Listener.cpp line 619 ):

relativeOffsetAnchor_ = bufferOffset_  + [ missing offset to 32 ]

thanks

**Comment by kino71** [comment]
It seems to work by replacing Listener.cpp line 619 with :

        relativeOffsetAnchor_ += stack_.top().blockLength_;

tests are ongoing.

**Comment by tmontgomery** [comment]
Thanks for diving into this. Let me know what else you uncover.

I believe there is a unit test that tests for this case. But could be mistaken. So, would be interested to see why that test seems to work but the template you mention does not.

Due to travel and other commitments, will be a little while before I can properly look into this.

**Comment by RogerFederer03** [comment]
Hi @kino71 ,

I have the similar issues too. I tried to replace Listener.cpp line 619 with :

    relativeOffsetAnchor_ += stack_.top().blockLength_;

It seems to work. I hope @tmontgomery  can take a look at this.

**Comment by GoshNautil** [comment]
Hi guys,

Currently I am working on CME data and the suggestions I found here were very useful. 
Nevertheless, even after applying the suggested fix, I get negative values for PRICENULL field: mantissa.
I believe that's incorrect value for market data, hence I believe there is a issue with the decoder.
Any ideas ?

Best regards,
Gosh

**Comment by tmontgomery** [comment]
The C++ OTF decoder has been totally redone. It should account for blockLength correctly now.
