### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by CuteMeerkat** [real-logic/simple-binary-encoding#246]
I tried to install SBE on Ununtu 14 and 12, both failed at the same place.

My settings are as followed:
Apache Ant(TM) version 1.9.3 compiled on April 8 2014
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

First, I run ./gradlew and the build was successful.
Then I run ant and the error message is as followed:

build:
    [javac] Compiling 57 source files to /opt/git/simple-binary-encoding/target/main/java/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /opt/git/simple-binary-encoding/main/java/uk/co/real_logic/sbe/xml/MessageSchema.java:20: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;
    [javac]                               ^
    [javac] /opt/git/simple-binary-encoding/main/java/uk/co/real_logic/sbe/ir/Ir.java:18: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;
    [javac]                               ^
    [javac] /opt/git/simple-binary-encoding/main/java/uk/co/real_logic/sbe/ir/HeaderStructure.java:19: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;
    [javac]                               ^
    [javac] /opt/git/simple-binary-encoding/main/java/uk/co/real_logic/sbe/ir/Token.java:19: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;
    [javac]                               ^
    [javac] /opt/git/simple-binary-encoding/main/java/uk/co/real_logic/sbe/ir/Encoding.java:20: error: package uk.co.real_logic.agrona does not exist
    [javac] import uk.co.real_logic.agrona.Verify;

Still some other similar errors.  It seems my gradlew fail to install all the required libraries.  Is there any solution to this issue?  Thank you so much for your help.

**Comment by mjpt777** [comment]
The project now uses Gradle to build and Ant has been deprecated. Please only use Gradlew until the Ant scripts are eventually removed.

**Comment by CuteMeerkat** [comment]
Thanks for your help.  I will try to get the c++ part working.  :)

**Comment by CuteMeerkat** [comment]
But it seems I do not have any file in ./target/dist and lack of some .hpp files.  I already used cmake to compile.  Any hint for this issue?  Thank you.
