### ISSUE TITLE
Generated cpp include guard missing namespace

### ISSUE THREAD

**Issue by lcs777** [real-logic/simple-binary-encoding#250]
Hi,

It appears the include guard needs to have the namespace name in it in addition to the class name. When I generate messages with the same name in separate namespaces, for instance

a::foo
b::foo

I cannot use them in the same code b/c the include guard is the same, both have

#ifndef _FOO_HPP_

instead of

#ifndef _A_FOO_HPP_
#ifndef _B_FOO_HPP_

(from Cpp98Generator.java)

        sb.append(String.format(
            "#ifndef _%1$s_HPP_\n" +
            "#define _%1$s_HPP_\n\n" +
              ...
            className.toUpperCase()
        ));

I think it should be

        sb.append(String.format(
            "#ifndef _%1_%2$s_HPP_\n" +
            "#define _%1_%2$s_HPP_\n\n" +
            ...
            namespaceName.toUpperCase(),
            className.toUpperCase()
        ));

Please let me know if my understanding of this is correct or not.  If so, I can send you the PR.

thanks,
lcs777

**Comment by tmontgomery** [comment]
Thanks for the PR! I somehow missed it. I've merged it now.
