### ISSUE TITLE
How to get message attribute in the C++ otf decoding

### ISSUE THREAD

**Issue by RogerFederer03** [real-logic/simple-binary-encoding#254]
Hello, 

I looked through the c++98 examples but I can not find one thing. How to get message attribute in the C++ otf decoding?

For example,
```
    <ns2:message name="AdminLogin15" id="15" description="AdminLogin" blockLength="1" semanticType="A">
        <field name="HeartBtInt" id="108" type="Int8" description="Heartbeat interval (seconds)" offset="0" semanticType="int"/>
    </ns2:message>
```
How can I get the semanticType="A" from the decoding? I think I really need some help decoding semanticType from message attribute.

Thanks

**Comment by tmontgomery** [comment]
The IR is now totally accessible in the OTF decoder just as it is with the Java OTF decoder. So, all attributes are accessible.
