### ISSUE TITLE
build procedure

### ISSUE THREAD

**Issue by dmitryme** [real-logic/simple-binary-encoding#257]
Hello, is it possible to create simple, clear instruction how I can build SBE without spending a lot of time, trying to understand all this Java stuff (maven, ant, java dependencies, which i don't understand)?

Tried to use ant - unsuccessful
Tried to use gradlew - the same shit
What else should I try?

**Comment by diginoise** [comment]
how does the ant build fail?
In what context (on which platform) do you want to use SBE ?

**Comment by mjpt777** [comment]
The current stable Java version is in Maven Central.

http://search.maven.org/#artifactdetails%7Cuk.co.real-logic%7Csbe%7C1.0.3-RC2%7Cjar

The current repo is migrating from Ant to Gradle. You can do a Gradle build with:

`$ ./gradlew`
