### ISSUE TITLE
Delete ant build

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#258]
Quite a few people seem to be getting confused with both the gradle and the ant build being around, we want to deprecate and remove the ant build. I would just push a patch that deletes it, but I'm not sure if there's still anything that it does that the gradle build doesn't do. What do people think?

**Comment by mjpt777** [comment]
Does it currently support all the tasks to build C# and C++ like the old Ant file did?

**Comment by strangelydim** [comment]
Speaking of the old ant file... How does one build C++ at the moment?  The README told me to do "ant cpp:test".  Which gives me this, on my Mac:

```
$ ant cpp:test
Buildfile: /Users/ericb/Google Drive/GitHub/simple-binary-encoding/build.xml

init:

cpp:compile:
       [cc] 2 total files to be compiled.
       [cc] clang: error: no such file or directory: '"/Users/ericb/Google Drive/GitHub/simple-binary-encoding/main/cpp/otf_api/Ir.cpp"'
       [cc] clang: error: no such file or directory: '"/Users/ericb/Google Drive/GitHub/simple-binary-encoding/main/cpp/otf_api/Listener.cpp"'
       [cc] clang: error: no input files

BUILD FAILED
/Users/ericb/Google Drive/GitHub/simple-binary-encoding/build.xml:847: gcc failed with return code 1

Total time: 0 seconds
```

**Comment by mikeb01** [comment]
You could remove the java tasks from the ant build and prompt the users to run the gradle build instead.

**Comment by tmontgomery** [comment]
Unless they have been added, the building of the OTF IR codec isn't in the gradle build. But it can be added.

**Comment by RichardWarburton** [comment]
I'll take a look at fixing this properly on Sunday.

**Comment by RichardWarburton** [comment]
@strangelydim the C++ build has been ported to cmake. I've updated the README to reflect this.
