### ISSUE TITLE
Bug [java]  generation of Enums wrong case 

### ISSUE THREAD

**Issue by David-Wales** [real-logic/simple-binary-encoding#260]
Currently when  an Enum type is generated. The Enum is capitalized even if the name in the XML file isn't. 

```
/* Generated SBE (Simple Binary Encoding) message codec */
package Examples;

public enum OrdTypeEnum
{
    Market((byte)49),
    Limit((byte)50),
    Stop((byte)51),
    StopLimit((byte)52),
    NULL_VAL((byte)0)

```

```
<enum name="ordTypeEnum" encodingType="enumEncoding">

```

This then causes an inconsistency when the relevant methods are generated on the Codec

```
    public ordTypeEnum ordType()
    {
        return ordTypeEnum.get(CodecUtil.charGet(buffer, offset + 37));
    }

/////
    public NewOrderSingle ordType(final ordTypeEnum value)
    {
        CodecUtil.charPut(buffer, offset + 37, value.value());
        return this;
    }


```

I am generating this using the ..../git/simple-binary-encoding/test/resources/new-order-single-schema.xml file

Is this a bug?

Thank you

**Comment by mjpt777** [comment]
Java coding convention is for all classes to have upper case first character.

Is an invalid set of method being generated?

**Comment by David-Wales** [comment]
Yes... sorry that's what I meant. I believe an invalid set of methods in being generated.

It's capitalising as per convention when generating the enum. But using the name specified in the XML file to generate the return type and argument types in the methods to access this (which is incorrectly cased).

**Comment by mjpt777** [comment]
Thanks. I'll test this.
