### ISSUE TITLE
Remove limit checking from SBE stub generation

### ISSUE THREAD

**Issue by mjpt777** [real-logic/simple-binary-encoding#263]
Now that the underlying buffer are the Agrona buffers we could remove the bounds checking from the SBE stubs and relay in the Agrona buffers bounds checking. 

I propose we remove the SBE bounds checking in Java to simplify the generated code.

**Comment by tmontgomery** [comment]
:+1:

**Comment by mjpt777** [comment]
Now depends on Agrona buffers doing the check.
