### ISSUE TITLE
Migrate performance build to gradle.

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#265]
Final part of #258

**Comment by RichardWarburton** [comment]
Can use https://github.com/google/protobuf-gradle-plugin to run protobuf from gradle.

**Comment by RichardWarburton** [comment]
Probably also should migrate the performance tests to a more recent version of jmh as part of the perf test migration.

**Comment by tmontgomery** [comment]
The C++ perf benchmarks are now built as part of the CMake build.
