### ISSUE TITLE
Update C++ codec for split encoding and decoding usage

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/simple-binary-encoding#271]
Update the C++ codec generation to follow the Java mechanics of a split encode & decode codec.

**Comment by tmontgomery** [comment]
actually, instead, it should be possible to use a `const` instantiation of the codec. It is not necessary to split the encoder and decoder to get the desired effects.

**Comment by tmontgomery** [comment]
Related to #152 .

**Comment by tmontgomery** [comment]
A `const` only version of a decoder is not possible without venturing into undefined behavior land due to the need to track position.

Thus, the way forward is to take the Java approach and generate encoder and decoder version.

**Comment by mjpt777** [comment]
Going to close this as not going to happen unless someone is willing to sponsor the work.
