### ISSUE TITLE
group of data fields?

### ISSUE THREAD

**Issue by robertroeser** [real-logic/simple-binary-encoding#272]
Hi,

I have a use-case where I need a group of string pairs. I'd like to do create a message like this:

```
<sbe:message name="Metric" id="1" >
        <field name="timestamp" id="1" type="uint64" />
        <group id="2" name="tags">
            <data name="name" id="3" type="varDataEncoding" />
            <data name="value" id="4" type="varDataEncoding" />
        </group>
        <data name="name" id="5" type="varDataEncoding"/>
        <data name="value" id="5" type="varDataEncoding"/>
</sbe:message>
```
Does something like this exist in SBE? I have yet to figure out how to do something like this.

Thanks,
Robert

**Comment by mjpt777** [comment]
RC3 of the specification supports this requirement. The current implementation is RC2. We would like to update the current implementation to RC3. This may happen sometime in the future if we get time or sooner if someone would like to sponsor the development.

**Comment by lbredeso** [comment]
Is there any update on RC3 status?  I find myself needing this same feature for groups, and if there were a way to vote on features, I would do so.  :-)

**Comment by mjpt777** [comment]
I'm schedule to start working on RC3 within the month.

**Comment by lbredeso** [comment]
:+1:

**Comment by mjpt777** [comment]
This has now been added.
