### ISSUE TITLE
[C++] Move assignment operator and constant qualifier

### ISSUE THREAD

**Issue by mstanichenko** [real-logic/simple-binary-encoding#274]
Hello,

I've been playing with simple-binary-encoding and CME templates and came across an issue which I don't know how to resolve. I am not able to compile generated stubs because they have a constant parameter for default move assignment operator. Below is a model example which illustrates a problem:
```C++
class A {
public:
  A(){};
  ~A(){};

  A(A&& other) = default;
  A& operator=(const A&& other) = default;
};

int main()
{
  A a;

  return 0;
}
```

```
$ g++ -std=c++11 a.cc
a.cc:7:6: error: defaulted declaration ‘A& A::operator=(const A&&)’
   A& operator=(const A&& other) = default;
      ^
a.cc:7:6: error: does not match expected signature ‘A& A::operator=(A&&)’
```

For example, this issue occurs if one generates stubs based on CME template file and tries to include  generated ```MessageHeader.hpp``` header

Would you be so kind as to elaborate on it? Do we really need a const rvalue here?

**Comment by tmontgomery** [comment]
The const snuck in there and shouldn't.

Also, the use of default is not going to make Visual Studio 2015 happy.

I'll see if I can get some time to explicitly define the correct move assignment operators in the generator today.

**Comment by tmontgomery** [comment]
Take a look and let me know if this is handled for you appropriately now.

**Comment by mstanichenko** [comment]
Hello @tmontgomery,

Thank you so much for the quick reply.
With the commit applied it works appropriately now.

**Comment by tmontgomery** [comment]
Great to hear. Thanks!
