### ISSUE TITLE
What is the status of .NET code?

### ISSUE THREAD

**Issue by buybackoff** [real-logic/simple-binary-encoding#286]
I have noticed that the C# code hasn't been updated for more than a year, while Java/C++ look active. Is C# code still relevant and is it compatible with updated Java generation tool? Why the development paused?

**Comment by odeheurles** [comment]
I've discontinued the port to C# by lack of time. I don't think any important changes have occurred since then but they are probably a few bug fixes that have been missed and would have to be ported to be on par with Java.

Martin has been talking about implementing SBE v3 and that's something I would like to port to C# as it would make SBE a lot more general purpose, and also a lot more usable in my day to day projects.

**Comment by buybackoff** [comment]
Thanks! When v3 is expected?

**Comment by mjpt777** [comment]
I plan to start working on the IR, compiler, and Java implementations of RC3 within the month.

**Comment by buybackoff** [comment]
I guess it will be compatible with RC2? 

It is very nice to here that SBE is becoming more general purpose. Where microseconds do not matter, I want to start using blobs from an existing serialization scheme (BSON), so that SBE messages are just DTOs with a header and payload (like another OSI 6 MIME). I will get benefits of the standard message header with version and templateId dispatch, and could then migrate to primitive SBE fields step-by-step when needed. At the first glance, I find it hard to map complex POCOs directly to SBE vs. automatic and versatile BSON. But then, I have a number of blittable structs that go to a byte stream directly, and SBE looks perfect to add some structure and standard here. Do you think this is an intended and sane, general purpose, use case, and it won't be significantly affected by RC3 and further changes?

**Comment by RichardWarburton** [comment]
@buybackoff I've used SBE as a framing protocol for other protocols. Even the current version is totally fine for that. You can just write an SBE header with a variable length field of bytes at the end, and plop your legacy serialization scheme in that variable length byte field. Works completely naturally.

**Comment by himanshu24x77** [comment]
I am also looking for replacing the general protocol serialization atleast
the in house. Way to go Sir.

**Comment by buybackoff** [comment]
@RichardWarburton thanks! yeah, SBE looks so natural as a replacement of a custom [message type + length] header, reinvented every time some messaging over a byte stream is needed. The question is closed, will start to gradually adopt SBE.

BTW, SBE docs say explicitly that framing [is beyond SBE scope](https://github.com/real-logic/simple-binary-encoding/wiki/Java-Users-Guide#framing), @RichardWarburton how do you use it?

**Comment by RichardWarburton** [comment]
I interpret the docs as saying that SBE messages will probably be framed by another protocol on the wire and that SBE isn't trying to replace TCP or act like a messaging product. It doesn't mean you can't wrap another protocol with them.

**Comment by buybackoff** [comment]
If you have a byte stream, how do you get from it byte arrays, which SBE takes as input? Is it another length header, or one could use SBE directly to infer the length of a message (I am still not sure that the latter is possible, only block size is in the header)? Some protocols, such as ZMQ, are already framed and fit perfectly to SBE, but I wonder how to use a plain stream over TCP socket.

SBE is streaming, but to get a buffer we need to read the entire message size before processing it (e.g. [this](https://github.com/real-logic/simple-binary-encoding/blob/master/examples/csharp/generated_stub/ExampleUsingGeneratedStub.cs#L35) comment). With the current implementation it looks like the only benefit of streaming is memory access pattern, but we cannot start processing a message until we get all its bytes.

**Comment by RichardWarburton** [comment]
In my case I'm using Aeron for the messaging protocol. So when I receive a message I know its been completely received and ordered. ZMQ has the same property.

If you want to use a streaming protocol like TCP then you /could/ wrap the header, see if you've read enough data to process the whole message and implement that logic to make it work. However this approach is quite messy and is basically conflating OSI levels 4-6 into one. I would recommend using something like Aeron or ZMQ.
