### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by zaphoyd** [real-logic/simple-binary-encoding#287]
I am curious what the general direction or plan for C++11 support is. The cpp98 output templates do include some conditionally included C++11 support. I've also seen some discussion in individual issues of having a dedicated cpp11 output format. Do you have a sense of which way things are more likely to go?

I have a few minor C++11 adjustments (at the moment, mostly related to use/support of constexpr) that I am considering making to my fork. Wondering what the best strategy for that might be that improves the chances of those changes being usable by others and compatible with future library updates.

**Comment by tmontgomery** [comment]
We are going to be accessing very soon whether the generator goes C++11 or stays C++98. There are pros and cons to each. Look for some news soon.

**Comment by himanshu24x77** [comment]
Keeping an eye Sir :-)

**Comment by tmontgomery** [comment]
SBE has been switched to C++11 for generated codecs and for OTF.
