### ISSUE TITLE
The XML Namespace doesn't seem to exist

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#290]
If you browse to `http://www.fixprotocol.org/ns/simple/1.0` (the XMLNS is all the examples) then you get 302'd a couple of times and then a "No route to host" failure. I think the XML namespace URL should point to a document explaining the namespace, eg http://www.w3.org/1999/xhtml.

This is a low priority issue for me, but seems worth fixing if time allows.

**Comment by donmendelson** [comment]
FIX Trading Community is in process of moving technical resources to GitHub. The XML schema for SBE RC3 is available here: https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/tree/master/v1-0-RC3/resources In future, the URI will be changed to point to the GitHub project.

Nevertheless, developers should take care not to depend on access to such a resource at system run-time.
