### ISSUE TITLE
Add a method to calculate the length of an SBE message

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#291]
If you're using an API which requires you to allocate or claim a block of memory in order to write the SBE message into it then you need to know the length of the encoded message.

This can be calculated by BLOCK_LENGTH + sum(length of each variable data field + size of length field of each variable data field).

However this couples users of the API to the details of the encoding and requires them to know that the size of length fields aren't part of the BLOCK_LENGTH. Having a static `requiredLength()` method would make the API easier to use.

**Comment by donmendelson** [comment]
The proposed method should also account for repeating groups. One query is: what is the required memory for a message with X repeating group entries. The inverse is: how many repeating group entries can be held by a buffer or datagram of length Y. This would be useful to help maximize bandwidth utilization.

**Comment by mjpt777** [comment]
To make this work we will need a signature that takes the number of repeating groups and a collection of all var data items. This could get quite complicated with var data in repeating groups, or repeating groups within repeating groups.

In the case of var data containing strings that needs to be encoded to a variable width encoding like UTF-8 then we would need to do the encoding before determining the length, or conservatively estimate.

Is there a possible minimum set that would be useful?
