### ISSUE TITLE
UnsafeBuffer performance mystery

### ISSUE THREAD

**Issue by lbredeso** [real-logic/simple-binary-encoding#292]
I'm modeling my SBE code on the example here:  https://github.com/real-logic/simple-binary-encoding/blob/master/examples/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java

Things are working great, but I found that encoding was taking a lot longer than I had expected, and the ```UnsafeBuffer``` constructor appears to be taking most of the time.  I'm setting it up like so:

```
final ByteBuffer byteBuffer = ByteBuffer.allocateDirect(4096);
final UnsafeBuffer directBuffer = new UnsafeBuffer(byteBuffer);
```

That constructor pretty consistently takes ~50ms on my workstation (this is 88% of total encode time for my particular example).  Is this expected?  I'm using 1.1.3-RC2, if that matters.

**Comment by mjpt777** [comment]
The byteBuffer and the directBuffer should be reused and not recreated on each message.

Check out the perf examples:

https://github.com/real-logic/simple-binary-encoding/blob/master/perf/java/uk/co/real_logic/sbe/MarketDataBenchmark.java

**Comment by mjpt777** [comment]
BTW the time is more likely in the allocation of the direct buffer.

**Comment by lbredeso** [comment]
Thanks for the tip, I'll look through the perf examples.

I had originally suspected ```ByteBuffer.allocateDirect(4096)``` as the issue, but line-by-line timings show it's actually the ```new UnsafeBuffer(byteBuffer)```.

Thanks again.

**Comment by mjpt777** [comment]
Depends on what gets inlined and what profiler you are using.

**Comment by lbredeso** [comment]
Reusing the buffers did the trick.  Closing.

**Comment by mjpt777** [comment]
Regarding the perf. If you allocate a 4K direct buffer the spec says it has to be zero'ed. Guess how long it takes to do that?
