### ISSUE TITLE
wrapForDecode functions do not validate buffer length

### ISSUE THREAD

**Issue by amluto** [real-logic/simple-binary-encoding#298]
If I pass a too-small buffer into a generated message's wrapForDecode, an exception is not thrown unless the buffer length is actually smaller than offset.  Presumably the generated code should validate:

- The message should be big enough for actingBlockLength
- The actingVersion should not result in reads of fields past the end of actingBlockLength (or those reads should be defaulted)
- (optional) actingBlockLength and actingVersion should be consistent.

**Comment by mjpt777** [comment]
The validation is now delegated to the provided buffer. The Agrona UnsafeBuffer validates all accesses.
