### ISSUE TITLE
The OTF API incorrectly parses padded groups

### ISSUE THREAD

**Issue by amluto** [real-logic/simple-binary-encoding#299]
The implementation extracts the blockLength from the GroupSize header and then completely ignores it.  The result is that groups are parsed incorrectly unless the group block length happens to exactly equal the sum of the sizes of the encodings that make up the group.

This is not the case for the NoMDEntries group in the CME's MDIncrementalRefreshBook32 message: the block length is 32 both in the schema and on the wire, but the encodings only use up 27 bytes.  The upshot is that the parser ends up five bytes off at the end of each instance of the group.

**Comment by amluto** [comment]
Something like this seems to help:

    diff -r 998228d52ef6 -r 72c3e5854a13 otf_api/Listener.cpp
    --- a/otf_api/Listener.cpp	Tue Oct 06 18:06:13 2015 -0700
    +++ b/otf_api/Listener.cpp	Thu Oct 08 16:44:12 2015 -0700
    @@ -598,20 +598,23 @@
         {
             cachedGroup_.name(stack_.top().scopeName_)
                         .schemaId(stack_.top().schemaId_)
                         .iteration(stack_.top().iteration_)
                         .numInGroup(stack_.top().numInGroup_)
                         .event(Group::END);
             onNext_->onNext(cachedGroup_);
             cachedGroup_.reset();
         }
     
    +    // Try to stay in sync while parsing groups.
    +    bufferOffset_ = relativeOffsetAnchor_ + stack_.top().blockLength_;
    +
         if (++stack_.top().iteration_ < stack_.top().numInGroup_)
         {
             // don't pop frame yet
             ir_->position(stack_.top().irPosition_);  // rewind IR to first field in group
     
             cachedGroup_.name(stack_.top().scopeName_)
                         .schemaId(stack_.top().schemaId_)
                         .iteration(stack_.top().iteration_)
                         .numInGroup(stack_.top().numInGroup_)
                         .event(Group::START);
    
FWIW, I don't see how any of this code can be correct in the case of nested groups, and my edit is no exception.  At least with this patch, it parses the message correctly.

**Comment by gricardo99** [comment]
Nice find!  I was hitting the exact same problem, wracking my brain for 5+ hours why my example app wouldn't work on MDIncrementalRefreshBook32.  I guess I should have been digging into the SBE code like you.    Thanks for posting!

**Comment by gricardo99** [comment]
I actually think the line should be something like this:
>+    // Try to stay in sync while parsing groups.
>+    bufferOffset_ = relativeOffsetAnchor_ + stack_.top().blockLength_*(stack_.top().numInGroup_ > 0);
>+

If the block has group size of zero, then you don't want to include the block length.  The CME does send some updates like this, where MDIncrementalRefreshBook has no MDEntry groups (just the MatchEventIndicator).

Without the above change, the decoder fails on those messages with zero group size.  With this change, I can decode successfully.

**Comment by tmontgomery** [comment]
The C++ OTF decoder has been totally rewritten and uses the Java OTF mechanisms now. So, this issue is no longer valid. Also, RC3 is in the process of being implemented as well.
