### ISSUE TITLE
Codecs should detect when actingBlockLength is less than generated message blockLength and prevent decode/encode

### ISSUE THREAD

**Issue by amluto** [real-logic/simple-binary-encoding#300]
If actingBlockLength is less than the block length in the schema used to generate a message class, the parser should recognize that new fields (those with offset+length beyond actingBlockLength) are not present.  Instead the generated code just reads out of bounds and returns arbitrary garbage.

**Comment by tmontgomery** [comment]
This is not C++ specific. In addition, the title is actually incorrect as there are extension characteristics included. Just not the one mentioned.

So, going to change the title to more accurately reflect the stated issue.

**Comment by mjpt777** [comment]
Acting block length can be less than current schema if the version is older. This is perfectly normal.

**Comment by amluto** [comment]
> Acting block length can be less than current schema if the version is
older. This is perfectly normal.

I realize it's normal.  At the time I filed this issue, the decoder would
malfunction.  Is this fixed now?

**Comment by mjpt777** [comment]
Can you define "malfunction" with a worked example?

**Comment by amluto** [comment]
Sorry for ignoring this for so long.  What I should have relied with, way back when, is (on a 2016 version of simple-binary-encoding):

The generated code from CME's `templates_v13.xml` for `MDIncrementalRefreshBook46` is:

```
        sbe_int32_t tradeableSize(void) const
        {
            if (actingVersion_ < 10)
            {
                return 2147483647;
            }

            return SBE_LITTLE_ENDIAN_ENCODE_32(*((sbe_int32_t *)(buffer_ + offset_ + 27)));
        }
```

which is okay if, and only if, the buffer is correctly sized for the acting version.  If the remote peer sends a too-short block or if something goes wrong, and the buffer is too short, then this will read out of bounds.  The corresponding write operations will _write_ out of bounds, which is a very severe bug, although triggering that remotely might be fairly challenging.

Something here should be checking bufferLength_.

I haven't yet checked whether this bug still applies, but I'm quite confident that it was a real bug at the time I filed it.

**Comment by mjpt777** [comment]
You can enable bounds checking for reading beyond the buffer. With this enabled the buffer is checked when wrapped and each advance of the position.
