### ISSUE TITLE
Unable to build behind a network proxy

### ISSUE THREAD

**Issue by hvram1** [real-logic/simple-binary-encoding#303]
Hi
    The gradle points to the shadow plugin and I am unable to build this due to https issues . The user name and proxies are right . I tried download the same file using curl and get the error of the site closing connections
E:\projects\simple-binary-encoding>curl --verbose -ssL https://plugins.gradle.org/m2/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.pom

* What went wrong:
A problem occurred configuring root project 'sbe'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.jdom:jdom2:2.0.5.
     Required by:
         :sbe:unspecified > com.github.jengelman.gradle.plugins:shadow:1.2.2
      > Could not resolve org.jdom:jdom2:2.0.5.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jdom/jdom2/2.0.5/jdom2-2.0.5.pom'.
            > Could not HEAD 'https://plugins.gradle.org/m2/org/jdom/jdom2/2.0.5/jdom2-2.0.5.pom'.
               > peer not authenticated
   > Could not resolve org.ow2.asm:asm:5.0.3.
     Required by:
         :sbe:unspecified > com.github.jengelman.gradle.plugins:shadow:1.2.2
         :sbe:unspecified > com.github.jengelman.gradle.plugins:shadow:1.2.2 > org.ow2.asm:asm-commons:5.0.3 > org.ow2.asm:asm-tree:5.0.3
      > Could not resolve org.ow2.asm:asm:5.0.3.
         > Could not get resource 'https://plugins.gradle.org/m2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to
get more log output.

BUILD FAILED

Total time: 8.159 secs

**Comment by mjpt777** [comment]
I've no problem with this on my Internet connection. I think you should take this up with whomever operates your proxy.

**Comment by hvram1** [comment]
Turned out to be a problem of http://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse
