### ISSUE TITLE
C++ Build using CMake error

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#304]
following the suggested actions, 

all the following 3 steps are ok.
$ ./gradlew
Then build and test with CMake in the build subdirectory created by the gradle build.

$ cd build
$ cmake ..

but  "cmake --build ."

Scanning dependencies of target gtest
[ 3%] Creating directories for 'gtest'
[ 6%] Performing download step (verify and extract) for 'gtest'
-- verifying file...
file='/fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/test/lib/gtest-1.7.0.zip'
-- verifying file... done
-- extracting...
src='/fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/test/lib/gtest-1.7.0.zip'
dst='/fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/gtest-prefix/src/gtest'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 9%] No patch step for 'gtest'
[ 12%] No update step for 'gtest'
[ 15%] Performing configure step for 'gtest'
-- gtest configure command succeeded. See also /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/gtest-prefix/src/gtest-stamp/gtest-configure-*.log

[ 18%] Performing build step for 'gtest'
-- gtest build command succeeded. See also /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/gtest-prefix/src/gtest-stamp/gtest-build-*.log

[ 21%] No install step for 'gtest'
[ 25%] Completed 'gtest'
[ 25%] Built target gtest
Scanning dependencies of target sbe
[ 28%] Building CXX object main/cpp/CMakeFiles/sbe.dir/otf_api/Ir.cpp.o
cc1plus: error: invalid option argument ‘-Ofast’
gmake[2]: *** [main/cpp/CMakeFiles/sbe.dir/otf_api/Ir.cpp.o] Error 1
gmake[1]: *** [main/cpp/CMakeFiles/sbe.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by tmontgomery** [comment]
What platform and g++ version is in use? And what is the output of the cmake command?

**Comment by chengm349** [comment]
Linux 2.6.18-308.4.1.el5 /x86_64
g++: gcc version 4.1.2 20080704 (Red Hat 4.1.2-52)
I did not get your last question. I just follow the command sequence listed and all output is listed in my original question

**Comment by tmontgomery** [comment]
gcc/g++ 4.8 is the minimum used due to `builtin_bswap`. So, try with a more modern compiler version.

You did not include the "cmake .." output. Just the cmake build output. However, the compiler version is probably the problem here.

**Comment by chengm349** [comment]
[mcheng@FLXSGL64DV02 build]$ cmake ..
latest SBE jar found: /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/libs/sbe-all-1.1.6-RC2-SNAPSHOT.jar
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
Build type(Release): perf tests turning OFF bounds checks
-- Configuring done
-- Generating done
-- Build files have been written to: /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build

**Comment by chengm349** [comment]
So the latest SBE C++ lib needs g++ 4.8 as minimum version?

**Comment by chengm349** [comment]
Is PROTOBUF the cause?

**Comment by chengm349** [comment]
I tried on  2.6.32-504.el6.x86_64 and g++ version is of g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11) Same error:

[  9%] No patch step for 'gtest'
[ 12%] No update step for 'gtest'
[ 15%] Performing configure step for 'gtest'
-- gtest configure command succeeded.  See also /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/gtest-prefix/src/gtest-stamp/gtest-configure-*.log

[ 18%] Performing build step for 'gtest'
-- gtest build command succeeded.  See also /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/gtest-prefix/src/gtest-stamp/gtest-build-*.log

[ 21%] No install step for 'gtest'
[ 25%] Completed 'gtest'
[ 25%] Built target gtest
[ 28%] Building CXX object main/cpp/CMakeFiles/sbe.dir/otf_api/Ir.cpp.o
cc1plus: error: invalid option argument ‘-Ofast’
gmake[2]: *** [main/cpp/CMakeFiles/sbe.dir/otf_api/Ir.cpp.o] Error 1
gmake[1]: *** [main/cpp/CMakeFiles/sbe.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by tmontgomery** [comment]
The OTF decoder and codecs use `builtin_bswap` so the gcc version needs at least to support that. I believe that is 4.8 minimum as I mentioned. `-Ofast` was added to gcc before that, I believe.

gcc 4.4.7 is less than 4.8. So, it will not work either.

**Comment by chengm349** [comment]
So g++ version is the cause. 

PROTOBUF is not a major concern yet

**Comment by chengm349** [comment]
RedHat EL7 /g++ 4.8.3 works.
