### ISSUE TITLE
SBE C++ lib build steps

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#305]
Before this latest version, we were advised to follow these steps to build:

$ ant cpp:test

If you have doxygen installed:

$ ant cpp

Run the C++98 examples

$ ant examples:cpp

Now the latest steps are quite different:

$ ./gradlew
Then build and test with CMake in the build subdirectory created by the gradle build.

$ cd build
$ cmake ..
$ cmake --build .
$ ctest

Is it possible to use old steps (if not exactly the same) to build?

**Comment by tmontgomery** [comment]
The ant build has been deprecated and removed.
