### ISSUE TITLE
OTF API refuses to parse new message versions

### ISSUE THREAD

**Issue by amluto** [real-logic/simple-binary-encoding#307]
Trying to parse the upcoming (version 6) CME MDP 3.0 release using the OTF API and old .sbeir data says:

    Error no IR found for message with templateId=27 and version=6 [E117] at offset 8

This is useless.  It should possibly warn, but it should parse the backwards-compatible part of the message.  After all, that's the whole point of backwards compatibility.

**Comment by amluto** [comment]
It's worse.  With new IR, the OTF API refuses to parse old versions.

How exactly is this code intended to be used?

**Comment by amluto** [comment]
Looking further, IrCollection::message takes a version parameter.  I think it shouldn't take a version parameter.

I don't know without further inspection whether the message parser can handle an IR template that has a different version (and thus a different acting block length) from the message being parsed.

**Comment by amluto** [comment]
Trying to generate an SBE IR file that contains two versions seems impossible with the tools provided.  For example, if I pass both XML templates into the compiler, I end up with an IR file that is only compatible with whichever template I pass second on the command line.

**Comment by tmontgomery** [comment]
The CME controls these schemas. We do not. We also do not currently test against them. That may or may not change in the future.

RC3 is in the works and not yet complete. In addition, as the OTF has been redone to be in line with the Java OTF, the way this works has been redone. Also, as mentioned a while ago IrCollection has gone away. So, management of IR from the OTF perspective is now totally up to the user of the OTF decoder.

With all of the above, I will set this to a question until such time as we close as invalid or make additional changes.

**Comment by amluto** [comment]
I haven't looked at the new OTF stuff, and I won't be able to until next
year.  Will the new code be able to decode a message generated by a version
of schema that differs from the version of the schema that was used to
generate the .sbeir file?  If so, then this should be okay.  If not, then
it's still a bug.

**Comment by tmontgomery** [comment]
If it has followed the extension rules for the spec and the app is using the `IrDecoder` and IR correctly with the OTF decoder, then it should, yes. But that is a lot of ifs and restrictions.

**Comment by tmontgomery** [comment]
As the C++ and Java OTF decoders are the same now, changing the title.

**Comment by mjpt777** [comment]
Closing for now as it has been rewritten. Please reopen a new issue with a specific example if it does not work.
