### ISSUE TITLE
Unable to run the performance for the MarketDataEncoding.java 

### ISSUE THREAD

**Issue by hvram1** [real-logic/simple-binary-encoding#308]
I was able to modify the build.gradle to compile and the CarBenchMark but was unable to build and execute the MarketDataBenchMark . It seems to refer to files that are not present . Any help to modify / run the same

**Comment by mjpt777** [comment]
The Java performance tests have not been ported to Gradle yet. For those please use the perf-build.xml Ant script. I will shortly be porting those to Gradle for completeness.
