### ISSUE TITLE
[C#] What happened to c# support?

### ISSUE THREAD

**Issue by damageboy** [real-logic/simple-binary-encoding#310]
I can see that 0a38768db0ebd044f57a0cf901a25eb44aabdafa removed csharp support...
Was this discussed somewhere? why? what happened?

**Comment by mjpt777** [comment]
We are upgrading the tool to support RC3 of the standard. This will be implemented for C++ and Java. Once this is complete we would welcome C# contributions.

The C# side has not been maintained over the last year plus @tmontgomery and I do not have the skills to maintain it.

The RC2 support of SBE is still available via labelled releases from the repository.

**Comment by buybackoff** [comment]
@odeheurles [was going](https://github.com/real-logic/simple-binary-encoding/issues/286#issuecomment-138294502) to port v3, I hope this is still the case.

**Comment by damageboy** [comment]
OK, thanks for the update, I just didn't understand the deletion of the old code, it now makes more sense of course
