### ISSUE TITLE
uk.co.real_logic.sbe.ir.Token

### ISSUE THREAD

**Issue by lapetiteclef** [real-logic/simple-binary-encoding#311]
Token is missing the "description" property. I added it locally, is there a reason for leaving it out?

A feature request would be to add a metadata property to describe if messages are request/reply or two-way (default). Most protocol have different messages handled in client/server direction. I actually use a prefix on the Ir Token-description now, its then used later when I generate stubs. That's why I had to add the missing description to Token locally. Example:

```
<message name="DetachAcceptor" id="2" description="request:remove acceptor">
        <field name="Id" id="1" type="uint32" semanticType="Id"/>    
</message>
```
That hack not optimal but gives me much nicer generated stub-code output.

A fix client would then only have support for NewOrderSingle in sender stub and not in receiver stub.

**Comment by lapetiteclef** [comment]
Post removed my Example message:

message name="DetachAcceptor" id="2" description="request:remove acceptor"

**Comment by mjpt777** [comment]
What you are describing seems like a richer semantic than just a description. We have considering capturing the description attribute for the IR so that Javadoc, or similar, could be generated for stubs.

@donmendelson is there such a semantic in FIX as being described here?

**Comment by mjpt777** [comment]
@lapetiteclef  BTW your example had tags in it so needs to be marked up as code which I did for you.

**Comment by donmendelson** [comment]
A FIX working group has been formed to define a machine-readable specification describing workflows, as well as data dictionary for non-standard messages. One aspect of workflow is possible responses to a request, for example acceptance (booked order), rejection, or immediate execution in response to NewOrderSingle. This is slightly different from an RPC since responses may asynchronous or triggered by market events or time. Workflows are often tied to state machine concepts, such as order states at the application layer. Session protocols are also state machines, e.g. logged on/off, heatbeat sent/expected.

This effort is still in a formative stage, and FIX Trading Community welcomes ideas. If you are interested in participating, please contact the FIX program office. Contact info: http://www.fixtradingcommunity.org/pg/structure/contact

**Comment by lapetiteclef** [comment]
@mjpt777 Yes, its more than a description. It ended up that way for us because it was simplest way to add a metadata without larger branching. If the description is added to Ir it would be great, that would solve it. 

As an example, the Aeron DriverProxy is similar level of abstraction on mappings we generate (using SBE instead of Flyweight). If you would use one SBE schema and generate such read/write queue/channel mappings. Would you not get annoyed by having a lot of generated code for messages in the proxy/adapters that are not used in that direction? That is the problem I try to solve internally with the description prefixes. Still its a hack, it would be better with support for message grouping/subsets in SBE. But I didn't see how I could get that feature without branching locally. I will try to argue for it what is a forum without arguments, right?

**Comment by mjpt777** [comment]
@lapetiteclef  We could add it to the IR. I've no real problem with that and now is even a good time as we are doing some work in that area. I'll add it anyway.

I'm just curious about the actual problem and if there is a better way to do it than a hack. Could you give an example of the groups/subset you mentioned.

**Comment by lapetiteclef** [comment]
@donmendelson Thanks for the info. Machine-readable workflow sounds like a quite complex top down approach. If you mix in states, ordering and workflow the schema gets quite complex and would also represent logic. Our workflow states are not deterministic on only SBE/FIX input. If we would see such complex schema as code then maybe: generated code coverage / complexity of schema = value. So my argument is that it might be simpler to get more value by just adding some message subsets into SBE. This comment was just to promote this feature in SBE, I don't know anything about the FIX workflow stuff. I hope its great but maybe not too great then we loose our jobs:)

Adding an optional message grouping to SBE schemas could result in no change on generated message stubs just extra metadata in Ir. Then process stays bottom up but enable another layer of code generation. Simplest suggestion would be to support the most primitive message subsets/groups: request/reply/twoway, then we could get four subsets and can generate transport code for a "request writer", "response reader", "request reader" and "response writer".

A more flexible approach would be to support message subsets definitions in the SBE schema. That could be accomplished with one list of subsets per schema and maybe a similar syntax to defining a enum or set. The mentioned request/reply/twoway subset would then just be an example of a such subset list implementation. If messages optionally could be flagged as part of one or several subsets in that list it is valuable Ir metadata. It enables to generate more detailed queue/channel mappings and also simple workflow stubs. Then readers and writers know what messages to read and write in what context.

If a read/write channel abstraction is added to SBE then a basic code generator could be included by default. But that might just complicate things because many platforms have their own interfaces/dispatch for transports. As a Real Logic related example: Agrona has the RingBuffer that might fit here but still Aeron has a nice Publication.tryClaim() feature. So transport specific code generators should generate better code. If the feature is limited to just Ir metadata that enables code generation without forcing implementation details. That would still support new code generators for transports and also minor workflow stubs. How such workflows are generated are also implementation specific, maybe other protocols are also involved, but if you could get the right subset of SBE messages from the mentioned subset definitions that enables generating repetitive side of the resulting code (create message encoders/decoders, wrap buffers, switch on typeid, write/read to channel etc).

I saw some comments about SBE schema reuse (multiple schema files) and that would be another way to enable similar code generation. I like existing approach with one schema equals one protocol, that's why I try to argue to put in message subsets instead. As an example, I checked and we currently generate 47% transport code on top of the SBE output. That is with the simple request/reply/twoway description prefix. Support of message subsets would enable SBE developers with more code generation.

Anyway, the library is superb. I'm a happy user with just our existing description prefixes.

**Comment by mjpt777** [comment]
@lapetiteclef The IR now supports the captured description attributes.

I think what you are asking for is a way of gathering a set of messages and mapping them to a proxies/stubs so that communications layer sits behind these. This metadata could even be used to generate the proxies and stubs. This is something I've often done numerous times before, it is boring boiler plate code that can be error prone.

It can be done by either taking an interface and generating the messages and proxies/stubs which works well in a single language environment. Or you can take a schema and generate for multiple languages if it contains sufficient metadata. The former is easier as you program and test to interfaces but restricts to one language.

**Comment by lapetiteclef** [comment]
@mjpt777 Thanks for the Ir Token.description commit! We continue using the description prefixes to get our needed message subsets.
