### ISSUE TITLE
Growable buffer

### ISSUE THREAD

**Issue by brianfromoregon** [real-logic/simple-binary-encoding#312]
Hi,
When encoding msgs with repeating groups and variable length data I am uncertain how large to make the buffer which sbe encodes into; making too small could cause exception for large msg. Have you considered support for a growable encoding buffer?

Thanks.

**Comment by RichardWarburton** [comment]
Would you be happy for the resizing operation to be controlled by you?

**Comment by mjpt777** [comment]
Yes we have considered it. That is why interfaces are supported with the work in migrating to RC3. This allows you to provide your own implementation that could grow if you wished. This will have a performance impact and why it is not supported in the base implementation.

**Comment by brianfromoregon** [comment]
Yeah I'd be happy to write the resizing code -- didn't realize a newer version used interfaces that sounds great thanks.

**Comment by mjpt777** [comment]
RC3 is currently in development and will be released within a few weeks.

**Comment by brianfromoregon** [comment]
Looks like growable buffers were added in SBE 1.4.0-RC4 courtesy Agrona 0.5. Nice!

**Comment by andmer** [comment]
Very nice. Thanks for heads up
