### ISSUE TITLE
Should SBE also generate a Car?

### ISSUE THREAD

**Issue by brianfromoregon** [real-logic/simple-binary-encoding#313]
Regarding your example: https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java

SBE generates CarEncoder and CarDecoder but no Car. I'm sure this is intentional and well thought through -- it follows your streaming access design principal.

But what about users who wish to pass around a Car once it's been decoded, are they meant to write a Car pojo and an adapter class which reads from CarDecoder and writes to Car? That code could be generated by SbeTool. Or perhaps even generate a Car which wraps an agrona buffer and accesses fields via offsets. Car could also be a flyweight, to avoid allocations.

Thanks in advance for clarifying your vision. Perhaps the strategy for a Car object is outside the scope of SBE, in which case I'd be interested in hearing your suggestion on what a typical, nice integration is between codecs and domain objects.

**Comment by RichardWarburton** [comment]
We used to generate a single object, eg: `Car`,  that did both encoding and decoding. Over time we decided that we would encourage better design (separating read-only view from mutation) by splitting out the encoder and decoder.

I suspect that Martin and Todd have well formed opinions on this, but from my perspective I would say that SBE should not be used for things like aggregate roots or entities in DDD terminology, but for things like domain events. In this case you're unlikely to do something like create a Car object and stash it in a map, so I'm not 100% sure this ability is needed.

**Comment by mjpt777** [comment]
@brianfromoregon  POJOs are a bit of an anti-pattern that have infected the Java world :-)

I like to map messages to method calls on an aggregate root in DDD, like @RichardWarburton has pointed out. The interface and mapping of parameters can be generated easily.

If you create POJOs then you are allocating which will greatly impact the throughput and response time of your application. SBE was designed for low latency financial trading where many applications are GC event free.

**Comment by tmontgomery** [comment]
Totally agree with @mjpt777 and @RichardWarburton . Often it is a very bad idea to conflate the concern of parsing/filling with object lifetime. This is the real issue that I have with POJOs. So, doing something outside of SBE would be a great benefit. But within SBE wouldn't be the best way to do it.

**Comment by brianfromoregon** [comment]
It might be handy to collect some best practice examples of passing the SBE event/message/data through the app a bit in a GC-friendly way. 
I think you're sort of doing this over in Amaethon project. For example amaethon.Auction looks like a flyweight-ish POJO which gets injected with SBE data pulled from Aeron. This is the sort of thing I'd like to do. Seems like the template class for amaethon.Auction could be generated by SbeTool as a starting point which can be extended by user. It may be handy if SbeTool generated it vs a different tool because SbeTool already knows how to use AuctionDecoder properly to hyrdate/reset/fill an Auction.

**Comment by mjpt777** [comment]
@brianfromoregon It would be good to write a sample service that uses SBE, Aeron, and good reactive style programming as an example to copy. Some day I hope to get the time to do that :-)

**Comment by brianfromoregon** [comment]
Checking in to see if any of you are aware of examples created in the past year, which show how to replace use of POJOs in an app as you describe.

**Comment by ssh352** [comment]
> Checking in to see if any of you are aware of examples created in the past year, which show how to replace use of POJOs in an app as you describe.

interested in examples too
