### ISSUE TITLE
Linux build error on ./gradlew

### ISSUE THREAD

**Issue by prasoon911** [real-logic/simple-binary-encoding#314]
I get the following build error. Could you please help. Thanks. Prasoon

===============================

ats@dev-2:~/SBE/simple-binary-encoding-1.1.7-RC2> ./gradlew
:clean UP-TO-DATE
:compileJava
Error: Could not find or load main class @.home.ats.SBE.simple-binary-encoding-1.1.7-RC2.build.tmp.compileJava.java-compiler-args.txt
:compileJava FAILED

FAILURE: Build failed with an exception

**Comment by mjpt777** [comment]
This looks like a JDK problem on your machine. You require the latest build of Java 8 JDK to compile this. 

What JDK have you installed? It must be the JDK and not just the JRE.

**Comment by prasoon911** [comment]
Installing JDK solved the problem. Many thanks for responding promptly - Prasoon
