### ISSUE TITLE
Missing required include in C++; <functional>

### ISSUE THREAD

**Issue by tamboril** [real-logic/simple-binary-encoding#316]
I found I have to include `<functional>` before including generated headers.

No big deal, but should be in the generated code, itself.

**Comment by tmontgomery** [comment]
Actually, the latest does exactly this.

Here is the entire block at the top of each generated file.

```
#if __cplusplus >= 201103L
#  include <cstdint>
#  include <functional>
#  include <string>
#  include <cstring>
#endif
```
