### ISSUE TITLE
Generate modified names when they would otherwise be invalid

### ISSUE THREAD

**Issue by JeffGreen** [real-logic/simple-binary-encoding#317]
There are generated variable names that occasionally are invalid method or variable names in the target language.  

For example, if the message-declarations-file.xml has a variable named final, this will cause the Java generator to generate invalid code since final is a keyword and thus final() is an invalid method name.

A simple although non-exhaustive proposal is to append something like an underscore if the variable name matches a language keyword.

**Comment by mjpt777** [comment]
If a keyword from C++ or Java is used you get an error message like the following:

```
ERROR: at <sbe:message name="Car"> <field name="final"> name is not valid for C++: final
Exception in thread "main" java.lang.IllegalArgumentException: at <sbe:message name="Car"> <field name="final"> name is not valid for C++: final
```

Are you saying code is generated and the error is not displayed? I generated the above message by naming a field as "final". No code was generated.

**Comment by JeffGreen** [comment]
A quick look at the code seems like it's validating against the unmodified variable name "Final" (not a keyword) but then generates based on a call to toLowerFirstChar() resulting in "final".  I believe this lower casing was introduced between 1.1.7 and 1.3 fwiw.

**Comment by mjpt777** [comment]
Thanks I see what you mean now. I also found a couple of instances where we are not checking for keywords on type and message names which has been fixed.
