### ISSUE TITLE
RC3 release jar

### ISSUE THREAD

**Issue by lcs777** [real-logic/simple-binary-encoding#318]
Hi,

I saw that the 1.3-RC3 was released,  (Great work.  Thanks!).  However, it does not seem like the jar was uploaded as the previous ones were. 

Please advise.

thanks,
lcs777

**Comment by tmontgomery** [comment]
Things have moved around slightly. The `sbe-tool` jar is the one that was just SBE before.

**Comment by dxwu88** [comment]
Hi Ics777, where is the 1.3 RC# release? Thanks

**Comment by mjpt777** [comment]
@dxwu88 Are you asking if C# is still supported? If so, we do not have a C# port of RC3 but would welcome contributions.

**Comment by javapowered** [comment]
how can I get latest stable release? is it ok to use trunk? Or it's better to checkout particular revision, the one marked "1.3.1-RC3 release"?

**Comment by mjpt777** [comment]
@javapowered The latest stable version is in Maven for Java. 

http://search.maven.org/#search%7Cga%7C1%7Csbe

However we like to keep HEAD pretty stable so it is often OK to go with that.

For C++ you need to build from head or go back to a label. HEAD for C++ would be the best option at present.
