### ISSUE TITLE
Getting started with SBE.

### ISSUE THREAD

**Issue by Lee0112358** [real-logic/simple-binary-encoding#324]
New to SBE, would like to start learning more. I have recently succesfully built and installed SBE. I am using C++ on linux. Where exactly is the sbe-tool located in the root folder? I have an example-schema.xml schema I would like to start using but how does one actually create the c++ stubs? 

Thanks in advance.

**Comment by tmontgomery** [comment]
You will want to run the Java application, SbeTool, and set the property `sbe.target.language` to `Cpp`. That will generate C++ stubs for the schema you input.

**Comment by Lee0112358** [comment]
Thanks for the response. As of now, I am using the following command:
java -Dsbe.target.language=cpp98 -jar sbe-1.3.1-RC3-SNAPSHOT.jar example-schema.xml. 

The sbe-1.3.1-RC3-SNAPSHOT.jar I am running is located in /simple-binary-encoding-master/build/libs.

Getting the following error. 
no main manifest attribute, in sbe-1.3.1-RC3-SNAPSHOT.jar

Do I have the correct sbe-tool path? There are a bunch of other directories created when I installed SBE and not sure which .jar to use.

**Comment by mjpt777** [comment]
If I check out the latest and run the below it works for me in the project dir. Alternatively you could fetch the released JAR from Maven Central. 

http://search.maven.org/#search%7Cga%7C1%7Csbe

```
java -Dsbe.target.language=cpp \
    -Dsbe.output.dir=target \
    -jar sbe-tool/build/libs/sbe-tool-1.3.2-RC3-SNAPSHOT-all.jar \
    sbe-samples/src/main/resources/example-schema.xml
```

**Comment by mjpt777** [comment]
https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

**Comment by Lee0112358** [comment]
That worked, thanks very much for the help. Appreciate the time.

**Comment by dxwu88** [comment]
If I want to generate C# code, how should I specify the language option sbe.target.language? Thanks!

**Comment by mjpt777** [comment]
@dxwu88 https://github.com/real-logic/simple-binary-encoding/blob/master/build.gradle#L674

**Comment by dxwu88** [comment]
It works. Thanks!!!

________________________________
