### ISSUE TITLE
Variable data length overload return types

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#327]
The put*(byte[], offset, length) methods in SBE return the length, which any caller knows because its passed into the method. They could actually return `this` in the same way that the other methods on the encoder do. The encoding methods that take strings directly - where you don't actually know how long the encoding was actually return this and not the length.

Is this the right direction to go with the API or should they all return `this`.

**Comment by mjpt777** [comment]
I think this would be a good change.
