### ISSUE TITLE
Encoder and Decoder toString() methods

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#328]
Something that I think would make it easier to debug the code that uses SBE encoders and decoders would be to have `toString()` methods that printed out the current names and values of the fields. Since it is expected to just be used in a debugger these methods don't need to be performant or allocation-free.

For me this is a low priority issue, however, if you agree with the concept but don't have time to implement I'm happy to contribute a patch.

**Comment by tmontgomery** [comment]
The encoders and decoders are stateful as they hold position information. As such, doing this is a little trickier. It means that the user would have to be careful when wrapping, calling `toString()` and re-wrapping.

**Comment by mjpt777** [comment]
As @tmontgomery points out this could be tricky for tracking the state. However we could save another field that is the initial position to support a toString().

**Comment by RichardWarburton** [comment]
I'm going to close this issue as I've decided to write an OTF decoder that prints out a Json representation of an SBE message, based upon the example Otf Decoder.
