### ISSUE TITLE
SimpleBinaryEncoder

### ISSUE THREAD

**Issue by satyasarmawalkingtree** [real-logic/simple-binary-encoding#330]
**SimpleBinaryEncoder**

I have taken code schema from github and run with maven ,but i am unable to get all the stubs generated. But in your example you have mentioned CarEncoder and some methods ,i am able to generate car Stub only and also some methods were skipped.
can  anyone suggest me to workout  the exact result.
-------------------@satyasarma----------------

**Comment by mjpt777** [comment]
If you clone the repo you can see the samples. You need to run the SbeTool main class after downloading it from Maven Central. It is configured with a number of system properties. 

https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

Can you provide a worked example of "some method were skipped".?

**Comment by mjpt777** [comment]
Closing as no example has been provided.
