### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by unicomp21** [real-logic/simple-binary-encoding#332]
IntelliJ complains about:

                    <arguments>
                        <argument>${project.build.resources[0].directory}/schema.xml</argument>
                    </arguments>

saying: "Cannot resolve symbol"

However, mvn clean install works fine.

**Comment by mjpt777** [comment]
What file is that in?

**Comment by mjpt777** [comment]
I've local versions on a number of machines and IntelliJ does not complain on any of them.

**Comment by unicomp21** [comment]
pom.xml

**Comment by unicomp21** [comment]
15.0.3

**Comment by tmontgomery** [comment]
For IntelliJ, it works better to import gradle instead of generating the files.

**Comment by mjpt777** [comment]
@tmontgomery That is what I do and it works well.
