### ISSUE TITLE
suggestion from user perspective: doc update on varData composite

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#333]
Hey all, I had a particularly large string I was modelling, in the test dataset it was 750+ characters long and it was naturally failing using sample uint8 (255 length) varDataEncoding composite. 

I wasn't sure why at first because my initial faulty thought was variable length data also meant unfixed length data as well, but of course reasoning through the composite definition and generated code you can get the true picture.

Could be a useful note in the docs for others who make a similar sort of mistake.

**Comment by mjpt777** [comment]
I've updated the samples to use uint16 to make cut and paste easier.

Do you think we should generate an error or truncate to the maximum size? I'm interested what others think to?

**Comment by andmer** [comment]
I vote document in the example and generate an error. I prefer to know
explicitly if my data "breaks" the model so to speak.

On Tuesday, February 23, 2016, Martin Thompson <notifications@github.com>
wrote:

> I've updated the samples to use uint16 to make cut and paste easier.
>
> Do you think we should generate an error or truncate to the maximum size?
> I'm interested what others think to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/real-logic/simple-binary-encoding/issues/333#issuecomment-187942520>
> .
>


-- 

Thanks,
-Andre

**Comment by mikeb01** [comment]
Generate an error, nothing more annoying than silent data corruption.

**Comment by mjpt777** [comment]
@tmontgomery Do you think the C++ should do a similar check?

**Comment by tmontgomery** [comment]
C++ has a better option. Simply expose the length type in the put calls, I think.

**Comment by mjpt777** [comment]
The issues comes from encoding and not the reverse. If the size is > 255 and the type is uint8 then the memcpy will be for the wrong length.

**Comment by tmontgomery** [comment]
I understand. The "put" methods on var data are for encoding. By making the length argument the same type as the schema VarDataEncoding length field, the compiler _can_ warn/error on truncation.

**Comment by mjpt777** [comment]
Great.
