### ISSUE TITLE
interface for generated decoder/encoder?

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#334]
What do you think about adding an interface to the generated encoder/decoder for the common generic bits?

My interest is because I would like to pass various decoder/encoders into a some base class which contains them and hide some setup etc..

public interface Decoder<T> {
    T wrap(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion);
    etc....
}

public interface Encoder<T> {
    int sbeBlockLength();

    int sbeSchemaId();

    int sbeSchemaVersion();

    int sbeTemplateId();

    int encodedLength()

    T wrap(final MutableDirectBuffer buffer, final int offset);
   
    etc....
}

example case along the lines of some method that inits them in a baseclass that owns it:

    public void initEncoder(Encoder aEncoder) {
        mEncoderByteBuffer.clear();
        int offset = 0;
        MessageHeaderEncoder wrap = mHeaderEncoder.wrap(mEncoderUnsafeBuffer, offset);
        wrap.blockLength(aEncoderAdapter.sbeBlockLength())
                .templateId(aEncoderAdapter.sbeTemplateId())
                .schemaId(aEncoderAdapter.sbeSchemaId())
                .version(aEncoderAdapter.sbeSchemaVersion());
        offset += wrap.encodedLength();
        aEncoderAdapter.wrap(mEncoderUnsafeBuffer, offset);
    }

    public void initDecoder(Decoder aDecoder, byte[] aBytes) {
        mDecoderUnsafeBuffer.wrap(aBytes);
        int offset = 0;
        mHeaderDecoder.wrap(mDecoderUnsafeBuffer, offset);
        offset += mHeaderDecoder.encodedLength();
        aDecoder.wrap(mDecoderUnsafeBuffer, offset, mHeaderDecoder.blockLength(), mHeaderDecoder.version());
    }

**Comment by mjpt777** [comment]
This would be possible and is an interesting idea. One of the goals with the move to RC3 was to have no library dependencies on SbeTool with the generated code like we did have with the old CodecUtil. 

Would you be happy with this interface being generated in the same package?

**Comment by andmer** [comment]
Yeah. definitely.

**Comment by mjpt777** [comment]
I'll have a look at doing something for the RC4 release.

**Comment by mjpt777** [comment]
@andmer Does this match your requirements?

**Comment by andmer** [comment]
Looks great, thanks Martin!

On Wed, Mar 16, 2016 at 2:54 PM, Martin Thompson <notifications@github.com>
wrote:

> @andmer <https://github.com/andmer> Does this match your requirements?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/real-logic/simple-binary-encoding/issues/334#issuecomment-197488350>
>



-- 

Thanks,
-Andre
