### ISSUE TITLE
Schema Generation

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#335]
I was just wondering if the SBE tool uses a schema as an input to encode/decode messages based on that or does it also build the schema itself? For example could it be used to build something like the attached schema file?
[streamlinemktdata.txt](https://github.com/real-logic/simple-binary-encoding/files/154800/streamlinemktdata.txt)

**Comment by mjpt777** [comment]
SBE can take a schema like the attached and from it generated stubs to do the encoding and decoding of messages. It can also generate IR that can be used for dynamic decoding of messages. The samples and benchmarks do this.

https://github.com/real-logic/simple-binary-encoding/tree/master/sbe-benchmarks/src/main

https://github.com/real-logic/simple-binary-encoding/tree/master/sbe-samples/src/main
