### ISSUE TITLE
can output c++ code

### ISSUE THREAD

**Issue by tanbench** [real-logic/simple-binary-encoding#336]
If you have a sbe project code that have build successfully ，but cannot find c++ code。
There are lot java class that output in
\simple-binary-encoding-master\sbe-benchmarks\build\generated\uk\co\real_logic\sbe\benchmarks\fix.
In the java class,import uk.co.real_logic.agrona.concurrent.UnsafeBuffer.They are java style.

If my project is c++ project,how can I  build sbe project to out c++ class ,so I can use it in my c++ project.

**Comment by tanbench** [comment]
can anyone give car.h and MarketDataIncrementalRefreshTrades.h?so I can build this project.thanks you very much.
#include "uk_co_real_logic_sbe_benchmarks_fix/MarketDataIncrementalRefreshTrades.h"

**Comment by tmontgomery** [comment]
If you used the cppbuild script, then the C++ generated files are placed under `cppbuild/Release/generated`.

For usage of SbeTool for generating C++ output, the wiki should have some info. Also, the CMakeLists.txt files contain calling of SbeTool to generate C++ codecs.
