### ISSUE TITLE
On the fly decoder

### ISSUE THREAD

**Issue by kumarroopesh** [real-logic/simple-binary-encoding#337]
Hi,
I am trying to do decoding of SBE encoded messages in c# .NET.
But it comes out just after calling IrDecoder.Decode() method.

Can you please help me in doing OTF decoding of SBE encoded messages.

**Comment by tmontgomery** [comment]
C# is not currently supported in the RC3 versions. So, not sure what is going on, but we don't intend at this time to work on C#.
