### ISSUE TITLE
can I  use quickfix and sbe to connect CME order routing?

### ISSUE THREAD

**Issue by tanbench** [real-logic/simple-binary-encoding#338]
hi,tmontgomery
     In my c++ project,I want to use quickfix tool and sbe tool to connect CME order routing.
Do you think it is possible to solve it.can you give me so methods or tool to solve it.
thanks you for your guide.

**Comment by tmontgomery** [comment]
I don't really know enough about quickfix to actually answer this. But if quickfix supports the FIX SBE spec, then it should be possible.

**Comment by donmendelson** [comment]
I don't represent either QuickFIX or CME, but to the best of my knowledge, CME does not *yet* support SBE for order entry. To communicate, the same protocol must be recognized on both ends of a connection.
