### ISSUE TITLE
on-the-fly doesn't decode messages with nested repeating groups correctly

### ISSUE THREAD

**Issue by russtotheb** [real-logic/simple-binary-encoding#339]
using an SBE template which contains a single repeating group which itself contains three repeating groups the message does not decode properly when using the on-the-fly decoder

in the decodeGroups method the end group index is being set incorrectly. it is currently being found by simply looking for the next occurrence of an end group token. in the case of nested repeating groups this will happen to be the the end group token of one of the inner groups and not the end group token for the group for which start was just called. this will only be observed when decodeGroups was called recursively from within the decoding of a parent group. once the lower value is returned and the blocks in the repeating group have all been decoded the index on which token is to be processed will be lower than expected and some repeating groups will attempt to be decoded at the message level. note that there needs to be more than one nested repeating group for the end group index to come back lower than intended.

a fix could be in the findNextOrLimit method - instead of just looking for the first end group token and returning it should look for the end group token of the group for which start group was called

**Comment by mjpt777** [comment]
I assume this is from an older version of SBE? We believe this bug was fixed with the migration to RC3.  See https://github.com/real-logic/simple-binary-encoding/issues/230

**Comment by russtotheb** [comment]
Yes - this was found with RC2. Is the RC3 decoder backward compatible with RC2? Our systems currently use RC2 extensively and do not have any current plans to move to RC3.

**Comment by mjpt777** [comment]
The wire protocol is backwards compatible. The API has evolved based on what we learned from usage and also to support integration with Aeron.
