### ISSUE TITLE
Variable length composites with uint32 lengths result in incorrect bounds checks

### ISSUE THREAD

**Issue by lbradstreet** [real-logic/simple-binary-encoding#340]
Creating the following composite:
```
        <composite name="varBytes">
            <type name="length" primitiveType="uint32"/>
            <type name="varData" primitiveType="int8"/>
        </composite>
```
results in a warning (as expected, as the spec only allows uint8/uint16 lengths).

The generated code has an incorrect bound check at `if (length > -3)`:

```
    public MessageContainerEncoder putPayload(
        final byte[] src, final int srcOffset, final int length)
    {
        if (length > -3)
        {
            throw new IllegalArgumentException("length > max value for type: " + length);
        }

        final int headerLength = 4;
        final int limit = parentMessage.limit();
        parentMessage.limit(limit + headerLength + length);
        buffer.putInt(limit, (int)length, java.nio.ByteOrder.LITTLE_ENDIAN);
        buffer.putBytes(limit + headerLength, src, srcOffset, length);

        return this;
    }
```

**Comment by mjpt777** [comment]
We should do the bounds check and also consider the max uint32 value that is reserved for null.

**Comment by mjpt777** [comment]
The issue with the `-3` checks comes from the long value being truncated. You can cope for now by using the following. We'll need to add extra validation for this case in Java.

``` XML
    <composite name="varDataEncoding">
        <type name="length" primitiveType="uint32" maxValue="2147483647"/>
        <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8"/>
    </composite>
```

**Comment by mjpt777** [comment]
For Java we should change the error to say a `maxValue` must be set if uint32 is used with a suggested value and not warn when it is.

**Comment by mjpt777** [comment]
I was thinking about the importance of support lengths greater than 64K bytes. A possible usage I can see on another project I'm involved with is using SBE to frame existing FIX tag value messages. Some of these will be drop copies that can a few MB in size, so greater than 64K is genuine requirement even in the FIX context. Messages of a few MB in size are quite reasonable in many contexts.

We need to support 32-bit lengths but be careful when dealing with values that don't fit in a Java 32-bit signed type.

**Comment by lbradstreet** [comment]
Thanks @mjpt777. With the maxValue fix this seems to work well. Our use case is also in the few MB range, so we will likely just set a lower maxValue on it anyway.

**Comment by tmontgomery** [comment]
1.3.5-RC3 has the set of changes in it and has been released.

@lbradstreet feel free to try things out now with UINT32 length and close this if all working well.

**Comment by lbradstreet** [comment]
Thank you. Works well for me.
