### ISSUE TITLE
How to use the SBE Tool?

### ISSUE THREAD

**Issue by shengsd** [real-logic/simple-binary-encoding#341]
#####  In the page Intermediate Representation
`$ java -Dsbe.ir.filename=<message-declarations-file.sbeir> -jar sbe.jar <message-declarations->file.xml>`

1.After `$ ./gradlew`, there are many *.jar files, which one could be used as the sbe.jar ?

##### In the page Sbe Tool Guide
`java [-Doption=value] -jar sbe-tool-1.3.3-RC3.jar <message-declarations-file.xml>`

2.You listed a lot of options except `sbe.ir.filename`, besides, I don't know their possible values.

3.I am a Cpp OTF user, and I have an XML file `templates_FixBinary.xml` from ftp://ftp.cmegroup.com/SBEFix/CertAutoCertPlus/Templates. 
Could you show me how to generate its Serialized IR file?

**Comment by mjpt777** [comment]
`java -Dsbe.ir.filename=schema-ir.sbeir -jar sbe-all-1.4.0-RC4.jar templates_FixBinary.xml`
