### ISSUE TITLE
how to set buffercapacity in sbe without prediction

### ISSUE THREAD

**Issue by satyasarmawalkingtree** [real-logic/simple-binary-encoding#342]
how to set buffercapacity in sbe without prediction. i want  to set the buffer capacity without prediction or hardcoded. what is  the best solution plz. guide me.

**Comment by mjpt777** [comment]
Can you provide a bit more detail on what you would like to do? Maybe with a worked example.

**Comment by satyasarmawalkingtree** [comment]
when we are encoding  any data which is variable data.we can't predictable how much size(nuber of bytes) it has .without predicting the size how can we assign the size  for ByteBuffer

**Comment by satyasarmawalkingtree** [comment]
ByteBuffer. allocateDirect (number of bytes)

**Comment by mjpt777** [comment]
If you don't know the size of your data within a reasonable bound then SBE might not be the best option. I prefer to chunk data rather than have unbounded message sizes.

A possible option is to create an implementation of MutableDirectBuffer that will resize an underlying buffer to accomidate unbounded messages.

**Comment by satyasarmawalkingtree** [comment]
final ByteBuffer byteBuffer = ByteBuffer.allocateDirect(Integer.valueOf(ConstantsUtility.BUFFER_SIZE));
		final UnsafeBuffer directBuffer = new UnsafeBuffer(byteBuffer);
this is we are right now hardcoding buffersize.but we need to pass dynamic data size.

**Comment by tmontgomery** [comment]
A schema will have an explicit max length based on field sizes for numInGroups and for length in VarDataEncoding. Also, the system probably should have an implied max length based on practical sizes for those fields or based on convention or configuration.

Depending on the complexity of the schema, determining the size of a message based on var data lengths as well as number of groups is relatively straight forward. In fact, there is an enhancement for this #291 

An implementation of MutableDirectBuffer that can resize is also quite useful on its own.

Another option is to pick a size that seems reasonable. Use the normal UnsafeBuffer. And keep bounds checking on. When a bounds check is hit, then resize to double previous value and re-encode.

**Comment by mjpt777** [comment]
@satyasarmawalkingtree I've pushed an ExpandableArrayBuffer to Agrona that will expand to the required capacity of your messages. Please give it a try and provide feedback.

https://github.com/real-logic/Agrona/commit/a481ead567d2b6cf16a34aac70ab1ad86d88af26
