### ISSUE TITLE
How to use composite type of varDataEncding in Another Composite Type

### ISSUE THREAD

**Issue by satyasarmawalkingtree** [real-logic/simple-binary-encoding#343]
I tried with ref ,but it is not generating setter(put) methods for String(Data) types.

  <composite name="VehicleYear" id="1" dimensionType="groupSizeEncoding">
             <type name="code"  primitiveType="uint16"/>
             <ref name="name"  type="varDataEncoding"/>
        </composite>
        <composite name="varDataEncoding">
            <type name="length" primitiveType="uint8"/>
            <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8"/>
        </composite>

**Comment by mjpt777** [comment]
var-data is only supported at the end of a message or repeating group. Please see the FIX SBE specification for greater details.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding
