### ISSUE TITLE
on netty3.x issue

### ISSUE THREAD

**Issue by zhao141** [real-logic/simple-binary-encoding#345]
i can`t get sbe ByteBuffer or byte[]. so,how do I transfer protocol? sbe and aeron is strong coupling?

**Comment by tmontgomery** [comment]
SBE depends on Agrona. Not Aeron.

The user supplies the ByteBuffer or byte[]. In the case of netty, it would be netty.

Then the ByteBuffer or byte[] would be wrapped in an UnsafeBuffer (from Agrona). And then that is passed to the codecs wrap methods.

Check the [wiki](https://github.com/real-logic/simple-binary-encoding/wiki/Java-Users-Guide) and the [samples](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java) for some more examples. The source of the ByteBuffer or byte[] is up to the application.

**Comment by zhao141** [comment]
before that. i have tried. but,unsafebuffer.array() and unsafebuffer.bytebuffer() is null. i can`t transfer. i was frustrated

**Comment by mjpt777** [comment]
@zhao141 UnsafeBuffer wraps an underlying buffer that can be ether a ByteBuffer or a byte[]. Dependign on which one is used then the other will be null.

If you wish to use SBE with Netty then wrap a ByteBuffer or a byte[] and with an UnsafeBuffer to  perform encoding or decoding. You can keep a reference to the underlying buffer and pass it to Netty once encoded with SBE, or vice versa for decoding.
