### ISSUE TITLE
java to c++ from disk

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#346]
Hi Todd,

disclosure, I'm generally on the Java side of things, but I need to test decoding in C++ as well.

I have written an SBE bytebuffer to disk from Java as such:

        try (RandomAccessFile out = new RandomAccessFile("mds.sbe", "rw")) {
            ret.flip();
            byte[] data = new byte[ret.limit()];
            ret.get(data);
            out.write(data);
        } catch (Exception e) {
            e.printStackTrace();
        }

I have a test reading this back in with my java code, no problem but with my c++ code but I am having a slight problem, maybe you can help me pick out the stupid error i made if you get a minute. I'd appreciate it! thank you.

main.cpp
https://gist.github.com/andmer/3207bd16ca72afb5b2aee0b041c2a39a

generated code.h
https://gist.github.com/andmer/ad38618a8e8edae7e65b5c36de5deb4b

output I'm getting:

/home/andmer/.CLion2016.1/system/cmake/generated/sbe_fix-1378652b/1378652b/Debug/sbe_fix
messageHeader.blockLength   =105
messageHeader.templateId    =87
messageHeader.schemaId      =1
messageHeader.schemaVersion =1
messageHeader.encodedLength =8
terminate called after throwing an instance of 'std::runtime_error'
  what():  buffer too short [E100]

Process finished with exit code 134

**Comment by tmontgomery** [comment]
check what sizeof(buffer) returns. I believe it is too small in that it is the size of the pointer and not the size of the buffer itself. What is being passed to wrapForDecode is too small.

**Comment by andmer** [comment]
hmm. ok. so it reports 8, which is the same as the encoded length of messageHeader, does that indicate i am not picking up the actual body of the message only the header?

sizeof(buffer) = 8
messageHeader.blockLength   =105
messageHeader.templateId    =87
messageHeader.schemaId      =1
messageHeader.schemaVersion =1
messageHeader.encodedLength =8
terminate called after throwing an instance of 'std::runtime_error'
  what():  buffer too short [E100]



Do you guys have any similar tests somewhere I could look at?
i.e. Going from a java bytebuffer to disk then back into char* c++ from disk

**Comment by andmer** [comment]
maybe its sizeof problem like you mentioned. is there a correct way around this you might recommend?

i tried hardcoding a buffer size to see what would happen and it seemingly now works.
MessageHeader hdr;
hdr.wrap(buffer, 0, 0, 2048);

MarketDataSnapshotFullRefresh mds;
mds.wrapForDecode(buffer, hdr.encodedLength(), hdr.blockLength(), hdr.version(), 2048);

sizeof(buffer) = 8
messageHeader.blockLength   =105
messageHeader.templateId    =87
messageHeader.schemaId      =1
messageHeader.schemaVersion =1
messageHeader.encodedLength =8
mds.encodedLength =105
symbol::MY-REQ-ID

**Comment by andmer** [comment]
more info, so looks like read can actually determine the correct size. I wonder why sizeof fails in this regard.

char* read(const char* name) {
    ifstream fl(name);
    fl.seekg(0, ios::end);

    size_t len = (size_t) fl.tellg();
    cout << "len=" << len << std::endl;

    char* ret = new char[len];
    fl.seekg(0, ios::beg);
    fl.read(ret, len);
    fl.close();
    return ret;
}

**Comment by tmontgomery** [comment]
There are C++ versions of the samples and several unit tests.

In this example, since you are only reading a single message and that message is contained in the entire file, I would use the file length. The length is the size of whatever buffer that is in use. Like you would normally use `snprintf`, `memcpy`, etc.

**Comment by andmer** [comment]
ok. thank you.
