### ISSUE TITLE
c++ read different than java?

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#347]
Hi Martin, Todd!

I may very well be doing something wrong in c++ but I'm seeing different results parsing same buffer from disk. some if it is just garbled, strings seem primarily the culprit there.

http://www.mergely.com/OfH9FzNR/

I have isolated this into a test project below:
https://github.com/andmer/sbe_fix
mvn:clean, mvn:compile, mvn:test to run the java decode

Any guidance or input is much appreciated!

**Comment by tmontgomery** [comment]
From a quick look, one thing that stands out is that the strings aren't null terminated when you access var data get methods. You probably want the std::string returns or copy them and null terminate them.

**Comment by andmer** [comment]
wonderful, this is my error. thank you.
