### ISSUE TITLE
Question on Java implementation

### ISSUE THREAD

**Issue by fbyrne** [real-logic/simple-binary-encoding#348]
Hi, 

I have a question on why the implementation chose to use org.agrona.* for ByteBuffer over the java.nio.ByteBuffer?

Thanks, 
Fergus

**Comment by mjpt777** [comment]
The Agrona buffer allows the wrapping of `ByteBuffer`, `byte[]`, off heap address, or another implementation supported by the interface such as the `org.agrona.ExpandableArrayBuffer`. `ByteBuffer` alone would be too limiting.
