### ISSUE TITLE
[C++] constexpr qualifier in static const field getters

### ISSUE THREAD

**Issue by vdidenko** [real-logic/simple-binary-encoding#353]
This is a follow up enhancement to the #195 issue.

I am tailoring the incoming message reaction, and it would be great to use a switch statement in the vein of the [structurechart](https://github.com/real-logic/simple-binary-encoding/issues/195#issuecomment-53376192)'s comment. Similarly to @structurechart I ran into the `constexpr` requirement.

Would it be possible to discuss a solution similar to the sample commit vdidenko/simple-binary-encoding@fe16a8ce1f1e14916d3ebe363978549a26267d5c? It introduces public constexpr fields and uses them to maintain the getter function signatures.

I have only changed the fields I _think_ I care about, but should I make the pull request similarly modifying all `static const` declarations touched by the original solution at real-logic/simple-binary-encoding@a601c48409a093abda3ad6808407712fa677dfaf?

**Comment by vdidenko** [comment]
Actually, is there a specific reason, why all those values are accessible through getters, but not through namespace or class `constexpr`s? For one thing, it's simplify storing strings, as currently there is an issue with the `sbeSemanticType` in the proposed code (warning: `ISO C++11 does not allow conversion from string literal to 'char *'`)

**Comment by vdidenko** [comment]
Updated the sample commit reference in the issue with a version which builds without warnings and preserves getters' signatures.

**Comment by tmontgomery** [comment]
I don't think it is necessary to do all the `static const` declarations. I am a little leery of the MSVS compiler support on `constexpr` for this, but I believe it is better to go ahead. As long as the getter signatures are preserved, it should be OK for those currently using it.

**Comment by vdidenko** [comment]
If the code is OK as is, then I will make it into a PR by separating it from the nested namespaces issue (constexpr support is on the top of the nested namespaces branch by accident, there is no dependency).

**Comment by vdidenko** [comment]
After reviewing it, it will be easier to make this pull request after the nested namespaces work.

**Comment by vdidenko** [comment]
@tmontgomery, the PR #355 is posted for a review.

**Comment by vdidenko** [comment]
Solution to this issue is reasonably challenged in the PR discussion at https://github.com/real-logic/simple-binary-encoding/pull/355#issuecomment-239317154.

**Comment by vdidenko** [comment]
@tmontgomery, when you refer to:

> add the new statics when it is C++11 and can be constexprs

are you talking about the functions? I thought you did not want to touch their signature at all, or do you mean to have a second function?

**Comment by vdidenko** [comment]
@rigtorp, yes making current functions `constexpr` should work, but I was under impression that was not a welcome change at the time of the PR. If I am wrong then it is a simple fix indeed.

**Comment by rigtorp** [comment]
@tmontgomery @vdidenko I don't think changing `const` to `constexpr` if supported by the compiler would cause any issues at all, same ABI etc.

**Comment by vdidenko** [comment]
I will get the patch out tomorrow - I am late now out of the door. It will be more reliable to be on the same page with a patch in from of us. OK?

**Comment by tmontgomery** [comment]
@vdidenko no worries. Sorry. What I meant was it might be cleaner to make the `static constexpr` be dependent on C++11 being used and not even being there if not. Along the lines of:

```cpp
#if __cplusplus >= 201103L
static constexpr std::uint16_t SbeBlockLength{(std::uint16_t)47};
#endif
static const std::uint16_t sbeBlockLength(void)
{
    return 47;
}
#endif
```

**Comment by vdidenko** [comment]
As I did the patch it added a new compile-time warning, which I would like to avoid. Specifically,

    static SBE_CONST_KIND char * sbeSemanticType(void)

Causes (as expected) the warning in generated code:

    +/.../cppbuild/Release/generated/code_generation_test/Car.h:132:16: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    +        return "";
    +               ^

On one hand I do not know how valuable it would be to keep the SemanticType getter as constexpr. If not (and it is not for me personally), then we can keep is as const:

    static SBE_CONST_KIND char * sbeSemanticType(void)

If we would like to have consistent getters, then we can change the macro definition to have the extra `const` after the `constexpr`:

            "#if __cplusplus >= 201103L\n" +
            "#  define SBE_CONST_KIND constexpr const\n" +
            "#else\n" +
            "#  define SBE_CONST_KIND const\n" +
            "#endif\n\n" +

[There is an extended answer on stackoverflow about it](http://stackoverflow.com/a/14117121/836097), but it does not seem to cover static member functions.

When I do this, then the headers in `sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/` give me a hard time - seems that those are files manually generated and checked in:

    In file included from /.../sbe-tool/src/main/cpp/otf/IrDecoder.h:40:
    /.../sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/TokenCodec.h:25:11: warning: 'SBE_CONST_KIND' macro redefined [-Wmacro-redefined]
    #  define SBE_CONST_KIND constexpr
              ^
    /.../cppbuild/Release/generated/baseline/VarDataEncoding.h:25:11: note: previous definition is here
    #  define SBE_CONST_KIND constexpr const
              ^

Where do there `uk_co_real_logic_sbe_ir_generated` headers come from? Do I need to manually regenerate them? (if we are not going to leave the SemanticType getter as const)

**Comment by rigtorp** [comment]
@vdidenko I wouldn't recommend to change too much stuff. Add some `constexpr` and for ease of use with C++11. Please don't break the existing API like your last patch did.

**Comment by vdidenko** [comment]
@rigtorp yes, to limit the scope of change is my intention too. Yet just brute adding `constexpr` is what causes ISOC++11 warnings and will possibly become invalid in C++14. If you have a feedback on how to resolve the warnings, it would be great.

I think it can be addressed with the `constexpr const` macro, but then it is worth to wait for @tmontgomery 's guidance on the headers which conflict with that macro.

**Comment by vdidenko** [comment]
In #355 I have changed more API than just added static constants, and it may be a bigger problem. I hope I am wrong but please consider this:

According to my current understanding, here is what we had before PR #355:
![pre353](https://cloud.githubusercontent.com/assets/74995/17639732/b3c347c0-60ba-11e6-9d65-c37a68f1296e.png)
Here is what we got after pre-processor as the result of the #355 PR:
![now](https://cloud.githubusercontent.com/assets/74995/17639734/b94f7f9c-60ba-11e6-953c-b70513fab40c.png)
As you can see the return type has changed (lost constness) and I consider it a bug. The bad news is that the bug got similarly expanded in @abbradar's PR #366.

What I would like to see ideally is something like that:
![ideal](https://cloud.githubusercontent.com/assets/74995/17639813/c4ebe29a-60bb-11e6-8af9-68a4704dda71.png)
However, in the spirit of minimal change here is what I am suggesting to change results of PRs #355 and #366 to:
![minimal](https://cloud.githubusercontent.com/assets/74995/17639824/fef55d40-60bb-11e6-8108-2db9898e9475.png)
I also think that having `SBE_CONST_KIND` set to `constexpr const` is a bad idea because it make the macro to define a function qualifier and a portion of a return type. I would rather have the  macro as:

    #if __cplusplus >= 201103L
    #  define SBE_CONSTEXPR constexpr
    #else
    #  define SBE_CONSTEXPR
    #endif

, while setting `SBE_CONSTEXPR const` to all return types where `const` was replaced with `SBE_CONST_KIND`.

@tmontgomery, I will have an example commit for the above today or tomorrow morning. It will still break the headers in `sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/`. Please, let me know what to do with them.

**Comment by rigtorp** [comment]
@vdidenko You're latest patch looks great to me! Should be fully backwards compatible and allow constexpr use on modern compilers.

A follow up patch would be to add the const function qualifier.

**Comment by tmontgomery** [comment]
thank you both for looking at this. Regenerating the Token/Frame IR codecs looks good to me.
