### ISSUE TITLE
Can we add a new variable length data into repeating group without breaking the old decoder?

### ISSUE THREAD

**Issue by deepblueli** [real-logic/simple-binary-encoding#356]
Hi, 

I can see that the [sample schema](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml) in sbe-samples project contains an example of having variable length data field within a repeating group, e.g. the below:-
```
<group name="fuelFigures" id="10" dimensionType="groupSizeEncoding">
            <field name="speed" id="11" type="uint16"/>
            <field name="mpg" id="12" type="float"/>
            <data name="usageDescription" id="200" type="varDataEncoding"/>
</group>
```

Is it possible to add a new var length data field into repeating group above without breaking the old decoder that doesn't read the new var length data field?

I can see that current generated code by SBE tool couldn't skip the new var length data field in a repeating group because the size of var-length data field is not part of the group's blockLength according the [RC4 spec](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-RC4/doc/03MessageStructure.md#sequence-of-message-body-elements).

Does it mean that repeating group can only properly support fixed-length fields, but not variable-length fields?

Thanks!

Best Regards, 
Guang Sheng

**Comment by mjpt777** [comment]
You are correct this is not part of the spec. I would like to have seen a block header that listed the number of var data items contained to allow for such an extension. Unfortunately the committee decided they did not want to support this. See [this](https://github.com/real-logic/simple-binary-encoding/issues/109) discussion.

Maybe a version 2.0 of SBE could support this sort of feature.

**Comment by deepblueli** [comment]
Thanks Martin  for the confirmation.

**Comment by deepblueli** [comment]
I would suggest to remove the var length data field in the repeating group in the example schema, or add comment there that it is not properly supported for extension. 

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml

**Comment by mjpt777** [comment]
It works in the example and the extension. You just cannot extend adding a var data field in a repeating group.

You should voice your concerns on the spec. I think it is a significant omission. It is controlled by the FIX Committee. At Real Logic we just provide the reference implementation.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

**Comment by deepblueli** [comment]
Thanks, will voice my concern there.

**Comment by deepblueli** [comment]
I think there is a possible upgrading procedure when introducing new var data field in repeating group.

It is to upgrade the decoder first, which will check the actingVersion, and able to decode messages of both old and new version of the schema.
Then follow by upgrading the encoder side to encode new var-length field in the group. 
This seems to work.

**Comment by mjpt777** [comment]
The very problem with extension is that some systems are not easy to upgrade and thus you are stuck. For example, the encoder could have been developed as an FPGA with a very long upgrade cycle.
