### ISSUE TITLE
[Java] Generating toString() methods / extending generator?

### ISSUE THREAD

**Issue by xiangh-fr** [real-logic/simple-binary-encoding#357]
Somewhat reanimating  #328 here, but since it was dropped by requester in favor of the OTF option rather than rejected (and it seems #178 is the same for C++):

* Would adding toString() generation be appreciated ? Would there be format constraints ? (or should options be provided)
* Is one of those option recommended instead (less convenient at first, but more adaptable to application requirements):
 * Using OtF decoding ?
 * Using the IR to generate display specialized classes ? 
 * Adding some hooks in the generation process to facilitate adding such methods (and also customizing interface hierarchy) ?

note: more generally, would need one of the last three method for some other purpose in any case (for which I implemented the OtF option for now, but since documentation warns about performance impact, and I could likely generate instead...)  so opinions on them or alternatives (to add functionalities without requiring a fork) more generally welcome.

**Comment by tmontgomery** [comment]
Providing a means to dissect a message is probably extremely useful.

#328 mentions the trickiness with tracking state with this. That can be avoided, but it does mean that the codecs become more complex and require more state. IMO, OTF decoding is fairly easy and probably more generically useful.

**Comment by mjpt777** [comment]
The state can be managed in a `toString()` method with local variables, I gave it some thought a little while back. I like the idea of offering this without OTF as the IR does not need to be available if you have the stubs. Very useful in a debugger, or for doing aspect based debugging.

I'd be supportive of this change but don't have the time to do it in the near future.

**Comment by mjpt777** [comment]
Would you be able to finish this off and add the closing of the message and other types plus remove the trailing `|` character so people could parse the output if necessary?

**Comment by xiangh-fr** [comment]
Sure, though not tomorrow.

However could you detail what you mean/expect by "closing of the message and other types" ?
(the trailing | character for example, while not necessary, is not something I see as preventing parsing - it's more like the final SOH in fix to me. However it at least requires either to de-specialize "separators" present in strings, or to delimit values potentially containing those.)

Should I generate some kind of factory and/or provide parsers (generated or reflection based?) ?
[writing those should help me see potential issues, in fact]

**Comment by mjpt777** [comment]
I've fixed the trailing '|' output. Thanks for the help with this!
