### ISSUE TITLE
Incorrect Code Generation?

### ISSUE THREAD

**Issue by structurechart** [real-logic/simple-binary-encoding#362]
Hi,

I am using this XML file:
ftp://ftp.cmegroup.com/SBEFix/Production/Templates/templates_FixBinary.xml

After I generated with the latest build, it generated MDIncrementalRefreshVolume37.hpp that contains:

>     class NoMDEntries
>     {
> ..........
>         inline NoMDEntries &next(void)
>         {
> ...........
>          }
> ...........
>         const char *mDEntryType(void) const
>         {
>             static sbe_uint8_t mDEntryTypeValues[] = {101};
> 
>             return (const char *)mDEntryTypeValues;
>         }
> ...........
>     }
> 

According to the XML template, MDEntryType is a const char not a const char*.

I would expect that MDIncrementalRefreshVolume37.hpp contained "char mDEntryType(void) const" instead as the XML template states MDEntryType is a char.

Thanks in advance.

**Comment by tmontgomery** [comment]
That schema does not parse correctly with the latest snapshot because it has a keyword ("Final") in it.

```
$ java -Dsbe.target.language="cpp" -jar ~/work/simple-binary-encoding/sbe-tool/build/libs/sbe-tool-1.5.0-SNAPSHOT-all.jar templates_FixBinary.xml
Exception in thread "main" java.lang.IllegalStateException: Invalid property name='final' please correct the schema or consider setting system property: sbe.keyword.append.token
	at uk.co.real_logic.sbe.generation.cpp.CppUtil.formatPropertyName(CppUtil.java:96)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.lambda$generateChoices$1(CppGenerator.java:652)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
```

In addition, this wants RC2 XSD and that is not supported by this reference implementation. And it seems it also will not validate against the current XSD.

As we do not control this schema, we can not really tell what might be going on.

If you can replicate the issue in a smaller, controlled, validated RC4 schema for the latest snapshot, more than happy to take a look at it when we get time.

**Comment by mjpt777** [comment]
This is the same issue as [#352](https://github.com/real-logic/simple-binary-encoding/issues/352)

**Comment by structurechart** [comment]
This is different from issue #352 although it has the keyword "final".

This ticket is for the strange interpretation of a const char field.

After changing "final" to "_final", it will be able to generate as others suggested in issue #352.

**Comment by tmontgomery** [comment]
If you change the "final" to "_final", then it still fails XSD validation.

**Comment by mjpt777** [comment]
The XML provided on the link is not valid. If I change it to the following top level element and provide the system param `-Dsbe.keyword.append.token=_` then it can generate stubs.

This needs to be raised with the CME as we cannot help.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:messageSchema xmlns:ns2="http://www.fixprotocol.org/ns/simple/1.0"
                   package="mktdata"
                   id="1" version="6"
                   semanticVersion="FIX5SP2"
                   description="20150109"
                   byteOrder="littleEndian">
...
```

**Comment by structurechart** [comment]
Right, this ticket isn't for the "final" keyword issue, which was addressed in issue #352 as you pointed out.

This ticket is for the strange interpretation of a const char field.

Regarding the invalid XSD, I am talking to CME to fix it.  However, I think it unlikely affects how the generator handles the const char field...just my guess as all others are fine.

**Comment by tmontgomery** [comment]
@structurechart you might be correct in that the parsing doesn't affect the generator. However, taking a quick look, I can't see what the issue might be. Therefore, and as we do support this in our limited spare time, working on this will have to wait until we have time. A valid, focused schema helps to make that easier to diagnose.

But even if we did find a problem and implement a fix, the original schema being invalid from an RC4 perspective doesn't mean that the codec generated would be valid to use.

**Comment by tmontgomery** [comment]
In addition, looking at what you mention and the entire generated field methods, this might be the correct semantic to provide. At least more flexible and useful.

```cpp
        static const std::uint64_t mDEntryTypeLength(void)
        {
            return 1;
        }

        const char *mDEntryType(void) const
        {
            static sbe_uint8_t mDEntryTypeValues[] = {101};

            return (const char *)mDEntryTypeValues;
        }

        char mDEntryType(const std::uint64_t index) const
        {
            static sbe_uint8_t mDEntryTypeValues[] = {101};

            return mDEntryTypeValues[index];
        }

        std::uint64_t getMDEntryType(char *dst, const std::uint64_t length) const
        {
            static sbe_uint8_t mDEntryTypeValues[] = {101};
            std::uint64_t bytesToCopy = (length < sizeof(mDEntryTypeValues)) ? length : sizeof(mDEntryTypeValues);

            std::memcpy(dst, mDEntryTypeValues, bytesToCopy);
            return bytesToCopy;
        }
```

While it is a single value, it is also a `char` type. For ease of use, the index version of the method can be used to get the single `char` value similar to what you want. i.e. `mDEntryType(0)`. The determination of the size can be done via the Id of the field, or the length, etc. All of which can be static constants.

While this is probably open to debate, I don't believe this needs to be changed at this time.

**Comment by structurechart** [comment]
@tmontgomery thanks for taking time to look into it.  Appreciate it.

I just thought that the generator would generate something uniform across the board for the same type of fields.

For instance, the generator generates the following for the template MDIncrementalRefreshBook32 (the generator offers similar interfaces for other templates as well):

        MDEntryTypeBook::Value mDEntryType(void) const
        {
            return MDEntryTypeBook::get((*((sbe_char_t *)(buffer_ + offset_ + 26))));
        }

The user would write something like this:
switch (type): {
//blah..
}

Then, even if the template provider adds a new type, the user doesn't have make any code change.

Now, the generator generates the interface differently and so the code to retrieve the field is different from the rest.

I understand that it is a design choice of using enum versus array of char + access through index.  But I feel that it would be nice to have a unified interface.

**Comment by tmontgomery** [comment]
@structurechart The field in question is a constant field for a char and not an enum. This is all in the control of the schema. RC3 added constant enums, in part, for this reason.

There are other considerations with how constant fields are used and some assumptions about how they might change (as they don't require any binary compatibility). @mjpt777 and I have discussed it and will continue to.
