### ISSUE TITLE
[Java] Decoding uint32

### ISSUE THREAD

**Issue by ThorbenLindhauer** [real-logic/simple-binary-encoding#363]
The generated code for a decoder with a `uint32` field is:

```java
public long myField()
{
    return (buffer.getInt(offset + 0, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFF);
}
```

This uses Java's default int to long conversion when the value is returned. That means, when encoding the null value `4294967294L` (or any long value where the 32nd bit is 1) a negative value is returned (`-2L` here).
Shouldn't the generated code use Java 8's `Integer.toUnsignedLong` for conversion in order to get out what is put in?

Cheers,
Thorben

**Comment by mjpt777** [comment]
Are you using an old version? The code was corrected a few months back to be the following:

```java
public long myField()
{
    return (buffer.getInt(offset + 0, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
}
```

**Comment by ThorbenLindhauer** [comment]
Oh, I see. Thanks for your answer and sorry for my confusion.

**Comment by mjpt777** [comment]
No worries. Thanks for checking it out.
