### ISSUE TITLE
null value for optional presence strings

### ISSUE THREAD

**Issue by robertchengkt** [real-logic/simple-binary-encoding#364]
for example, some type like this, without a nullValue given, what is the default nullValue in SBE for it?<type name="StringLength50" description="String With Length 50 Characters " presence="optional" length="50" primitiveType="char" semanticType="String"/>

**Comment by mjpt777** [comment]
The SBE standard does not have support for optional value strings. Best to ask the question here.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding
