### ISSUE TITLE
representing empty character value for primitive type char in example xml

### ISSUE THREAD

**Issue by rbh02** [real-logic/simple-binary-encoding#365]
For the following enum:

``` xml
<enum name="TestCharNull" encodingType="char">
<validValue name="NULL_VALUE"></validValue>
<validValue name="POSITIVE">+</validValue>
<validValue name="NEGATIVE">-</validValue>
</enum>
```

The empty char value throws a null pointer exception while trying to generate the cpp decoder files.
Is this the correct way of representing nulls for chars or is this a bug with the SBE decoder?

**Comment by RogerFederer03** [comment]
I have the same issue too. The empty char value throws a null pointer exception while trying to generate the cpp decoder files.

**Comment by tmontgomery** [comment]
The schema is invalid, I think. You should validate it with the XSD. A validvalue must have a value, IIRC.

**Comment by RogerFederer03** [comment]
@tmontgomery  Thanks for the explanation.
