### ISSUE TITLE
Cannot Build?

### ISSUE THREAD

**Issue by structurechart** [real-logic/simple-binary-encoding#375]
I am trying to build simple-binary-encoding-1.5.1 and I got the following error in  cppbuild/Debug/CMakeFiles/CMakeError.log:

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_3b3b8/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_3b3b8.dir/build.make CMakeFiles/cmTC_3b3b8.dir/build
gmake[1]: Entering directory `/home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3b3b8.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_3b3b8.dir/CheckSymbolExists.c.o   -c /home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_3b3b8
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_3b3b8.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_3b3b8.dir/CheckSymbolExists.c.o  -o cmTC_3b3b8 -rdynamic 
CMakeFiles/cmTC_3b3b8.dir/CheckSymbolExists.c.o: In function`main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_3b3b8] Error 1
gmake[1]: Leaving directory`/home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp'
gmake: **\* [cmTC_3b3b8/fast] Error 2

File /home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/\* */
# include <pthread.h>

int main(int argc, char*\* argv)
{
  (void)argv;
# ifndef pthread_create

  return ((int*)(&pthread_create))[argc];
# else

  (void)argc;
  return 0;
# endif

}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_d496f/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_d496f.dir/build.make CMakeFiles/cmTC_d496f.dir/build
gmake[1]: Entering directory `/home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d496f.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_d496f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake3/Modules/CheckFunctionExists.c
Linking C executable cmTC_d496f
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_d496f.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_d496f.dir/CheckFunctionExists.c.o  -o cmTC_d496f -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_d496f] Error 1
gmake[1]: Leaving directory`/home/myhome/simple-binary-encoding-1.5.1/cppbuild/Debug/CMakeFiles/CMakeTmp'
gmake: **\* [cmTC_d496f/fast] Error 2

My pthread lib is pthread not pthreads :(

$ ldconfig -p | grep pthread
    libpthread.so.0 (libc6,x86-64, OS ABI: Linux 2.6.32) => /lib64/libpthread.so.0
    libpthread.so.0 (libc6, OS ABI: Linux 2.6.32) => /lib/libpthread.so.0
    libgpgme-pthread.so.11 (libc6,x86-64) => /lib64/libgpgme-pthread.so.11
    libevent_pthreads-2.0.so.5 (libc6,x86-64) => /lib64/libevent_pthreads-2.0.so.5

**Comment by tmontgomery** [comment]
We rely on CMake for this. So, this looks more like a CMake issue. You might try the CMake archives for help on this one.
