### ISSUE TITLE
(C++) No version-checking code generated for group fields

### ISSUE THREAD

**Issue by tamboril** [real-logic/simple-binary-encoding#386]
While there are `xxxSinceVersion()` and `xxxInActingVersion()` methods to check
before decoding top-level fields, there are no such methods generated for groups in C++.

**Comment by tmontgomery** [comment]
I do not believe that repeating groups can be added (and I am sure they can not be removed) to a schema by versioning according to the FIX/SBE spec. Can you point to the area in the spec that talks about doing this?

**Comment by tamboril** [comment]
[Template extension](http://www.cmegroup.com/confluence/display/EPICSANDBOX/MDP+3.0+-+Message+Schema#MDP3.0-MessageSchema-TemplateExtension).  Maybe it's just a CME convention.

I requested this because I encountered it in the attached schemas going from version 6 to version 8.  In this case, template 32 had a new group added to it.

[templates_FixBinary.zip](https://github.com/real-logic/simple-binary-encoding/files/473223/templates_FixBinary.zip)

**Comment by tmontgomery** [comment]
You can add fields to an existing repeating group, but you can't (to my knowledge) legally add a repeating group to an existing message schema that doesn't have a repeating group.

To be able to handle it, you can use the schema version in the header as well as the templateId to demux into a different codec.

**Comment by tamboril** [comment]
Strange, but you're right.  I can't find the schema referenced in the XML (RC2), and the RC3 schema does not support  `sinceVersion`  in the `<group>`  tag.

**Comment by donmendelson** [comment]
This issue was addressed in RC4, which has since been promoted to Draft Standard.

> A repeating group may be added, but only after existing groups and if there are no subsequent variable data elements at the end of the message.

In the SBE XML schema, a group, like other elements of blockType, has a sinceVersion attribute.

**Comment by mjpt777** [comment]
@donmendelson I'm surprised this got added. It was not pointed out in the changes. I remember the discussion around it and the best way to address this properly was to record the number of repeating groups and var data fields in the header to properly do extension for all cases. Many schemas have var data at the end and this is just plan dangerous.

Why was it added and not called out?

**Comment by donmendelson** [comment]
Correction about history: the quoted statement was added in RC3 (approved Dec. 2014) and was noted in release notes:

> Statements added to say whole repeating groups or variable data may be added to a message without breaking compatibility so long as the added elements are at the end of a message.

That Schema Extension Mechanism section was further refined in RC4 (published March 2015).

This should not be a surprise!

**Comment by mjpt777** [comment]
I missed that change. Could have been my issue but I did try to follow it carefully and somehow missed that.

Regardless I think this is very wrong. It is a shame that such error prone features make it into a standard. I think this sort of thing hurts the FIX Community image by creating hacks rather than facing the problems with a comprehensive and inclusive approach. Nothing we can do now but I hope things improve for the future.

You never answered with why was it added? This is the important point. Is there a good case we can refer to help users understand?

**Comment by donmendelson** [comment]
@mjpt777, I want to emphasize that this is not simply my opinion, but rather the consensus of the working group at that time.

**Working group meeting notes**
Topic: Extension mechanism for repeating groups and variable length data
Posted issues: General Q/A: Simple Binary Encoding specification Release Candidate 2 David Chapman 15 April 2014, CDT RC3 Proposals: Proposal to enhance SBE extension mechanism
Status: Aug. 11 call consensus: do not change headers but consider alternatives such as schema updates on the wire [Another tracked issue]
Pros and cons: Con: Not useful for high performance trading. No specific use case given.
If framing header is used, then extension by adding repeating groups and variable data to end of message can be supported without changing header.

**Comment by mjpt777** [comment]
@donmendelson I know this is not just your opinion and that the working group decided it. As I said we cannot change history but we can learn for the future.

Try considering how it looks when a closed group makes a decision without user review or attempting an implementation. In this case a feature has been added that is error prone and yet "No specific use case given". No system is perfect but all can be improved.

**Comment by tmontgomery** [comment]
There are two items here that somehow seemed to have been lumped together. Extension of vardata, which _always_ appears at the end of a message or repeating group. And extension of a repeating group, which _may_ appear at the end of a message or outer repeating group. But _may_ be followed by vardata. These are two very different things to extend. It's a shame they were not broken out slightly differently.

**Comment by tmontgomery** [comment]
We will look into adding `sinceVersion` calls to the repeating groups. Using these will require some application logic, as is normal for versions. But at least the methods will be available.

**Comment by mjpt777** [comment]
Also be aware that a repeating group or var data could be added inside a repeating group resulting in a very unpleasant situation to debug.

**Comment by thomasj02** [comment]
Has there been any progress on exposing `sinceVersion` in the repeating groups? CME links to this project ([from this page](http://www.cmegroup.com/confluence/display/EPICSANDBOX/MDP+3.0+-+Simple+Binary+Encoding)) and claims it is a reference implementation, but without `sinceVersion` you can't parse data with the new CME template

**Comment by tmontgomery** [comment]
@mjpt777 and I have been quite busy. We do plan to get to this as soon as we can.

**Comment by mjpt777** [comment]
`sinceVersion` metadata is now exposed on all fields, groups, and var data on the Java decoders with this commit. https://github.com/real-logic/simple-binary-encoding/commit/56a323f1f1b676b5fa298df111378c108dd89a92

**Comment by tmontgomery** [comment]
The methods have also been added to the groups for the C++ codecs as well with commit b9c4443226a1542801896a194161165bcb4f6bb2
