### ISSUE TITLE
[C++]: Simplify bool methods in codecs

### ISSUE THREAD

**Issue by vdidenko** [real-logic/simple-binary-encoding#389]
Currently the C++code generator produces return statements like this:

``` c++
return (m_actingVersion >= mdEntryTypeSinceVersion()) ? true : false;
```

(see [the generated codecs for example](https://github.com/real-logic/simple-binary-encoding/blob/d05b05477177d1656e0082196dccef0de22a1966/sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/TokenCodec.h#L195): all lines in that file where `true` occurs).

Could it be simpler:

``` c++
return m_actingVersion >= mdEntryTypeSinceVersion();
```

Is there a hidden meaning to this complication? If not, it is ready for a pull: vdidenko/simple-binary-encoding@94389b12920e632b17c5a5e70b4b0aa00ac061d3

**Comment by tmontgomery** [comment]
it should be simpler, yeah. Go ahead with a PR.
