### ISSUE TITLE
Allow skipping to the end of a message without reading all the groups and var data

### ISSUE THREAD

**Issue by mjpt777** [real-logic/simple-binary-encoding#392]
Add a method something like `Decoder.skipToEnd()`.

**Comment by tamboril** [comment]
I agree.  I've had to roll my own for scanning to a specific group as quickly as possible, and it's not easy due to the stateful nature of the parser and the private state variables, such as `index`.

**Comment by adkapur** [comment]
Oh nice this is the impetus for --> [https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/53](url)

**Comment by mjpt777** [comment]
Fixed with https://github.com/real-logic/simple-binary-encoding/pull/865
