### ISSUE TITLE
Variable Length Data Fields Within Repeating Group

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#393]
As per the SBE specification references listed below, it appears that variable length data fields could be included within a repeating group so just wanted to clarify if the real-logic SBE utility supports this?

Repeating group elements 
Repeating group entries are recursively organized in the same fashion as the root level: fixed-length fields, then nested repeating groups, and finally, variable-length data fields.

Group block length 
The blockLength part of a group dimension represents total space reserved for each group entry, not counting any nested repeating groups or variable-length fields. (Length of a variable-length Data field is given by its corresponding Length field.) Block length only represents message body fields; it does not include the length of the group dimension itself, which is a fixed size.

Repeating Groups 
A repeating group is a message structure that contains a variable number of entries. Each entry contains fields specified by a message schema. 
The order and data types of the fields are the same for each entry in a group. That is, the entries are homogeneous. Position of a given field within any entry is fixed, with the exception of variable-length fields.

**Comment by mjpt777** [comment]
Yes var data fields can be placed at the end of a repeating group. The examples show this working.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java#L141
