### ISSUE TITLE
Data fields in Composite Groups

### ISSUE THREAD

**Issue by romansmirnov** [real-logic/simple-binary-encoding#394]
I want to define a reusable `<composite>` to be reused in different message which contains a `<data ...>` field:

```xml
<composite name="peerInfo">
    <type name="port" primitiveType="uint8"/>
    <type name="state" primitiveType="uint8"/>
    <type name="generation" primitiveType="uint64"/>
    <type name="version" primitiveType="uint64"/>
    <data name="hostname" type="varDataEncoding"/>
</composite>
```

However, this does not seem to be possible (Schema does not allow `<data>` as child element of `<composite>`.

Is it possible to have variable length fields in reusable composite declarations?

Many thanks!

**Comment by mjpt777** [comment]
Data fields and repeating groups are not permitted in composite types. The standard is specified this way.
