### ISSUE TITLE
Nested Composites

### ISSUE THREAD

**Issue by mosig1** [real-logic/simple-binary-encoding#395]
Hello,

I have code with nested structs that I would like to translate to SBE XML. An example of the code is as follows:

```
struct Company
{
    int otherData;
    double moreData;
    struct Team Team1;
    struct Team Team2;
};

struct Team
{
    struct Employee Bob;
    struct Employee Alice;
};

struct Employee
{
    short id;
    int age;
};
```

In this example, the Company struct would be my <message> and the Employee and Team would be <composite>. I tried defining the nested structs as nested composites using the format shown below, but the inner composite does not get referenced or generated anywhere in the code.

```
<composite name="Team">
    <composite name="Employee">
        <type name="id" primitiveType="int16"/>
        <type name="age" primitiveType="int32"/>
    </composite>
</composite>
```

Is this possible? If not, what is the reasoning behind it not being possible?

Thanks

**Comment by mjpt777** [comment]
Yes it is possible to nest composites by value or ref. See this example.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml

**Comment by mosig1** [comment]
Thank you, @mjpt777 
I see the by reference in the example. How do you nest them by value?

**Comment by mosig1** [comment]
Also, the reason I asked is because I did not see the <ref> on the wiki.

**Comment by mosig1** [comment]
the `<ref>`
Sorry, it won't let me edit or delete.

**Comment by mjpt777** [comment]
What do you mean by "it won't let me edit or delete"?

**Comment by mjpt777** [comment]
Nested by value is shown in this testcase which is exercised on every build.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/test/resources/composite-elements-schema.xml
