### ISSUE TITLE
CPP User Guide - Not Able to Follow Code Snippet

### ISSUE THREAD

**Issue by 6193509** [real-logic/simple-binary-encoding#396]
https://github.com/real-logic/simple-binary-encoding/wiki/Cpp-User-Guide

I do not find actual sample code from which following snippet is mentioned in guide. May you please share it ?

![image](https://cloud.githubusercontent.com/assets/20138183/19154533/35551fac-8bdb-11e6-8074-1a209e4e8a6b.png)

Also not the function resetForDecode body ?

**Comment by mjpt777** [comment]
The wiki page had become out of date. I've updated it.
