### ISSUE TITLE
Second Repeating Group After First Repeating Group Containing Nested Repeating Group

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#399]
Just wanted to clarify an issue that we encountered where a second repeating group which follows behind a first repeating group containing a nested repeating group gets incorrectly referenced in the code as a nested repeating group of the first repeating group.

For example this works correctly: NoSecurityAltID repeating group followed by NoLegs repeating group containing NoLegSecurityAltID nested repeating group

>        <group name="NoSecurityAltID" id="454" description="Number of entries in AltID group." blockLength="27" sinceVersion="6" dimensionType="groupSize">
            <field name="SecurityAltID" id="455" type="StringLength26" description="Expanded instrument description." offset="0" semanticType="String"/>
            <field name="SecurityAltIDSource" id="456" type="CHAR" description="Identifies class or source of the SecurityAltID (455) value." offset="26" semanticType="String"/>
        </group>
        <group name="NoLegs" id="555" description="Number of legs (repeating groups)" blockLength="115" dimensionType="groupSize">
            <field name="LegBenchmarkCurveName" id="677" type="String5" description="Required for Floating Rate Leg. Floating rate reference." offset="0" semanticType="String"/>
            <field name="RateDescriptor" id="37504" type="String8" description="Rate Descriptor." offset="5" semanticType="String"/>
            <field name="PreviousFixingDate" id="37501" type="LocalMktDate" description="Issue date for one leg of a multi-issue trade. It is the previous fixing date on the float leg." offset="13" semanticType="LocalMktDate"/>
            <field name="LegPayFrequencey" id="37506" type="StringLen3" description="Payment frequency of fixed and floating rates expresses as a period." offset="15" semanticType="String"/>
            <field name="PreviousFixingRate" id="37502" type="Decimal64" description="The Rate set on the last reset date. It is the previous fixing rate." offset="18" semanticType="float"/>
            <field name="LegSymbol" id="600" type="StringLength50" description="For Eris Interest rate swaps values would be FIXED, FLOAT and for Spread, value would be underline instrument " offset="27" semanticType="String"/>
            <field name="LegRatioQty" id="623" type="Int32NULL" description="The ratio of quantity for this individual leg relative to the entire multi-leg instrument." offset="77" semanticType="int"/>
            <field name="LegSide" id="624" type="uInt8NULL" description="The side of this individual leg." offset="81" semanticType="int"/>
            <field name="LegCurrency" id="556" type="Currency" description="Currency associated with a particular Leg's quantity" offset="82" sinceVersion="4" semanticType="Currency"/>
            <field name="LegSecurityType" id="609" type="String8" description="Identifies the type of instrument." offset="85" semanticType="String"/>
            <field name="LegSecurityGroup" id="5795" type="String12" description="Leg equivalent of body tag 1151-SecurityGroup (i.e. leg 'product code')" offset="93" sinceVersion="5" semanticType="String"/>
            <field name="LegDateOffset" id="37503" type="Int8NULL" description="Float reset date offset, specified when LegType = FLOAT." offset="105" sinceVersion="5" semanticType="int"/>
            <field name="InterpolationFactor" id="37505" type="Decimal64" description="Multiplier that when applied on longer rate results in previous fixing rate." offset="106" sinceVersion="5" semanticType="float"/>
            <group name="NoLegSecurityAltID" id="604" description="Multileg instrument's individual security's NoSecurityAltID. " blockLength="27" dimensionType="groupSize">
                <field name="LegSecurityAltID" id="605" type="StringLength26" description="Multileg instrument's individual security's SecurityAltID. " offset="0" semanticType="String"/>
                <field name="LegSecurityAltIDSource" id="606" type="uInt8NULL" description="Multileg instrument's individual security's SecurityAltIDSource." offset="26" semanticType="int"/>
            </group>

But this does not:  NoLegs repeating group containing NoLegSecurityAltID nested repeating group followed by NoSecurityAltID repeating group

      <group name="NoLegs" id="555" description="Number of legs (repeating groups)" blockLength="115" dimensionType="groupSize">
            <field name="LegBenchmarkCurveName" id="677" type="String5" description="Required for Floating Rate Leg. Floating rate reference." offset="0" semanticType="String"/>
            <field name="RateDescriptor" id="37504" type="String8" description="Rate Descriptor." offset="5" semanticType="String"/>
            <field name="PreviousFixingDate" id="37501" type="LocalMktDate" description="Issue date for one leg of a multi-issue trade. It is the previous fixing date on the float leg." offset="13" semanticType="LocalMktDate"/>
            <field name="LegPayFrequencey" id="37506" type="StringLen3" description="Payment frequency of fixed and floating rates expresses as a period." offset="15" semanticType="String"/>
            <field name="PreviousFixingRate" id="37502" type="Decimal64" description="The Rate set on the last reset date. It is the previous fixing rate." offset="18" semanticType="float"/>
            <field name="LegSymbol" id="600" type="StringLength50" description="For Eris Interest rate swaps values would be FIXED, FLOAT and for Spread, value would be underline instrument " offset="27" semanticType="String"/>
            <field name="LegRatioQty" id="623" type="Int32NULL" description="The ratio of quantity for this individual leg relative to the entire multi-leg instrument." offset="77" semanticType="int"/>
            <field name="LegSide" id="624" type="uInt8NULL" description="The side of this individual leg." offset="81" semanticType="int"/>
            <field name="LegCurrency" id="556" type="Currency" description="Currency associated with a particular Leg's quantity" offset="82" sinceVersion="4" semanticType="Currency"/>
            <field name="LegSecurityType" id="609" type="String8" description="Identifies the type of instrument." offset="85" semanticType="String"/>
            <field name="LegSecurityGroup" id="5795" type="String12" description="Leg equivalent of body tag 1151-SecurityGroup (i.e. leg 'product code')" offset="93" sinceVersion="5" semanticType="String"/>
            <field name="LegDateOffset" id="37503" type="Int8NULL" description="Float reset date offset, specified when LegType = FLOAT." offset="105" sinceVersion="5" semanticType="int"/>
            <field name="InterpolationFactor" id="37505" type="Decimal64" description="Multiplier that when applied on longer rate results in previous fixing rate." offset="106" sinceVersion="5" semanticType="float"/>
            <group name="NoLegSecurityAltID" id="604" description="Multileg instrument's individual security's NoSecurityAltID. " blockLength="27" dimensionType="groupSize">
                <field name="LegSecurityAltID" id="605" type="StringLength26" description="Multileg instrument's individual security's SecurityAltID. " offset="0" semanticType="String"/>
                <field name="LegSecurityAltIDSource" id="606" type="uInt8NULL" description="Multileg instrument's individual security's SecurityAltIDSource." offset="26" semanticType="int"/>
            </group>
        </group>
        <group name="NoSecurityAltID" id="454" description="Number of entries in AltID group." blockLength="27" dimensionType="groupSize">
            <field name="SecurityAltID" id="455" type="StringLength26" description="Expanded instrument description." offset="0" semanticType="String"/>
            <field name="SecurityAltIDSource" id="456" type="CHAR" description="Identifies class or source of the SecurityAltID (455) value." offset="26" semanticType="String"/>
        </group>

**Comment by mjpt777** [comment]
What version of SBE are you using and can you expand on what you mean by by it does not work? For example, what fails?

**Comment by mjpt777** [comment]
Sorry I just realised what failure you are seeing now I have computer access and not just my phone. Can you please report what version you are using?

**Comment by adkapur** [comment]
yes you are correct, it seems that we are using a very old version, thanks
