### ISSUE TITLE
VS2015 cppbuild failure

### ISSUE THREAD

**Issue by pwong-legendarb** [real-logic/simple-binary-encoding#400]
Environment:
JDK 8u111, CMake 3.7.0-rc1, VS2015

The library and some executable are generated fine.
But I cannot fully build it using Debug build using below command.
$ mkdir -p cppbuild/Debug
$ cd cppbuild/Debug
$ cmake ../..
$ cmake --build . --clean-first

The issue happened in the generated header file MDUpdateAction.h under cppbuild\Debug\generated\uk_co_real_logic_sbe_benchmarks_fix

```
class MDUpdateAction
{
public:

    enum Value 
    {
        NEW = (std::uint8_t)0,
        CHANGE = (std::uint8_t)1,
        DELETE = (std::uint8_t)2,
        OVERLAY = (std::uint8_t)5,
        NULL_VALUE = (std::uint8_t)255
    };

    static MDUpdateAction::Value get(const std::uint8_t value)
    {
        switch (value)
        {
            case 0: return NEW;
            case 1: return CHANGE;
            case 2: return DELETE;
            case 5: return OVERLAY;
            case 255: return NULL_VALUE;
        }

        throw std::runtime_error("unknown value for enum MDUpdateAction [E103]");
    }
};
```

DELETE is keyword and it cannot build in VS2015. I tried to change it and build again but the script re-generate the file.

> "D:\Projects\CME\simple-binary-encoding-master\cppbuild\Release\ALL_BUILD.vcxproj" (default target) (1) ->
> "D:\Projects\CME\simple-binary-encoding-master\cppbuild\Release\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxp
> roj" (default target) (20) ->
> (ClCompile target) ->
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(48): error C2059: syntax error: '(' [D:\Projects\CME\simple-binary-encoding-master\cppbuild\Release\sbe-benchm
> arks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(48): error C3805: '(': unexpected token, expected either '}' or a ',' [D:\Projects\CME\simple-binary-encoding-
> master\cppbuild\Release\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(51): error C2143: syntax error: missing ')' before ';' [D:\Projects\CME\simple-binary-encoding-master\cppbuild
> \Release\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(51): error C2238: unexpected token(s) preceding ';' [D:\Projects\CME\simple-binary-encoding-master\cppbuild\Re
> lease\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(59): error C2440: 'return': cannot convert from 'long' to 'uk::co::real_logic::sbe::benchmarks::fix::MDUpdateA
> ction::Value' [D:\Projects\CME\simple-binary-encoding-master\cppbuild\Release\sbe-benchmarks\src\main\cpp\benchlet-sbe-
> md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(60): error C2065: 'OVERLAY': undeclared identifier [D:\Projects\CME\simple-binary-encoding-master\cppbuild\Rel
> ease\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]
>   d:\projects\cme\simple-binary-encoding-master\cppbuild\release\generated\uk_co_real_logic_sbe_benchmarks_fix\MDUpdate
> Action.h(61): error C2065: 'NULL_VALUE': undeclared identifier [D:\Projects\CME\simple-binary-encoding-master\cppbuild\
> Release\sbe-benchmarks\src\main\cpp\benchlet-sbe-md-runner.vcxproj]

**Comment by pwong-legendarb** [comment]
change sbe-benchmarks\src\main\resources\fix-message-samples.xml
row 117 DELETE to DELETEX
then everything build correctly

**Comment by mjpt777** [comment]
This can be addressed by using the `sbe.keyword.append.token` system property when generating codecs to append a token such as `_` to keywords such as delete.
