### ISSUE TITLE
presume old decoder won't be able to decode messages of new version?

### ISSUE THREAD

**Issue by derekxgl** [real-logic/simple-binary-encoding#407]
Even if I'm not interested in fields introduced in messages of new version, presume old decoder won't be able to decode the message? Given not interested in new fields, presume I do not need to change any of my own code apart from generating new decoder by using sbe tool? On the other side, new decoder should have no problem to decode old and new messages? Obviously old message won't have new fields.

**Comment by tmontgomery** [comment]
FIX/SBE has specific extension rules. Specifically, fields can only be added and not removed, etc.

**Comment by mjpt777** [comment]
A older version of a decoder can decode newer versions. The codec encodes block lengths in section block lengths to cope with this.
