### ISSUE TITLE
any drawback if just use compacted C struct to cast memory instead of using sbe tool generated decoder

### ISSUE THREAD

**Issue by derekxgl** [real-logic/simple-binary-encoding#408]
For reasonable simple & stable message schema, any drawback if I define my own compact C `struct` to cast memory instead of using sbe tool generated decoder? Even if schema gets updated (still assume schema is relatively simple), if only receive messages of newer version, I still feel my own hand coded `struct` is better (at least slightly faster). Any significant drawback I'm missing?

**Comment by tmontgomery** [comment]
No drawback, no. Extensible messages are easier, though. We have debated about providing structs from message schemas. And may do so at some point.
