### ISSUE TITLE
hang at '> Configuring > 0/5 projects > root project'

### ISSUE THREAD

**Issue by derekxgl** [real-logic/simple-binary-encoding#409]
On corporate linux box, modified gradlew script to have http, https, socks proxy options (I don't know which one gets used).  It works fine to download gradle-3.1-bin.zip, but hangs at '> Configuring > 0/5 projects > root project'. Eventually gave up with below error

```
FAILURE: Build failed with an exception.

* Where:
Build file '/*folders*/simple-binary-encoding-1.5.2/build.gradle' line: 18

* What went wrong:
Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '1.2.3']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.1/plugin/use/com.github.johnrengelman.shadow/1.2.3'.
   > Malformed reply from SOCKS server

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

The proxy options I added are 
`-Dhttp.proxyHost=Something -Dhttp.proxyPort=SomePort -Dhttps.proxyHost=Something -Dhttps.proxyPort=SomePort -DsocksProxyHost=Something -DsocksProxyPort=SomePort`

It would be great if all dependencies are bundled in the project.

**Comment by derekxgl** [comment]
The proxy options I added are 
-Dhttp.proxyHost=Something -Dhttp.proxyPort=SomePort -Dhttps.proxyHost=Something -Dhttps.proxyPort=SomePort -DsocksProxyHost=Something -DsocksProxyPort=SomePort

**Comment by mjpt777** [comment]
Gradle, Maven, Ivy, etc. all fetch dependencies as a standard development approach. If corporations want to block external access then an internal maven repository will have to be installed.
