### ISSUE TITLE
Schema <field> attributes incorrectly ignored?

### ISSUE THREAD

**Issue by da4089** [real-logic/simple-binary-encoding#410]
Section 2.3 lists a set of schema attributes for the `field` element, including `minValue` and `maxValue`.

Section 2.3.1 states that these attributes also apply to the specification of an encoding, and that fields using that encoding inherit the attributes.  I assume that "encoding" translates to a `type` element in a schema.

However, if I define a schema with a field including the `minValue` and `maxValue` attributes, _sbe-tool_ does not apply them to the generated stubs.  If the attributes are defined on a type, and the field is defined using that type, then the attributes are correctly applied to the generated stubs.

My reading of 2.3, and reinforced by 2.3.1, makes me think you should be able to specify `minValue` and `maxValue` directly on a `field` element?

Example schema:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<messageSchema package="issue1"
               id="1"
               semanticVersion="5.2"
               description="Field attributes issue test"
               byteOrder="littleEndian">
    <types>
      <composite name="messageHeader"
                 description="Message identifiers and length of message root">
            <type name="blockLength" primitiveType="uint16"/>
            <type name="templateId" primitiveType="uint16"/>
            <type name="schemaId" primitiveType="uint16"/>
            <type name="version" primitiveType="uint16"/>
        </composite>

        <type name="Symbol" description="Symbol" primitiveType="char"
              minValue="a" maxValue="z"/>
    </types>

    <message name="TestMessage1" id="1" description="Test Message 1">
      <field name="FieldName1" id="2" type="Symbol" />
    </message>

    <message name="TestMessage2" id="3" description="Test Message 1">
      <field name="FieldName2" id="4" type="char" minValue="a" maxValue="z" />
    </message>
</messageSchema>

```

Generated stubs for `FieldName1` have `minValue`=97 and `maxValue`=122, while `FieldName2` has `minValue`=32 and `maxValue`=126 (defaults for `char`).

**Comment by mjpt777** [comment]
The XSD for field does not define the `minValue` or `maxValue` attributes, these are only on `encodedDataType`. If you apply these attributes to field then schema validation fails.

Probably best to take this up with the people who wrote the specification and see if their documents are consistent with the XSD.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

**Comment by da4089** [comment]
Thanks Martin -- I'll follow up with the FIX folks.
Is there someone there I should reach out to directly (rather than just creating a GitHub issue)?

**Comment by mjpt777** [comment]
GitHub Issue is probably the best approach. They are likely to answer and others can benefit.

**Comment by da4089** [comment]
Spec isssue at https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/35 for reference.
