### ISSUE TITLE
MessageHeader info lost.

### ISSUE THREAD

**Issue by GazitGu** [real-logic/simple-binary-encoding#412]
Hi Martin Thompson,

Thanks for you great work on SBE.

We got an issue when using SBE in a trading system:

issue: after encode, we missed the header info (say fix-message-sample.xml), the first 8 byte are 0, this happens ONLY when ByteBuffer is direct and at around 7000 times, for none direct ByteBuffer we didn't notice the issue.

below is the code to reproduce the issue (the output byte array with 0 at the first 8 bytes), the message are generated from fix-message-sample.xml.

```java
/**
 * 
 */
package test;

import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.concurrent.atomic.AtomicLong;

import org.agrona.concurrent.UnsafeBuffer;

import uk.co.real_logic.sbe.benchmarks.fix.MessageHeaderEncoder;
import uk.co.real_logic.sbe.benchmarks.fix.NewOrderEncoder;
import uk.co.real_logic.sbe.benchmarks.fix.OrdType;
import uk.co.real_logic.sbe.benchmarks.fix.Side;
import uk.co.real_logic.sbe.benchmarks.fix.TimeInForce;


/**
 * @author Administrator
 *
 */
public class SendOrder {

  private AtomicLong orderIdSeq = new AtomicLong(0);
  private int i = 0;

  public long createOrder(String symbol, long price, int volume, String account, Side side) {
    long orderId = orderIdSeq.incrementAndGet();
    System.out
        .println(String.format("createOrder  instrument = %s, price = %s, volume= %s, orderId = %s",
            symbol, price, volume, orderId));

    final MessageHeaderEncoder headerEncoder = new MessageHeaderEncoder();
    ByteBuffer byteBuffer = ByteBuffer.allocateDirect(1024);
    final UnsafeBuffer directBuffer = new UnsafeBuffer(byteBuffer);
    int offset = 0;
    int bufferOffset = 0;
    int encodingLength = 0;
    final NewOrderEncoder orderEncoder = new NewOrderEncoder();
    headerEncoder.wrap(directBuffer, bufferOffset).blockLength(orderEncoder.sbeBlockLength())
        .templateId(orderEncoder.sbeTemplateId()).schemaId(orderEncoder.sbeSchemaId())
        .version(orderEncoder.sbeSchemaVersion());
    bufferOffset += headerEncoder.encodedLength();
    encodingLength += headerEncoder.encodedLength();
    byte[] clOrdIDBytes = new byte[NewOrderEncoder.clOrdIDLength()];
    byte[] clOrdId = "001".getBytes();
    System.arraycopy(clOrdId, 0, clOrdIDBytes, 0, clOrdId.length);
    orderEncoder.wrap(directBuffer, bufferOffset).putClOrdID(clOrdIDBytes, 0)
        .ordType(OrdType.LIMIT_ORDER).side(side).timeInForce(TimeInForce.DAY)
        .transactTime(System.currentTimeMillis() * 1000000);
    orderEncoder.orderQty().mantissa(volume);
    orderEncoder.price().mantissa(price);
    byte[] accountBytes = new byte[NewOrderEncoder.accountLength()];
    byte[] src = account.getBytes();
    System.arraycopy(src, 0, accountBytes, 0, src.length);
    orderEncoder.putAccount(accountBytes, offset);

    byte[] symbolBytes = new byte[NewOrderEncoder.symbolLength()];
    byte[] symbolSrc = symbol.getBytes();
    System.arraycopy(symbolSrc, 0, symbolBytes, 0, symbolSrc.length);
    encodingLength += orderEncoder.encodedLength();
    byteBuffer.limit(encodingLength);

    System.out.println("The used buffer " + (++i) + ": " + getData(byteBuffer, encodingLength));
    return orderId;
  }

  public long bid(String symbol, long price, int volume, String account) {
    return createOrder(symbol, price, volume, account, Side.BUY);
  }

  public long ask(String symbol, long price, int volume, String account) {
    return createOrder(symbol, price, volume, account, Side.SELL);
  }

  private String getData(ByteBuffer byteBuffer, int len) {
    byte[] data = new byte[len];
    byteBuffer.mark();
    byteBuffer.get(data);
    byteBuffer.reset();
    return Arrays.toString(data);
  }

  /**
   * @param args
   */
  public static void main(String[] args) {
    SendOrder sender = new SendOrder();
    String symbol = "510050";
    long bidPx = 2329;
    long askPx = 2330;
    int volume = 100;
    String account = "00000000001";
    while (true) {
      sender.bid(symbol, bidPx, volume, account);
      sender.ask(symbol, askPx, volume, account);
    }
  }
}
```

Thanks for your time.

Gazit

**Comment by GazitGu** [comment]
The test is under version 1.5.3 and 1.5.2

**Comment by mjpt777** [comment]
Can I ask why you keep allocating `byte[]`s and direct `ByteBuffer`s on each iteration? Allocating direct ByteBuffers is very expensive and puts significant pressure on the garbage collector doing finalization. Why not allocated one up front and reuse it?

**Comment by mjpt777** [comment]
I've not been able to reproduce this on Windows with the latest 1.8.0_112. What Java version are you using?

It might be related to this bug. https://bugs.openjdk.java.net/browse/JDK-8087134

**Comment by GazitGu** [comment]
Thanks for you response.

we allocate some the bytebuffers in a pool and reuse it, to demonstrate the issue i create bytebuffer directly here, **when you change the bytebuffer allocation to allocateDirect** and at around 7000 times you will find the message start with 8 zero.

i am using jdk 1.8.0_91.

i will try to use jdk 1.8.0_112 to test it again.

Thanks.

**Comment by GazitGu** [comment]
the latest jdk version have the same issue, we test it under window 10.

below is the output log shows the difference:
The used buffer 5538: [-100, 0, 68, 0, 1, 0, 1, 0, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49, 0, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 50, 26, 9, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 48, -64, -38, -95, 7, -89, 105, -121, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
The used buffer 5539: [0, 0, 0, 0, 0, 0, 0, 0, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49, 0, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 50, 25, 9, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 48, -128, -121, -81, 20, -89, 105, -121, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by mjpt777** [comment]
Thanks for following up. A few thing you could do to help narrow this down:

1. Simplify the example to just write the header and not the order to see if it still happens.
1. Output the address of the buffer when it happens. `long address = ((sun.nio.ch.DirectBuffer)buffer).address();`
1. Try with `-server` and `-Xint` startup flags to see if it is possibly a C2 bug.

**Comment by GazitGu** [comment]
Tried all the options, only after added -Xint the issue gone.

Thanks for you suggestions.

**Comment by mjpt777** [comment]
When it failed, what was the address?

**Comment by GazitGu** [comment]
[-100, 0, 68, 0, 1, 0, 1, 0]
387368656
[0, 0, 0, 0, 0, 0, 0, 0]
**387371776**

**Comment by mjpt777** [comment]
Thanks. Can you post a minimal code sample that creates the issues with only the header being written?

**Comment by GazitGu** [comment]
Yes.

below is the code sample only set message header and stop when error occurs (first byte was 0, it should be -100 for order message).
/**
 * 
 */
package test;

import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.concurrent.atomic.AtomicLong;

import org.agrona.concurrent.UnsafeBuffer;

import uk.co.real_logic.sbe.benchmarks.fix.MessageHeaderEncoder;
import uk.co.real_logic.sbe.benchmarks.fix.NewOrderEncoder;
import uk.co.real_logic.sbe.benchmarks.fix.OrdType;
import uk.co.real_logic.sbe.benchmarks.fix.Side;
import uk.co.real_logic.sbe.benchmarks.fix.TimeInForce;


/**
 * @author Administrator
 *
 */
public class SendOrder {


  public long createOrder(String symbol, long price, int volume, String account, Side side) {

    final MessageHeaderEncoder headerEncoder = new MessageHeaderEncoder();
    ByteBuffer byteBuffer = ByteBuffer.allocateDirect(1024);
    final UnsafeBuffer directBuffer = new UnsafeBuffer(byteBuffer);
    int bufferOffset = 0;
    int encodingLength = 0;
    final NewOrderEncoder orderEncoder = new NewOrderEncoder();
    headerEncoder.wrap(directBuffer, bufferOffset).blockLength(orderEncoder.sbeBlockLength())
        .templateId(orderEncoder.sbeTemplateId()).schemaId(orderEncoder.sbeSchemaId())
        .version(orderEncoder.sbeSchemaVersion());
    bufferOffset += headerEncoder.encodedLength();
    encodingLength += headerEncoder.encodedLength();
    encodingLength += orderEncoder.encodedLength();
    byteBuffer.limit(encodingLength);

    getData(byteBuffer, encodingLength);
    return 0;
  }

  public long bid(String symbol, long price, int volume, String account) {
    return createOrder(symbol, price, volume, account, Side.BUY);
  }

  public long ask(String symbol, long price, int volume, String account) {
    return createOrder(symbol, price, volume, account, Side.SELL);
  }

  private String getData(ByteBuffer byteBuffer, int len) {
    byte[] data = new byte[len];
    byteBuffer.mark();
    byteBuffer.get(data);
    byteBuffer.reset();
    if(data[0]==(byte)0){ // the first byte should be -100 for order message
      long address = ((sun.nio.ch.DirectBuffer)byteBuffer).address();
      System.out.println(Arrays.toString(data));
      System.out.println(""+address);
      System.exit(-1);
    }
    return null;
  }

  /**
   * @param args
   */
  public static void main(String[] args) {
    SendOrder sender = new SendOrder();
    String symbol = "510050";
    long bidPx = 2329;
    long askPx = 2330;
    int volume = 100;
    String account = "00000000001";
    while (true) {
      sender.bid(symbol, bidPx, volume, account);
      sender.ask(symbol, askPx, volume, account);
    }
  }
}

Thanks for keep investigating on this issue.

**Comment by mjpt777** [comment]
I can recreate the issue on Linux with this simplified version of the code. 

```java
import org.agrona.concurrent.UnsafeBuffer;
import uk.co.real_logic.sbe.benchmarks.fix.MessageHeaderEncoder;
import uk.co.real_logic.sbe.benchmarks.fix.NewOrderEncoder;

import java.nio.ByteBuffer;

public class TestOrder
{
    public static long i = 0;

    public long createHeader()
    {
        ByteBuffer byteBuffer = ByteBuffer.allocateDirect(1024);
        final UnsafeBuffer directBuffer = new UnsafeBuffer(byteBuffer);

        final MessageHeaderEncoder headerEncoder = new MessageHeaderEncoder();
        final NewOrderEncoder orderEncoder = new NewOrderEncoder(); // comment this line and it does not fail

        headerEncoder.wrap(directBuffer, 0)
            .blockLength(158)
            .templateId(68)
            .schemaId(1)
            .version(1);

        byteBuffer.limit(headerEncoder.encodedLength());

        checkData(byteBuffer);

        return 0;
    }

    public String checkData(final ByteBuffer byteBuffer)
    {
        i++;

        if (byteBuffer.get() == (byte)0)
        {
            long address = ((sun.nio.ch.DirectBuffer)byteBuffer).address();
            System.out.println("address=" + address + " address%64=" + (address % 64) + " i=" + i);
            System.exit(-1);
        }

        return null;
    }

    public static void main(final String[] args)
    {
        TestOrder sender = new TestOrder();

        while (true)
        {
            sender.createHeader();
        }
    }
}
```

**Comment by GazitGu** [comment]
yes, that works, but still not very clear how come JVM cares the two independent code lines who create first.

**Comment by mjpt777** [comment]
I think this is a JVM bug. I'll try and investigate more. Best workaround for now is to hold onto the direct ByteBuffer rather than recreating all the time which is horrendous in performance anyway.

**Comment by GazitGu** [comment]
What we were doing now is creating a bytebuffer pool and borrow it each time we need one.

Thanks for you time.
