### ISSUE TITLE
composite enum and ref to enum sinceVersion are always 0

### ISSUE THREAD

**Issue by billsegall** [real-logic/simple-binary-encoding#415]
Similar to issue #414 if I modify sbe-tool/src/test/resources/example-composite.xml thusly:
```+++ b/sbe-tool/src/test/resources/example-composite.xml
@@ -2,7 +2,7 @@
 <sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe"
                    package="composite"
                    id="1"
-                   version="0"
+                   version="4"
                    semanticVersion="5.2"
                    description="Example Simple4"
                    byteOrder="littleEndian">
@@ -23,12 +23,16 @@
     </enum>
 
     <composite name="point">
-      <type name="name" primitiveType="char" length="5" />
-      <type name="d" primitiveType="double" />
-      <type name="i" primitiveType="int32" />
-      <type name="u" primitiveType="uint8" length="2" />
-      <ref name="truthval1" type="booleanEnum"/>
-      <ref name="truthval2" type="booleanEnum"/>
+      <type name="name" primitiveType="char" length="5" sinceVersion="1"/>
+      <type name="d" primitiveType="double"  sinceVersion="1"/>
+      <type name="i" primitiveType="int32"  sinceVersion="1"/>
+      <type name="u" primitiveType="uint8" length="2"  sinceVersion="1"/>
+      <ref name="truthval1" type="booleanEnum" sinceVersion="2"/>
+      <ref name="truthval2" type="booleanEnum" sinceVersion="3"/>
+      <enum name="ENUM" description="enum as uint8" encodingType="uint8" semanticType="int" sinceVersion="1">
+            <validValue name="Value1" sinceVersion="1">1</validValue>
+            <validValue name="Value10" sinceVersion="2">10</validValue>
+        </enum>```

then when traversing the IR the version is always zero for the <ref> and <enum> elements but is correctly set for the primitiveTypes.

**Comment by mjpt777** [comment]
This raises some interesting questions. You know that a composite cannot be extended according to the specification? So all types in one must be less than or equal to its version. Effectively only the version of the composite itself matters. I'd consider the `sinceVersion` attributes on types in a composite  to be for documentation only.

When it comes to `sinceVersion` on a `ref` then I've no idea what the actual semantics of this would mean. Why it is allowed by the XSD escapes me.  Maybe @donmendelson can explain?

**Comment by mjpt777** [comment]
A reason I can see to extend a composite is if comes at the end of a block, though this could be error prone to enforce. Composites can be useful from a code reuse perspective when the same block is used across multiple message templates.

**Comment by mjpt777** [comment]
I've been looking at the implications of using `sinceVersion` within composite decoders and have concluded this is very error prone and against the spec. I think having this attributed supported within composite for the XSD is a bug given the spec. It has been a good reason to revisit the Java stubs which I've got them to ignore the sinceVersion within composites.

**Comment by mjpt777** [comment]
Closing this for now unless the specification wants to address this more specifically.
