### ISSUE TITLE
Crash on Sparc CPU

### ISSUE THREAD

**Issue by ThiConcept** [real-logic/simple-binary-encoding#416]
Hi Support,

I have implemented an adaptor against CME's MDP3 Api.
The implementation is using codecs generated by SBE library.

I am running it on a SPARC Cpu. This Cpu doesn't support unaligned memory access whereas Intel Cpu does. As a result, some native memory accesses made by the sbe library are unaligned and make the process crash.

- Are you aware of such an issue ?
- Do you know if there is a sbe library (java) that can support this kind of architecture or any workaround ?

Thanks in advance,

Thibaut

**Comment by mjpt777** [comment]
Yes we are aware of the issue. If the `offset` attribute is used on each field then they can be aligned.

Maybe we should change the samples to be aligned to demonstrate this. I'll see how much work that would be.

**Comment by mjpt777** [comment]
BTW the CME should have made a spec that has all the fields aligned by using the offset attribute. If they have not then you should raise an issue with them.

**Comment by ThiConcept** [comment]
Hi,

Thanks for your answer.
I have to check on my side, and with CME.
I will revert soon. I hope I can close the issue.

Thanks 
Regards
