### ISSUE TITLE
Reinstating optional support for C++98?

### ISSUE THREAD

**Issue by da4089** [real-logic/simple-binary-encoding#417]
I've got an application using an older version of sbe-tool to generate a C++98 API, and I'd really like to upgrade to current (1.5.x), but I can't update my customer API to C++11.

I've seen #287 and #315, but I'm not across the logic that led to the dropping of C++98.

Would there be any interest in a patch reinstating optional support for generating C++98 compatible stubs?

**Comment by prashn** [comment]
I am interested in C++98 API as well. @da4089: Which version are you using? Is 1.1.7-RC2 the last version with C++98 support?

**Comment by da4089** [comment]
We're using 1.1.7-RC2 also.

I was wondering about a flag for the C++ generator to optionally produce C++98-compatible code.

**Comment by mjpt777** [comment]
If someone is willing to send a PR for C++ 98 then we can consider it. We don't have time to create and maintain this ourselves.

**Comment by tmontgomery** [comment]
I believe this is best handled by using the TargetCodeGenerator that was added in 1.5.6. This allows new code generators to be loaded without being part of the repo. As we don't have the time to create and maintain this ourselves, it should be separate from this repo.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/test/java/uk/co/real_logic/sbe/TargetCodeGeneratorTest.java

**Comment by da4089** [comment]
@tmontgomery, is that the approach that should be taken for additional languages also?  For example, a revived C# code generator, or Python, or ... etc?

How do you anticipate these generators being distributed to end-users?

**Comment by tmontgomery** [comment]
@da4089 yes, could be used by any language.

The way it works is to set the target.language to a classname. So, just put the generator in a jar and add it to the SbeTool classpath.
