### ISSUE TITLE
[Java] Generated encoder does not initialize actingVersion

### ISSUE THREAD

**Issue by donmendelson** [real-logic/simple-binary-encoding#418]
Generated decoders properly allow setting actingVersion as a parameter to wrap() since the encoded version is passed on the wire in the message header. However, generated encoders have conditional code comparing actingVersion but never initialize it, so it is always treated as zero. See generated example below. The simple fix would be to initialize `this.actingVersion = SCHEMA_VERSION;` 

However, there are two possible choices, depending on intent.

1. If it is intended that encoders should be capable of encoding prior versions, then it could take actingVersion as a parameter as decoders do. But it would also need a way to encode the correct blockLength for each prior version.
2. If encoders should only be capable of encoding the current version, then field actingVersion should be removed along with any conditions that depend on it. 

This example fails because actingVersion is always zero.
```java
    public QtyEncodingEncoder minQty()
    {
        if (actingVersion < 1)
        {
            return null;
        }

        minQty.wrap(buffer, offset + 54);
        return minQty;
    }
```

**Comment by mjpt777** [comment]
What version have you been using for this? Is this C++ or Java?

The example you give is a decoding, i.e. it is reading, yet I think you are asking about encoding. How did you create this, can you prove an example?

**Comment by donmendelson** [comment]
Java generated with version 1.5.4.

The schema is just slightly modified from example in SBE spec to test versioning:
https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-DRAFT_STANDARD/resources/Examples.xml

The code above is where an encoder is returned for Qty composite type for added minQty field in version 1 of the schema.

```xml
		<composite name="qtyEncoding">
			<type name="mantissa" primitiveType="int32" />
			<type name="exponent" presence="constant" primitiveType="int8">0</type>
		</composite>
```

**Comment by mjpt777** [comment]
Thanks @donmendelson. Some of the extension code was not handled properly with the changes in RC4. I've now cleaned this up and pushed a change. I found a couple of other bugs relating to repeating groups and bit sets. Let me know if it now works for you.

I don't think it makes sense for an encoder to support encoding previous versions. Added fields should be optional or use a previous encoder.
