### ISSUE TITLE
IR support for deprecated attribute

### ISSUE THREAD

**Issue by billsegall** [real-logic/simple-binary-encoding#420]
It seems the <type>attribute "deprecated" was a later addition to the spec and is not yet available in the IR. At some point it should be added for completeness. It is described in the current xsd.

**Comment by tmontgomery** [comment]
I vaguely remember discussing this. The conclusion is that this doesn't change the layout, etc. It is simply informational. Do you mean adding it so the user can call a method like "isDeprecated" to query it?

**Comment by mjpt777** [comment]
I was simply thinking the IR is a good place to capture this and that it could optionally be used generating codecs.

**Comment by billsegall** [comment]
I was wondering if it was desirable to encode/decode a NullValue for a deprecated element. The spec is unclear as to what one should do with deprecated elements but it does provide a version number for when it was deprecated so perhaps that implies a deprecatedInVersion() (with 0 being not deprecated?)

It's available on many elements but is perhaps conceivably useful on messages where you might choose not to send a certain message type to sufficiently new clients where it is known to be deprecated. The spec doesn't make assertions on how it should be used other than suggesting it is for transitioning clients.

**Comment by tmontgomery** [comment]
I think the IR can capture it, but the real value of the deprecation would be in maintaining schemas and parsers for them and in comparing one version of a schema to another version. i.e. not in the generation of codecs or on-the-fly.

**Comment by mjpt777** [comment]
I can see the value in deprecating a message template but I don't see a good reason for deprecated a field if the template is still valid. Seems like an odd choice in the standard. Any idea for when this would be valid?

**Comment by donmendelson** [comment]
Agreed that the spec could use a more detailed explanation of `deprecated` attribute. . It was inspired by Javadoc tag of the same name, which indicates that a better alternative exists. The element has not been removed but it may be removed in the future. Schema extension supports new fields while deprecation supports gradual phase-out of a message, field or code value

FIX has a number of field and code values that have been marked as deprecated. See Appendix 6-E of FIX 5.0 SP2 for a list. That document states that a feature may be phased out due to a shortcoming of the original design or to new business requirements.

**Comment by mjpt777** [comment]
@donmendelson What does phased out in respect to a field mean with SBE? That would break backwards compatibility as fields can only be added. Deprecated is saying that in the future we make take this away. Applying this to a message template makes sense but not for a field. Can you give an example of phasing out a field and how it would work for existing applications?

**Comment by donmendelson** [comment]
An example from FIX: field Benchmark was added in FIX 4.2, deprecated in FIX 4.3 and replaced with three new fields, and was removed in FIX 4.4. The FIX Repository keeps the full pedigree with added/changed/deprecated/removed attributes. In SBE we have `sinceVersion` for added, and `deprecated`.

I agree that the only way to remove a field in SBE is to issue a new template, but we can still signal obsolescence .

My understanding of other protocols such as ISO 20022 is that they also have deprecated message components. The world changes, often beyond the control of message designers.

**Comment by tmontgomery** [comment]
The real value is mostly in comparing versions and multiple message templates, it would seem. Mostly the tooling around schema maintenance could use the tag.
