### ISSUE TITLE
Is there a way to add automatic padding in variable-length field to ensure alignment ?

### ISSUE THREAD

**Issue by m-anthony** [real-logic/simple-binary-encoding#428]
The use case for this can either be :
- several variable-length field in a message, with a multi-bytes length description.
- a variable-length field inside a repeating group.

If I understand correctly the order of the field on the wire with SBE codec, this can lead to unaligned accesses with some data length. Is there any way to prevent that by declaring some value that the total variable-length data field length (length description + data) should be a multiple of, and let the SBE codecs handle some padding if necessary ?

**Comment by tmontgomery** [comment]
Currently, no. The spec doesn't really allow this currently. Or at least to my knowledge.

A way to do it from the application is to pad the variable length data manually. So that you don't need to worry about the encoding, you can include the padding count in bytes as the last byte.

**Comment by m-anthony** [comment]
Hi Todd,

Thank you for the application level trick with the padding count.

Is there any chance that a PR for this feature can be accepted so it can be handled directly by SBE ?
If the answer is positive, do you have any suggestion about the name of the attribute to add on the <data> element ? I have some trouble to find a really representative name for this feature

**Comment by mjpt777** [comment]
It may be worth considering multiple approaches to the requirement and then making a proposal to the FIX community for future specifications.

I think the best short term approach would be to have direct buffer implementation that reads/writes values byte by byte and then makes the required type out of the assembled bytes. This would also allow for packed structures that don't have natural alignment plus deal with endianess. This could be an alternative to the `UnsafeBuffer`.
