### ISSUE TITLE
nullValue only set in IR's encoding if set in type not in field and value is long not unsigned

### ISSUE THREAD

**Issue by billsegall** [real-logic/simple-binary-encoding#429]
For this snippet of an sbe-schema
```
   <types>
      <type name="uint64nv" presence="optional" nullValue="18446744073709551615"   description="Large Null Value test" primitiveType="uint64"/>
   </types>
    <sbe:message name="nullvaluetest" id="1" semanticType="issue" description="nullvalue test">
        <field name="U64nv"   id="10"  type="uint64nv"/>
        <field name="U64"     id="20"  type="uint64" presence="optional" nullValue="18446744073709551615"/>
```

When processing the IR I see:

uint64nv has token.encoding().nullValue == "-1"
uint64 has     token.encoding().nullValue == null

I think they should both be "18446744073709551615" which is -1 if the value was signed.

**Comment by mjpt777** [comment]
Java does not support unsigned types, with the exception of char, and we have no larger size to contain this.

Also do you have schema validation enabled? `nullValue` is not supported on a field according to the spec which I think is an omission.

**Comment by billsegall** [comment]
I see the difficulty without an unsigned type and so for golang which won't allow a compile time conversion of uint64(-1) I've instead used Java8's Long.toUnsignedString(Long.parseLong(value))

Turning on schema validation I now see:
[Error] :30:140: cvc-complex-type.3.2.2: Attribute 'nullValue' is not allowed to appear in element 'field'.
although section 2.3 "Common field schema attributes" says they are legal. I will seek clarification on that @ fixprotocol.io and close this issue.

Thanks.

**Comment by billsegall** [comment]
It's already an open issue:
https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/35
