### ISSUE TITLE
Semantic type member access is private

### ISSUE THREAD

**Issue by dynamok** [real-logic/simple-binary-encoding#432]
Is there any reason why access to the semantic type is private for OTF decoding?  Could be changed to public?

**Comment by dynamok** [comment]
In addition, the same applies to field description and null_value:

That is, it looks that we have to override field access to these fields:

m_description
m_semanticType
m_nullValue

**Comment by mjpt777** [comment]
The missing accessors have been added. Does this work for you now?

**Comment by dynamok** [comment]
I will try when we the get the latest version. What version would have this fix?

Thanks,
Dimitry

**Comment by mjpt777** [comment]
The C++ is built from source for the OTF so you can get it now. The next SbeTool release will be 1.5.7.

**Comment by dynamok** [comment]
Thanks, we will try it out.

Dimitry

**Comment by mjpt777** [comment]
Closing as I assume it worked but got not feedback.
