### ISSUE TITLE
To decode a repeating group more than once, resetting of the limit is needed

### ISSUE THREAD

**Issue by dfhub** [real-logic/simple-binary-encoding#440]
According to the example in the wiki, to decode a repeating group we can use a foreach loop:

```
for (CarDecoder.PerformanceFiguresDecoder performanceFigures : car.performanceFigures())
{
    sb.append("\ncar.performanceFigures.octaneRating=").append(performanceFigures.octaneRating());

    for (AccelerationDecoder acceleration : performanceFigures.acceleration())
    {
        sb.append("\ncar.performanceFigures.acceleration.mph=").append(acceleration.mph());
        sb.append("\ncar.performanceFigures.acceleration.seconds=").append(acceleration.seconds());
    }
}
```

Looping using the foreach moves the limit of the decoder (i.e. the car object in this case).
If, for some reason, I need to loop through the repeating group more than once, it will not work.
In order to workaround this, I would have to (as done in the generated toString() method):
1) get the original limit before start processing the repeating group (i.e. originalLimit = car.limit())
2) set the limit to its original value after repeating group processing is ended (i.e. car.limit(originalLimit)

Is it the expected behavior?
Is there any reason why the limit cannot be reset when calling the car.performanceFigures() method?

Thank you

**Comment by mjpt777** [comment]
You could use the limit to reset before to iterating if you are careful. You cannot rerun a single iteration of the loop as this would throw off the loop index.
