### ISSUE TITLE
Can not gradlew.bat

### ISSUE THREAD

**Issue by shilf** [real-logic/simple-binary-encoding#442]
I double click on gradlew.bat. Always stop on >Building 14% > :sbe-tool:compileJava > 111 KB/259 KB downloaded.Why ? I am in shanghai china

**Comment by mjpt777** [comment]
This is the Gradle build system. Maven also downloads dependencies. I wish the community made more efficient build systems but it is the world we have to live with.

Please take this issue up with [Gradle](https://gradle.org/) as the question is not appropriate here.
