### ISSUE TITLE
Problem with running SBETool

### ISSUE THREAD

**Issue by KamilHawk123** [real-logic/simple-binary-encoding#445]
I try to compile the SbeTool.java in the command prompt but i get this error.Anybody run into problem like that.here is the link of the screen shoot 
https://www.screencast.com/t/Hs1cKH5zJ
I am trying to run the simple binary encoding under VS2015 but i first need to get that tool working for me.If you could post a compiled recent sbetool i would appreciate it

**Comment by mjpt777** [comment]
You build by running the gradle on the command line. This is covered on the home page read me.

```> gradlew```
