### ISSUE TITLE
Multiple IR Files

### ISSUE THREAD

**Issue by ccge** [real-logic/simple-binary-encoding#446]
Is there a way to load multiple IR files with the C++ OTF Decoder? The IrDecoder seems to only be able to take 1 IR file at a time and there is no more IrCollection.

**Comment by tmontgomery** [comment]
The Java and C++ OTF decoders both work the same way. The IrDecoder is for a single IR file.

However, building an IR collection (that uses multiple IR files) is quite straight forward. Load each into new IrDecoders and then have a combined `IrDecoder::message` method.

**Comment by ccge** [comment]
I have built a sbe_decoder class outside of IrDecoder that contains a struct that holds all the IrDecoder's and has a decode method to decode raw SBE messages.  Something like this:
```
class sbe_decoder
{
private:
  struct decoder_components
  {
      IrDecoder ir_decoder;
      std::shared_ptr<std::vector<Token>> header_tokens;
      std::shared_ptr<std::vector<Token>> message_tokens;
      decoder_components(){};
  };
public:
  explicit sbe_decoder( const std::string& ir_file_name );
  size_t decode( const char* sbe_packet, unsigned int sbe_packet_length, copy_free_thing& sbe_msg );
}
```
Some other member date structure can hold decoder_components. Lets call it ir_collection.

An instance of sbe_decoder constructs with a string of wildcards, like example*.sbeir. But, when it comes time call decode(resembles the main() here: https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/cpp/OtfExample.cpp) you need to know what element to access in ir_collection. All you have though is a raw SBE message.

I don't see a way to get the correct element of ir_collection because when you constructed sbe_decoder all you had was the IR files and not the raw sbe message.

I also don't want to modify IrDecoder.h because you will not be able to seamlessly start using a new version of OTF Decoder.

**Comment by tmontgomery** [comment]
SBE usage will typically need to decode the header first that is outside the raw SBE message. This is shown in the example via the `HeaderDecoder`. In the example, the `templateId` field and `actingVersion` field are used to determine which message in the IrDecoder to grab the tokens for.

This technique can be expanded for more templateIds and versions for a larger collection in a number of ways. Such as always picking unique templateIds for each message type even across IR files.

This is one of the challenges of using SBE. How to pick template Ids and versions, etc. The implementation does not dictate a solution because the specification does not dictate a solution.

**Comment by ccge** [comment]
I am not trying to pick templateIds and actingVersions. The IRs I am using are already set. I do not create an instance of OtfHeaderDecoder until I go to decode a raw SBE message either.

I am trying to fill a "ir_collection" data structure of various IR files in my sbe_decoder constructor. That "ir_collection" would be filled with the decoder_components struct above.

headerDecoder in the example can only be used correctly if you have a raw SBE message. But, in the case of any class utilizing the OTF Decoder, there doesn't seem to be any good way to fill a "ir_collection" on that class' constructor. This is because on that class' constructor, you will not pass a random raw SBE message.

An instance of OtfHeaderDecoder (headerDecoder) should only be called when you are trying to decode the whole message.

**Comment by tmontgomery** [comment]
Managing messageHeader definitions across IR files is the responsibility of your code. Not SBE. This does impact picking templateIds and actingVersions. My suggestion would be to consider how to think of this as a complete whole approach. How can you pick the right messageHeader if you can't pick the correct templateId? (for example). In other words, before you get to the "raw SBE message", you need to know what IR to use. That means which IR file and tokens within that file. The messageHeader is a part of the spec. But it doesn't have to be used. A "raw SBE message" is exactly that. Raw. It doesn't mandate a messageHeader be present (if I recall correctly).

Here are some options:
- Use the same messageHeader definition across schemas and prepend a messageHeader to the raw SBE message. Then it doesn't matter which IR file. But this requires unique templateIds across the files for each message type.
- Use another specific raw SBE message type as a header before each raw SBE message. In other words, each raw SBE message is prepended with a specific, known, message type that includes templateId and IR file of the raw SBE message that follows.
- Use a perfect hash to generate IR file and templateId with your own non-SBE header. Or use the above specific SBE message type.

And this is why we no longer supply an IrCollection. It can (and should) be part of the application design.

**Comment by ccge** [comment]
Is there anyway to use the IrDecoder or OtfHeaderDecoder to get the id and version fields out of the messageSchema found here?: https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml

**Comment by tmontgomery** [comment]
I believe it is in the IrDecoder. `m_id` is set from the schema Id. The `sbeSchemaVersion` can be saved from the FrameCodec. Take a look at `IrDecoder::decodeIr` to see what it does. Saving those values from the IR and providing them via IrDecoder should be straight forward.

**Comment by ccge** [comment]
I saw that it is all in ```IrDecoder::decodeIr``` via the ```FrameCodec```. But, again, I am not trying to modify anything in the OTF code.

The next version should include helper methods in ```IrDeocder.h``` to access all the fields in ```messageSchema``` such as ```package```, ```id```, and ```version```.

**Comment by tmontgomery** [comment]
@ccge if you submit a PR with access to those values, I will merge it.

**Comment by mjpt777** [comment]
Closing for now and will await a patch if it is forthcoming.
