### ISSUE TITLE
encode char less than max lenght

### ISSUE THREAD

**Issue by QIvan** [real-logic/simple-binary-encoding#448]
Hi! I play with your [car example](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java) and when I change [value of vehicle code](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java#L46) from ```"abcdef" ``` to  ```"abcde" ``` (removed 'f' symbol) a program fails with the exception 

``` 
Exception in thread "main" java.lang.IndexOutOfBoundsException: srcOffset out of range for copy: offset=0
	at baseline.CarEncoder.putVehicleCode(CarEncoder.java:268)
	at uk.co.real_logic.sbe.examples.ExampleUsingGeneratedStub.encode(ExampleUsingGeneratedStub.java:121)
	at uk.co.real_logic.sbe.examples.ExampleUsingGeneratedStub.main(ExampleUsingGeneratedStub.java:78)
```` 

in generation code:
```java 
        if (srcOffset < 0 || srcOffset > (src.length - length))
        {
            throw new IndexOutOfBoundsException("srcOffset out of range for copy: offset=" + srcOffset);
        }

```

Can you explain this check? Why I can't encode less than 6 characters in this field?

**Comment by mjpt777** [comment]
That convenience method is expecting all the characters. If you want to write less then write the individual characters. 

The error message could be better which I will pick up.

**Comment by mjpt777** [comment]
You should also consider what this means to the reader. I'd fill the unused characters with nulls so they are clearly not used.

**Comment by QIvan** [comment]
Thank you for your explanations !
