### ISSUE TITLE
Inconsistent Agrona Library

### ISSUE THREAD

**Issue by eliasbalasis** [real-logic/simple-binary-encoding#449]
SBETool generates code that is dependent on org.agrona:Agrona library instead of uk.co.real-logic:Agrona contrary to [Overview](https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Maven#overview)

A side effect of this is misleading presence of multiple libraries with same name from different vendor and different version in project's class-path

**Comment by mjpt777** [comment]
Can you point out where exactly the reference to `uk.co.real-logic:Agrona ` is?

**Comment by eliasbalasis** [comment]
Sure, here is the expected dependency
<dependency>
	<groupId>uk.co.real-logic</groupId>
	<artifactId>Agrona</artifactId>
</dependency>

the generated code however references classes from package org.agrona which is found under Maven dependency

<dependency>
	<groupId>org.agrona</groupId>
	<artifactId>Agrona</artifactId>
</dependency>

I believe for consistency, uniformity and convenience the generated code should reference classes from package uk.co.real_logic.agrona which is found under the expected Maven dependency

**Comment by mjpt777** [comment]
org.agrona is correct for Agrona. It is shadowed into the sbe-all.jar. If just using sbe-tool.jar then you need to add it as a dependency.

How does the expected dependency work? I see no reference to this on the overview page.

**Comment by eliasbalasis** [comment]
I see, that's reasonable,

however, step 1 under overview reads

"Add Agrona to your project <dependencies>" (points to expected dependency)

**Comment by mjpt777** [comment]
It points to the repo which is under the real-logic GitHub account but its package structure is org.agrona. Package structure and GitHub accounts are different things.

**Comment by eliasbalasis** [comment]
I have the feeling that "Overview" implies using the expected real-logic.Agrona for project using generated sbe-tool code, which uses org.Agrona instead.

It is misleading I had to figure out and change dependency individually, plus, I am getting multiple Agrona libraries (same functionality) in my class-path this way when for example using Disruptor which depends on real-logic.Agrona

**Comment by mjpt777** [comment]
Are you sure the Disruptor depends on Agrona?

**Comment by mjpt777** [comment]
I've updated to have the non-shadowed dependency, i.e. sbe-tool rather than sbe-all,  and give the Agrona dependency example.

**Comment by mjpt777** [comment]
I've updated to have the non-shadowed dependency, i.e. sbe-tool rather than sbe-all,  and give the Agrona dependency example.

**Comment by eliasbalasis** [comment]
I got confused, Disruptor doesn't seem to be using any Agrona

The concern remains the same however, real-logic artefacts should be using real-logic.Agrona instead of org.Agrona

I can see the instructions changed, I will try with sbe-tool instead sbe-all and let you know

**Comment by mjpt777** [comment]
I don't understand. Why is it a concern that one project depends on another with a different package naming structure? This is perfectly natural and done in many projects with dependencies.

**Comment by mjpt777** [comment]
I don't understand. Why is it a concern that one project depends on another with a different package naming structure? This is perfectly natural and done in many projects with dependencies.

**Comment by eliasbalasis** [comment]
This is partially misleading on my side

I have been accidentally including real-logic.Agrona in my project

I am finally thinking that if a project uses real-logic artefacts which use real-logic.Agrona (expected) and SBE-Tool generated classes it may introduce 2 dependencies in class-path with same name and seemingly same functionality

Is my understanding correct? Could this be a potential side effect?

**Comment by mjpt777** [comment]
There is no current `real-logic.Agrona`. There is a dependency on Agrona which you can find the git repo under the GitHub real-logic organisation. Agrona has the package structure of org.agrona and can be found in Maven Central by searching for agrona.  Many projects start with the company name that incubated them and often turn into their own top level domain as they gain interest. A search for [agrona](https://search.maven.org/#search%7Cga%7C1%7Cagrona) on Maven Central will show such a history for this.

Search for RxJava and you will see a similar history.

https://search.maven.org/#search%7Cga%7C1%7Crxjava

Separately you need to decide if you include the *all* version of a library which includes it dependencies shadowed in or manually control the dependencies yourself so you can have specific versions and no duplication. This is your choice and part of your own build setup.

**Comment by eliasbalasis** [comment]
I see your point, indeed, it is clear is history, started as company specific but changed domain it seems on the way.

Shadowing understood as well.

Thanks for clarifying

**Comment by mjpt777** [comment]
You're welcome.
