### ISSUE TITLE
Engine with repeating groups or variable-length fields

### ISSUE THREAD

**Issue by QIvan** [real-logic/simple-binary-encoding#450]
Can an [engine from your example](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml#L44) have group or data tags? How I should build my schema if I need for example to add to the engine some description?

**Comment by tmontgomery** [comment]
A composite can not have groups or data. A composite is a type, like a struct. Repeating groups and data are message fields. The FIX/SBE spec treats them a bit differently.

There are a couple ways to accommodate an engine description.
- Add a data field to the message that is the engine description separate from the engine composite.
- Add a fixed length element array to the engine to hold the description. Such as fuel type or manufacturer code do.

**Comment by QIvan** [comment]
Thank you @tmontgomery 

P.S. Can I mark this issue as a question?
