### ISSUE TITLE
Bounding check for m_offset

### ISSUE THREAD

**Issue by myrgy** [real-logic/simple-binary-encoding#461]
Hi

we are using SBE template from ftp://ftp.cmegroup.com/SBEFix/Production/Templates/running using -fsanitize=address. During testing our application with american fuzzy lop I found that we got several crashes.
Crashes were caused by BAD_ACCESS during filed reading, like:
` std::uint64_t transactTime() const
    {
        return SBE_LITTLE_ENDIAN_ENCODE_64(*((std::uint64_t *)(m_buffer + m_offset + 0)));
    }`
 in case when input data was corrupted m_offset contains wrong value, which cause crash as a result.
My proposal is to add bounding check.

**Comment by tmontgomery** [comment]
What type of checking and where do you suggest? And what type of corruption is this?

**Comment by myrgy** [comment]
as initial input parameter we receive buffer and buffer size.
so, we can check if offset is less that buffer size.  And in case, when not - throw exception.
It's not a corruption, but we trying to deference pointer, which points far away from original data.
as a result we have undefined behaviour. In my case - application crashes.

**Comment by tmontgomery** [comment]
There already is a check of offset with respect to buffer length in the codecs `reset` when it sets position. This catches situations where the acting block length, offset, and buffer pointer are not in agreement with the buffer length.

Do you have bounds checks disabled?

Is there a test missing from https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/test/cpp/BoundsCheckTest.cpp for catching this?

**Comment by myrgy** [comment]
SBE_NO_BOUNDS_CHECK macro is not defined.

I have one entity inside another one
it looks like:
`
class Internal
{
private:
    char *m_buffer;
    std::uint64_t m_bufferLength;
    std::uint64_t m_offset;
    std::uint64_t m_actingVersion;

    inline void reset(char *buffer, const std::uint64_t offset, const std::uint64_t bufferLength, const std::uint64_t actingVersion)
    {
        if (SBE_BOUNDS_CHECK_EXPECT(((offset + 3) > bufferLength), false))
        {
            throw std::runtime_error("buffer too short for flyweight [E107]");
        }
        m_buffer = buffer;
        m_bufferLength = bufferLength;
        m_offset = offset;
        m_actingVersion = actingVersion;
}
...};

class Main
    {
    private:
        char *m_buffer;
        std::uint64_t m_bufferLength;
        std::uint64_t *m_positionPtr;
        std::uint64_t m_blockLength;
        std::uint64_t m_count;
        std::uint64_t m_index;
        std::uint64_t m_offset;
        std::uint64_t m_actingVersion;
        Internal m_internal;

    public:
        inline void wrapForDecode(char *buffer, std::uint64_t *pos, const std::uint64_t actingVersion, const std::uint64_t bufferLength)
        {
            m_buffer = buffer;
            m_bufferLength = bufferLength;
            m_internal.wrap(m_buffer, *pos, actingVersion, bufferLength);
            m_blockLength = m_dimensions.blockLength();
            m_count = m_dimensions.numInGroup();
            m_index = -1;
            m_actingVersion = actingVersion;
            m_positionPtr = pos;
            *m_positionPtr = *m_positionPtr + 3;
        }
`
So it looks like I have this check - but it doesn't solve my issue.

**Comment by myrgy** [comment]
Thaks you. 
Yes, this check is enabled.
In my case issue was caused by wrong application logic:
I have 2 decoding operations where second depend from first one. 
As a result I pass wrong buffer size to second decode.

**Comment by tmontgomery** [comment]
Thanks! Glad you found it.
