### ISSUE TITLE
Message Within Message

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#465]
This is related to --> [https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/54](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/54)

Does real-logic support encoding/decoding of a template within a template with both templates belonging to the same schema?

For example there is a schema containing both template 1 and template 2

Template 1 contains a variable length field which contains a message which is actually template 2

Will the decoder get the bytes from the variable length field and then pass those to the application and the application will tell the decoder to use template 2 to decode the message based on the template ID in the message header or will real logic be able to decipher that the message in the variable length field in template 1 belongs to template 2 by automatically reading the template ID in the message header?

**Comment by mjpt777** [comment]
You can indirectly do this by wrapping the encapsulated message with the template of the appropriate type around the var data field. This can also work for a template from another schema.

**Comment by adkapur** [comment]
Sorry but I didn't understand, could you please provide an example to illustrate your explanation if possible?

**Comment by tmontgomery** [comment]
Imagine a message composed of 2 message schemas. One followed immediately by the other. The second can contain the var data field laid out as a schema itself.

The SBE codecs can do this.

**Comment by adkapur** [comment]
Yes correct agreed but if we slightly reword your example to say that a message is composed of two message templates (with both belonging to the same schema), one immediately followed by the other with the second template containing a var data field laid out as a template itself then is that also supported?

**Comment by mjpt777** [comment]
The SBE XSD schema does not have support for a template within a template. I argued when the spec was being formed that they should be types and types should be composable but that was not accepted.

Given the current spec and implementation, the only way this is possible is to have a var-data field which can have an encoded message inside it that you would need to encode in a separate buffer and then copy in, the reverse being a bit more simple as it would be a simple wrapping of the var-data field for decoding.

**Comment by adkapur** [comment]
Okay I see, actually customers are complaining that this approach leads to a proliferation of schemas therefore we would like to revisit and explore this since they would prefer to have a single schema contain all template files. We are going to track this here at -->  [https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/54](url)
