### ISSUE TITLE
Rust code generation

### ISSUE THREAD

**Issue by ZackPierce** [real-logic/simple-binary-encoding#467]
[Rust](https://www.rust-lang.org) is a language with good philosophical alignment with SBE around performance and not introducing unnecessary overhead. It would be great to be able to directly use SBE with Rust programs without relying on wrapping generated C++ bindings.

I propose the addition of Rust encoder/decoder generation to the sbe-tool.  

As a stretch goal, in addition to adding another target ecosystem, it may be possible to use some of the type-system language features of Rust to generate encoders/decoders which make writing invalid messages a compile-time error rather than a run-time corruption of data.

Assuming the project caretakers and community approve, I'd like to take a swing at implementing this issue. Guidance around contribution best practices above and beyond adhering to the [SBE design principles](https://github.com/real-logic/simple-binary-encoding/wiki/Design-Principles) is most welcome.

**Comment by tmontgomery** [comment]
Go for it. Feel free to follow the Go Lang implementation as a means to hook things in and the target generator.

**Comment by tmontgomery** [comment]
Actually, the C# generator instead of the Go Lang one as @billsegall pointed out in gitter.
