### ISSUE TITLE
Copy constructor regression

### ISSUE THREAD

**Issue by tamboril** [real-logic/simple-binary-encoding#468]
Related to #164, I think this is a regression as a result of PR #391.
Compiler-generated copy constructors for C++ generated classes yield invalid copies due to the pointer m_positionPtr.

**Comment by tmontgomery** [comment]
They have been put back now. Try them out and let us know how they function. The issue of not being able to copy a default constructed codec should be fixed as well.

**Comment by tamboril** [comment]
Thanks for the quick response.  I'll try it again.

**Comment by tamboril** [comment]
Looks good.  I only had to make a slight adjustment for a change related to `offset()`, but it passed some pretty exhaustive tests on th decode side for me.

Closing...
