### ISSUE TITLE
C++ generator issue

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#470]
Messages like below looks good for C++ generator

```xml
    <message name="Message1" id="1" blockLength="16">                                           
        <field name="field1" id="0" type="uint64"/>                                             
        <field name="field1" id="0" type="uint8"/>                                             
    </message>   
```

I don't know if it valid for SBE spec, but generated C++ code is not compilable

**Comment by mjpt777** [comment]
This is valid. If you wanted to align the beginning of a repeating group or var data on a 16 byte boundary then you would do this. If `blockLength` is set then it must be greater than or equal to the sum of the field lengths given their offsets.

In what way does it not comply?

**Comment by ksergey** [comment]
@mjpt777 I mean both fields has name "field1"

**Comment by mjpt777** [comment]
Ah, that was not clear in the title of the issue. I'll investigate.

**Comment by mjpt777** [comment]
I've pushed a change that validates message and field names are unique in context.
