### ISSUE TITLE
[go]: Range Checks and Null Values?

### ISSUE THREAD

**Issue by meyerdan** [real-logic/simple-binary-encoding#472]
We are generating Encoders/Decoders for go.

In our schema, we have a field, defined as follows:

```xml
<field name="position" id="2" type="uint64" presence="optional" />
```

Our question goes to the range-checking which can be enabled in the generated decoder.
We observe that the check is generated as follows, regardless whether the `presence="optional"` attribute is set or not:

```go
  if s.PositionInActingVersion(actingVersion) {
        if s.Position < s.PositionMinValue() || s.Position > s.PositionMaxValue() {
            return fmt.Errorf("Range check failed on s.Position (%d < %d > %d)", s.PositionMinValue(), s.Position, s.PositionMaxValue())
        }
    }
```

If a `null` value is received, it will be `s.PositionMaxValue() + 1`.

Our question is: should the range check code accommodate for null values or are we maybe confusing something?

**Comment by billsegall** [comment]
I think it's a bug. I'll have a look.

**Comment by billsegall** [comment]
I'm seeing token.presence() is always REQUIRED (which is why is token.isOptionalEncoding() is returning false on me. My test file is quite simple:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe"
                   package="issue472"
                   id="472"
                   version="0"
                   semanticVersion="1.0"
                   description="issue 472 test case"
                   byteOrder="bigEndian">
    <types>
        <composite name="messageHeader" description="Message identifiers and length of message root">
            <type name="blockLength" primitiveType="uint16"/>
            <type name="templateId" primitiveType="uint16"/>
            <type name="schemaId" primitiveType="uint16"/>
            <type name="version" primitiveType="uint16"/>
            <ref name="s" type="setRef"/>
        </composite>
    </types>
    <sbe:message name="issue472" id="1" description="issue 472 test">
        <field name="position" type="uint64" id="2" presence="optional"/>
    </sbe:message>
</sbe:messageSchema>
```

**Comment by mjpt777** [comment]
The optional is applied to the field here and not the type. The IR has this reflected in the `field` token vs the contained `type` token(s). The spec has some issues here. For example, `presence` is available on basic types but not composites, enums, or bitsets. There are also issues with `minValue`, `maxValue`, and `nullValue` being available on the type but not the field.  I personally believe the type should not have presence or restrictions and they should only be on the field. Maybe @donmendelson has a view here?

**Comment by donmendelson** [comment]
See issue https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/31
This change has already been approved by working group. I'd appreciate review of the proposed change for SBE version 2.0 RC1.

**Comment by billsegall** [comment]
See https://github.com/real-logic/simple-binary-encoding/pull/475
