### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by RexLee64** [real-logic/simple-binary-encoding#478]
Hi, there is some erros when i use it to decode the  schema of CME.

```
java -Dsbe.target.language=cpp \
     -Dsbe.output.dir=target \
     -jar sbe-all/build/libs/sbe-all-1.7.1-SNAPSHOT.jar \
     templates_FixBinary.xml
```
and then:

`Exception in thread "main" java.lang.IllegalStateException: Invalid property name='final' please correct the schema or consider setting system property: sbe.keyword.append.token`

**Comment by mjpt777** [comment]
See question 3 in the FAQ. https://github.com/real-logic/simple-binary-encoding/wiki/Frequently-Asked-Questions
