### ISSUE TITLE
cpp generator

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#479]
Why we need `m_bufferLength` and `m_actingVersion` private variables in generated class MessageHeader? This members not used inside MessageHeader.

**Comment by ksergey** [comment]
Variable `m_actingBlockLength` in other classes also unused

**Comment by tmontgomery** [comment]
MessageHeader is generated from a fixed flyweight. Those fields are used by other flyweights. Or I should say, might possibly be used depending on schema. `m_bufferLength` probably should have a getter. Agreed. Feel free to add that or I will eventually.

**Comment by ksergey** [comment]
@tmontgomery Thank you! When you release new version?

**Comment by mjpt777** [comment]
We will be releasing this shortly.

**Comment by ksergey** [comment]
@mjpt777 
The same for messages - `m_bufferLength` should have public getter. Could you please fix?

**Comment by mjpt777** [comment]
Done.

**Comment by ksergey** [comment]
Thanks
