### ISSUE TITLE
Simple Open Framing Header

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#482]
Just wanted to clarify if the SOFH is supported by the real-logic encoder/decoder or not? thanks

**Comment by mjpt777** [comment]
Can you provide more details to what this is?

**Comment by RichardWarburton** [comment]
I think he's referring to https://github.com/FIXTradingCommunity/fix-simple-open-framing-header.

**Comment by mjpt777** [comment]
No one has engaged us so far to do any work on this so no direct support for SOFH in this SBE implementation.

However the message header type in SBE can be extended to provide extra fields.

**Comment by adkapur** [comment]
Is it possible to revisit this? The main impetus is to have total message size as part of the schema since blockLength in the SBE header today only includes the root length and excludes variable length data fields and repeating groups

**Comment by donmendelson** [comment]
Aditya, SOFH is independent of the SBE header. In fact, it is independent of SBE since it was designed to allow mixing of encodings on the wire, e.g. SBE plus tag value or XML messages. 

Nevertheless, it is possible to define SOFH has a composite type in your SBE message schema with length and code elements, and Real Logic implementations will generate an encoder and decoder for it. There is just one tricky point: SOFH is always network byte order (big endian) while SBE can use either byte order.

**Comment by billsegall** [comment]
I"d like to add one other consideration to framing headers which is that you might use one framing header for multiple SBE encoded messages. 

A usage case might be to maximize bandwidth usage whilst ensuring that each network data unit contained only complete messages. You would then pack them into a network protocol  buffer with a single framing header.

Bill.

**Comment by adkapur** [comment]
Okay great thanks to both, that is good to know. Yes we are looking into the possibility of the framing header being able to encapsulate multiple templates and represent total message size of all those templates

If we add this to the schema then it will precede the SBE header since that is specific to each message and suppose if we encode a new order as two templates (one template containing business critical information and the other template containing ancillary information) then the framing header could be used to encapsulate both templates and communicate total message size of both as a single logical message

The framing header could also serve as a marker of where each message starts in a TCP connection which is a continuous stream of bytes unlike packet based UDP

**Comment by adkapur** [comment]
Even extending the SBE header to include message size as part of SBE 2,0 also sounds attractive and would enable the recipient to jump ahead to the next template if they are not interested in the first one and so on

Total message size in framing header encapsulating multiple templates and message size of each template in SBE header

**Comment by RFrenkel** [comment]
Could we include framing header as allowed and supported optional composite field, the elements of which can be specified by publishing application in the schema itself, 

The number of elements of the farming header, elements definitions and structure doesn't have to be standardized for everyone, as it may require different design for each application, implementation approach and transport type.
However, as  part of the standard we could include support for the optional specification of the framing header to be defined in the application schema. If it is defined, receiving application will expect it be sent just before SBE header. If not defined, then SBE header will be expected as the first few bytes. 

Total msg Size can also be defined as part of optional Framing Header composite, so it doesn't break current SBE message header and RC4 customers.  
If total message size needs to be provided, then it can be the only element of the framing header. It could also be just the first element, if design of the messages calls for more elements.

My thought is the design of the framing headers must be left flexible, per application, transport type and implementation.

**Comment by adkapur** [comment]
Yes but we need total message size in the SBE header also (as part of SBE 2.0) as Martin is suggesting and the total message size of the framing header could encapsulate multiple templates as a single logical message as Bill has suggested
