### ISSUE TITLE
Can I add a variable length member in a SBE composite type?

### ISSUE THREAD

**Issue by darthninja1** [real-logic/simple-binary-encoding#485]
I have a nested data structure that I'm trying to integrate with SBE. One of the nested objects has a string member. How can I add variable length fields to composite types?

**Comment by mjpt777** [comment]
No. The specification does not allow for variable length fields in a composite.

Variable length fields can be added at the end of a repeating group or the end of a message. You can compose something more complex with repeating groups or multiple messages.
