### ISSUE TITLE
Separate bit twiddling from buffer accesses in sets

### ISSUE THREAD

**Issue by jnj** [real-logic/simple-binary-encoding#489]
This is a wish list item. It would be nice in the generated output to separate the buffer accesses from the bit manipulation in bit sets because we may not always have a buffer to work with. For example:

```java

// This decoder requires a buffer containing our byte.
public boolean lastVolumeMsg()
{
        return 0 != (buffer.getByte(offset) & (1 << 1));
}
```

I'd like to have, say, a static method that doesn't require a buffer:

```java
// No buffer needed.
public static boolean lastVolumeMsg(byte b)
{
        return 0 != (b & (1 << 1));
}
```

**Comment by mjpt777** [comment]
Seems reasonable.  I'll look at adding this.

**Comment by tmontgomery** [comment]
I think this makes sense as well.

**Comment by tmontgomery** [comment]
Needed for C++ also.
