### ISSUE TITLE
JavaScript codec

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/simple-binary-encoding#5]
JavaScript codec should be straight forward to add. Here are some options and thoughts.

For Node.js, the buffer API is very compatible with the Java CodecUtils. http://nodejs.org/docs/v0.6.0/api/buffers.html

For the browser, there are ArrayBuffer and DataView via Typed Arrays. These are similar in concept as well.

https://developer.mozilla.org/en-US/docs/Web/API/DataView?redirectlocale=en-US&redirectslug=Web%2FJavaScript%2FTyped_arrays%2FDataView#Browser_compatibility

http://www.html5rocks.com/en/tutorials/webgl/typed_arrays/

**Comment by mjpt777** [comment]
Other languages are encouraged. Closing to for now as it is not an issue.

**Comment by rafalpiotrowski** [comment]
checkout https://github.com/rafalpiotrowski/simple-binary-encoding
branch: typescript-support
run ./gradlew generateTypeScriptExamples it will generate codes in generated/ts folder
soon I will be publishing agrona DirectBuffer implementations so the code can be tested

**Comment by unicomp21** [comment]
Is the implementation finished @rafalpiotrowski?  Agrona status?

**Comment by unicomp21** [comment]
btw, nice job!

**Comment by unicomp21** [comment]
@mjpt777 can we PR this?

**Comment by mjpt777** [comment]
> @mjpt777 can we PR this?

We would consider a PR. Would someone be committed to maintaining it?

**Comment by unicomp21** [comment]
I'd be willing to help, @rafalpiotrowski thoughts?
