### ISSUE TITLE
presence="optional" for the Composite type

### ISSUE THREAD

**Issue by l-yara** [real-logic/simple-binary-encoding#509]
Hello All,

Is it possible to have an optional (nullable) field of the composite type? For instance, in our beloved `Car` scheme it is possible to specify:
```
<sbe:message name="Car" id="96" description="Description of a basic Car">
    ...
    <field name="engine" id="9" type="Engine" presence="optional"/>
    ...
</sbe:message>
```
(note `presence="optional"` in the declaration) while `Engine` type is being defined as 
```
<composite name="Engine">
    <type name="capacity" primitiveType="uint16"/>
    <type name="numCylinders" primitiveType="uint8"/>
    ....
</composite>
```
I'd expect that would mean that the whole `engine` field might be missing from the message, but how will I:
- encode the fact that engine is not provided via `CarEncoder`?
- decode that fact with `CarDecoder`?

For primitive types we do have the `<fieldName>NullValue()` statics but not for the composites. 
In #30 it was suggested that we can use "setting or testing its first primitive type encoding" (special thanks to @donmendelson for this trick). That would work great for the collections of primitives and Strings but does not make much sense for the composites: what if composite does not have primitive? what if composite's first primitive type field can legitimately be `null` by itself while the composite instance is present?
In #325 it was mentioned that spec does not make a difference between empty varData and null one. I could not find anything about optional composite fields but such option would be VERY useful.

**Comment by donmendelson** [comment]
One solution to this problem is to create Engine as a repeating group rather than as a composite type. It would have fields capacity, numCylinders, etc. You could limit the maximum number of entries to 1, so there could be zero or one Engines. See "Restricting repeating group entries" in the spec.
(Without constraints, it would allow you to describe a hybrid car with multiple engines.)

**Comment by karypid** [comment]
May I point out that according to [the spec](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/04MessageSchema.md) supposedly:

> Null value of a composite type

> For a composite type, nullness is indicated by the value of its first element. For example, if a price field is optional, a null value in its mantissa element indicates that the price is null.

**Comment by mjpt777** [comment]
I'm closing this as it would be best handled on the spec repo.
