### ISSUE TITLE
VS2017(C#) Where is Uk.Co.Real_logic.Sbe.Benchmarks.Fix?

### ISSUE THREAD

**Issue by Bigbear119** [real-logic/simple-binary-encoding#511]
Environment:
VS2017
When I download and open c# project, I cannot compile c# project.
Missing Uk.Co.Real_logic.Sbe.Benchmarks.Fix
Where can I include the package?
I also cannot compile sbe-samples-car, because there is no Car and MessageHeader class in those files.

**Comment by billsegall** [comment]
You will need to generate the codecs. See the section labelled "C# build"
at the top level README in https://github.com/real-
logic/simple-binary-encoding.

Alternately the sbe-tool guide at https://github.com/real-
logic/simple-binary-encoding/wiki/Sbe-Tool-Guide has some help for you on
invoking sbe-tool.

Also see the documentation at:
https://github.com/real-logic/simple-binary-encoding/tree/master/csharp

Bill.

**Comment by Bigbear119** [comment]
Ha~ Thanks~
It works now.
I didn't notice that I should generate the codecs first.
