### ISSUE TITLE
Boolean error when generating codecs

### ISSUE THREAD

**Issue by WolfAlexander** [real-logic/simple-binary-encoding#512]
Hi!

In generated classes, there are several errors with Booleans when generating codecs with sbe-all-1.7.2:
* buffer.putByte(offset + 68, (byte)value.**value()**); - 'value' has a private access in java.lang.Boolean
* return Boolean.**get**(((short)(buffer.getByte(offset + 40) & 0xFF))); - cannot resolve method 'get'

**Comment by WolfAlexander** [comment]
I think I solved it, so for booleans we should create enums, right?

**Comment by mjpt777** [comment]
Here is an example of creating a Boolean.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml#L54
