### ISSUE TITLE
C++ Generator: MessageHeader copy-constructor broken

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#513]
Hi,

Latest stable release generate incorrect copy-constructor for `MessageHeader`:
```c++
    MessageHeader(const MessageHeader& codec) :                                                                                                    
        m_buffer(codec.m_buffer), m_offset(codec.m_offset), m_actingVersion(codec.m_actingVersion){} 
```
Missed  `m_bufferLength`  copying

I believe copy-constructor and copy-operator could be default
```c++
#if __cplusplus >= 201103L
MessageHeader(const MessageHeader&) = default;
MessageHeader& operator=(const MessageHeader&) = default;
#endif
```

Also why you support old c++ standard? I believe will be reasonable to require c++11 for generated code. 

Thanks

**Comment by mjpt777** [comment]
I've fixed the bug but will let @tmontgomery comment on approach.

**Comment by tmontgomery** [comment]
For MessageHeader (and composites), defaults would work. But the generator reuses some of the logic from the message codecs. Which can't use default.
