### ISSUE TITLE
Primitive types decoding problems

### ISSUE THREAD

**Issue by WolfAlexander** [real-logic/simple-binary-encoding#514]
Hi!

I have a problem with decoding messages. Currently, some of int64 och uint64 are decoded wrong:

Expected: 2000000
Actual:  1982271

Expected: 1504472334000
Actual:      1504467435327

Rest of messages and some int64 are decoded as expected. So question is, why does it happen?

* Messages are encoded on another hardware then they are being decoded.
* When encoding and decoding on the same computer - works as expected.
* Using Java and generated stubs
* We have Python code that is decoding as expected

**Comment by mjpt777** [comment]
Can you provide a testcase? What version are using using of SBE and what language?

**Comment by mjpt777** [comment]
Sorry I meant to ask about OS and CPU architecture.

**Comment by WolfAlexander** [comment]
Unfortunately, I am not allowed to share the data.

MacOS Sierra 10.12.6, 64-bit.

**Comment by WolfAlexander** [comment]
I might be able to get a test case with fake test data from those who encodes messages, but no certain. If I get one, I will post here.

**Comment by mjpt777** [comment]
What version of SBE and JVM? Without a test case there is little we can do.

**Comment by WolfAlexander** [comment]
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

SBE 1.7.1
But stubs for testing are generated with sbe-all-1.7.2-SNAPSHOT.

**Comment by mjpt777** [comment]
Thanks. If you can get a testcase then we can investigate.

**Comment by WolfAlexander** [comment]
I believe we solved it. The error was ours -  we needed to add a specific charset when we where putting the strings in buffer and in one other place:

```
ByteBuffer sbeEncodedMessageBuffer = ByteBuffer.allocateDirect(MSG_SIZE);
sbeEncodedMessageBuffer.put(sbeEncodedMessage.getBytes(StandardCharsets.ISO_8859_1));
```

**Comment by mjpt777** [comment]
It sounds like some corruption. I don't see from your code spinet how this happened as it is not an API I recognise. Maybe you are showing out of context. Happy it is resolved for you anyway.
