### ISSUE TITLE
[Java] How to deal with BigDecimal

### ISSUE THREAD

**Issue by loveyoupeng** [real-logic/simple-binary-encoding#520]
Hi there,
      Our project is highly rely on BigDecimal to represent financial data, is there any suggestions or best practices we could follow to encode/decode BigDecimal or any mapping utilities available
      Thanks a lot 
       Yunpeng Li

**Comment by mjpt777** [comment]
SBE is designed to be a cross language standard. BigDecimal is Java specific in its implementation plus it also has serious performance implications. When dealing with fixed point numbers I often use a `long` to represent a value and a `byte` or `int` to represent the scale for where the decimal point is in the value. This is easy to serialise to in SBE or other formats. You could convert BigDecimals to this or a String format for encoding/decoding with SBE.

**Comment by loveyoupeng** [comment]
Thanks for the advice

Thanks a lot
Yunpeng Li
