### ISSUE TITLE
Current Rust build fails with Cargo installed

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#524]
If I run the current gradle build then it fails for me.  I'm using windows to run the build and have cargo installed. I've tried both using `./gradlew` under mingw git bash and also gradlew.bat under regular windows cmd.exe here is the output from the shell related to cargo if I pass the --debug flag:

3:39:10.974 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'cargo''. Working directory: <REDACTED>\simple-binary-encoding\rust\car_example Command: cargo run
13:39:10.974 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'cargo'':<REDACTED>}
13:39:10.974 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
13:39:10.974 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'cargo'.
13:39:11.031 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
13:39:11.031 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'cargo''
13:39:11.031 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
13:39:13.089 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
13:39:13.089 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'cargo'' finished with exit value 101 (state: FAILED)
13:39:13.089 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute task action 2/2 for :runRustCarExample'

If I run ./gradlew -x "runRustCarExample" then I the RustGeneratorTest fails for me.

**Comment by tmontgomery** [comment]
Seems that currently, the Rust build has sprung up as failing again after latest commits.

**Comment by tmontgomery** [comment]
I've added a property `sbe.skipRust` that can be used to skip the Rust integration tests when `cargo` is found, but the tests should be skipped.
