### ISSUE TITLE
Using choice values > 32 causes Visual C++ to spit warnings

### ISSUE THREAD

**Issue by ksavela** [real-logic/simple-binary-encoding#525]
I'm using Visual C++ 14 (Visual Studio 2015 Pro) and my message format uses a set that has more than 32 choices so I use uint64 as the encodingType.  

    <set name="SomeSet" encodingType="uint64">
      <choice name="CHOICE_1">0</choice>
      <choice name="CHOICE_2">1</choice>

      

      <choice name="CHOICE_33">32</choice>
      <choice name="CHOICE_34">33</choice>
    </set>

The warning is

> ... warning C4293: '<<': shift count negative or too big, undefined behavior

The generated code about which the compiler complains is something like:

`
   static bool cHOICE_33(const std::uint64_t bits)
    {
        return bits & (0x1L << 32);
    }

    static std::uint64_t cHOICE_33(const std::uint64_t bits, const bool value)
    {
        return value ? (bits | (0x1L << 32)) : (bits & ~(0x1L << 32));
    }

    bool cHOICE_33() const
    {
        return SBE_LITTLE_ENDIAN_ENCODE_64(*((std::uint64_t *)(m_buffer + m_offset))) & (0x1L << 32);
    }
`
where there is a warning associated with each 0x1L<<"count".  The Microsoft compiler uses 32-bits for long while gcc uses 64 (when compiling for 64-bit architecture).  

I just now ran across this so I'm not sure if the code is actually broken but I suspect it is.  When I get a chance to test this I'll update this issue report.

Would someone be willing to make the type of that literal 0x1L more consistent with the encodingType, perhaps using a static_cast to the encodingType or perhaps using the resulting number as a literal rather than having the compiler shift this?  e.g. 0x100000000 instead of 0x1L<<32 ?

**Comment by tmontgomery** [comment]
Will take a look at when I can.

**Comment by tmontgomery** [comment]
Does this work as expected now?
