### ISSUE TITLE
Decoding with stubs - NoSuchElementException

### ISSUE THREAD

**Issue by WolfAlexander** [real-logic/simple-binary-encoding#526]
Hi. I am having a weird problem when decoding.

I have an message with following structure:

```
[Message]
superdatafields
superlist=[
	(
		datafields
		innerlist = [(
			innerobject=(1…..)
		)]
	),
	(
		datafields
		innerlist= [(
			innerobject=(2…..)
		)]
	),
]
```

From this message, several object should be created. The number objects depends on number of elements in the superlist.

```
StreamSupport.stream(superlist.spliterator(), false)
        .map(superlistelement -> createObject(superdatafields, superlistelement))
        … (other stuff)

```

```
private static Object createObject(superdatafields, superlistelement){
      Object object = superlistelement.innerlist.next();

      System.out.println(object.innerobject());
	….
}

```
Outprint after running:
```
({1……})
java.util.NoSuchElementException…
```

But, if I instead do `System.out.println(object)`, then:
```
(Innerobject{1……})
(Innerobject{2……})

```
So why when I am printing the object, it is alright and I can see both inneobjects. But if I try to access the inneobject, I get NoSuchElementException on second innerobject.
Using generated stubs from a schema.

**Comment by mjpt777** [comment]
The samples you post do not look like SBE. Could this be some other encoding? If you would like help can you please post a gist to a full example showing the issue you are seeing?

**Comment by WolfAlexander** [comment]
Well, I get SBE encoded messages and trying to decode using SBE stubs.. so how do you mean it is not SBE? Or do you mean the code? 

Unfortunately, cannot post more code or data or schema. I thought that I might did some obvious error when accessing lists or you should not use streams with stubs. Because those stub-decoders are quite weird - for example if I print an decoder object and then directly after access and print the inner value, I get wrong or weird value.

**Comment by WolfAlexander** [comment]
The message that does have only one element in superlist works fine

**Comment by mjpt777** [comment]
It could be related to how the spliterator and streaming works. SBE requires that nested objects are accessed in a specific order. If you access in the wrong order then you are likely to get undefined results.

SBE does not allocate objects. It is designed to be used as a flyweight pattern. They are not "weird" ;-) it is how the flyweight pattern works. If the stream needs to retain allocated objects then it will not work.

**Comment by mjpt777** [comment]
> The messages that does have only one element in superlist works fine

This sounds like you are trying to retain the "object" from each iteration and this does not work with the flyweight pattern.

**Comment by WolfAlexander** [comment]
Might be the orderproblem. Since it works when I print the decoder, I will have to look trough in what order the decoder prints its inner object and see if I find something.

**Comment by WolfAlexander** [comment]
I see. Any suggestions?

**Comment by mjpt777** [comment]
SBE is designed for reading what you require then moving on. Streamed memory access is the fastest access method. If you need to retain the data then you need to copy it. SBE does not produce POJOs like many other codecs, and thus it does not create GC pressure like the others, the consequence is you have to decide what data you want to capture and retain yourself. If you want to replace some other codec with SBE then you need to consider the design. It is likely not a drop in replacement.

**Comment by WolfAlexander** [comment]
Alright, I know what I have to change now. Thank you.
