### ISSUE TITLE
BUG: C++ wrong null value for enum

### ISSUE THREAD

**Issue by arobenko** [real-logic/simple-binary-encoding#527]
Custom nullValue specified for enum type
```
<enum name="Enum1" encodingType="int16" presence="optional" nullValue="10000">
    <validValue name="Val1">-1000</validValue>
    <validValue name="Val2">2005</validValue>
    <validValue name="Val3">3000</validValue>
</enum> 
```
is not taken into account when generating C++ code:
```
class Enum1
{
public:

    enum Value 
    {
        Val1 = (std::int16_t)-1000,
        Val2 = (std::int16_t)2005,
        Val3 = (std::int16_t)3000,
        NULL_VALUE = (std::int16_t)-32768 // <---- WRONG
    };
    ...
};
```
Reproduced with v1.7.4

**Comment by mjpt777** [comment]
This is not a bug. If you turn on schema validation the follow error is emitted:
```
[Error] :36:91: cvc-complex-type.3.2.2: Attribute 'presence' is not allowed to appear in element 'enum'.
[Error] :36:91: cvc-complex-type.3.2.2: Attribute 'nullValue' is not allowed to appear in element 'enum'.
```

**Comment by arobenko** [comment]
Just like mentioned in #529, I think any example mentioned in the spec is a valid one and I as a developer would expect it to be supported by the compiler. The spec contains the following example of optional boolean:
```
<enum name="optionalBoolean" encodingType="uint8" presence="optional" nullValue="255" semanticType="Boolean">
    <validValue name="false">0</validValue>
    <validValue name="true">1</validValue>
</enum>
```
Seeing this I won't think twice before attempting something like this in my schema. Yes, I'm aware that table in section "4.5.6.1" doesn't contain the "presence" and "nullValue" properties, but still, maybe it's worth considering to be supported.

**Comment by mjpt777** [comment]
This is a mistake in the spec. I've raised an issue but have little influence over the specification.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/61
