### ISSUE TITLE
SBE + Aeron

### ISSUE THREAD

**Issue by vad0** [real-logic/simple-binary-encoding#534]
Hello! I am trying to use SBE and Aeron in one project, but there is a problem: they use different Agronas. SBE Tool generates sources with prefix org.agrona.*,  but Aeron uses uk.co.real_logic.*. What is the best way to make them use the same Agrona? I tried to specify uk.co.real_logic dependency in SBE plugin, but it didn't work. Could you pls help? Thank you

**Comment by mjpt777** [comment]
Both Aeron and SBE in the current release use the same version of Agrona, or at least they should do. Can you be more specific about the issue you are seeing and maybe point to a concrete example?

**Comment by tmontgomery** [comment]
You must use compatible versions of SBE and Aeron. i.e. ones that have the same Agrona version. This looks like you are mixing an old Aeron with a newer SBE.

**Comment by tmontgomery** [comment]
As of this comment (Dec. 18. 2017), SBE deps on Agrona 0.9.12 and Aeron deps on Agrona 0.9.12. Information taken from the build.gradle files for both repos. The releases of both dep on Agrona 0.9.12.

**Comment by vad0** [comment]
Thanks a lot! It was really the case.

**Comment by tmontgomery** [comment]
No worries. I'll close this then.
