### ISSUE TITLE
Variable fields in composite

### ISSUE THREAD

**Issue by darthninja1** [real-logic/simple-binary-encoding#537]
Some time back I [asked ](https://github.com/real-logic/simple-binary-encoding/issues/485) a similar question.

There seems to be a way to achieve what I want using the following as long as I specify max length. In addition, with this approach a repeating groups could be added in any order.

Is there a downside of this approach?

If these are truly supported, could you update the docs to reflect this. The current docs IMO are a bit cryptic. It may help to have relevant examples added/

>     <sbe:message name="Payload" id="1">
>         <field name="field6" id="1" type="SomeField"/>
>         <field name="field2" id="2" type="double"/>
>         <field name="field4" id="3" type="varDataEncoding"/>
>         <field name="field5" id="4" type="varStringEncoding"/>
>         <field name="field3" id="5" type="BooleanType"/>
>         <field name="field1" id="6" type="uint64"/>
>     </sbe:message>
> 

... the composite details -

>         <composite name="varDataEncoding">
>             <type name="length" primitiveType="uint32" maxValue="1073741824"/>
>             <type name="varData" primitiveType="uint8" length="5"/>
>         </composite>
>         <composite name="varStringEncoding">
>             <type name="length" primitiveType="uint32" maxValue="1073741824"/>
>             <type name="varData" primitiveType="char" length="10" characterEncoding="ASCII"/>
>         </composite>
>         <composite name="SomeField">
>             <type name="length" primitiveType="uint32" maxValue="1073741824"/>
>             <type name="blah" primitiveType="double" length="5"/>
>         </composite>
> 

This allows me to do - 
```
        payloadEncoder.wrapAndApplyHeader(buf, 0, messageHeaderEncoder);
        payloadEncoder.field1(10).field2(112).field3(BooleanType.F);
        payloadEncoder.field4().length(2);
        payloadEncoder.field4().varData(0, (short) 1);
        payloadEncoder.field4().varData(1, (short) 2);
        payloadEncoder.field5().length(1);
        payloadEncoder.field5().varData("hellohello");
        payloadEncoder.field6().length(1);
        payloadEncoder.field6().blah(0, 2);

        messageHeaderDecoder.wrap(buf, 0);
        int bufferOffset = messageHeaderDecoder.encodedLength();
        dupeDecoder.wrap(buf, bufferOffset, messageHeaderDecoder.blockLength(), messageHeaderDecoder.version());
        System.out.println(dupeDecoder.field5().varData());
        System.out.println(dupeDecoder.field6().blah(0));
        System.out.println(dupeDecoder.field1());
        System.out.println(dupeDecoder.field2());
        System.out.println(dupeDecoder.field3());
        System.out.println(dupeDecoder.field4().varData(0));
        System.out.println(dupeDecoder.field4().varData(1));

```

The output -

```
hellohello
2.0
10
112.0
F
1
2
```

**Comment by mjpt777** [comment]
This is not valid under the [SBE](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) specification. It may be "working" for you but this type of behaviour is not defined. Please refer to the [SBE] (https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) specification for what is supported. You can use a hammer to bash in screws but it does not mean it is right to do it :-)
