### ISSUE TITLE
Support for Python

### ISSUE THREAD

**Issue by shrishinde** [real-logic/simple-binary-encoding#539]
Congratulations on good work being done here.
Is there scope/plan for making this available for Python 2.7 programmers?

**Comment by da4089** [comment]
I have an incomplete Python generator in progress, but it’s not getting a lot of cycles.  Happy to push it publicly if there’s interest.

**Comment by da4089** [comment]
Also, see https://github.com/tfgm/sbedecoder

**Comment by shrishinde** [comment]
@da4089 thank.
I had seen that but I mainly need encoding part. Please publish you changes for python encoding I would like to try it out.

**Comment by shrishinde** [comment]
Currently I am using python `struct` module to try encoding but I am not sure if this is acceptable.
I have mentioned problem [here](https://stackoverflow.com/questions/48656706/convert-utc-timestamp-to-simple-binary-encoded-message)

**Comment by tmontgomery** [comment]
A python codec would be great to have. We would definitely welcome it!

**Comment by donmendelson** [comment]
Good news that SBE is garnering broad interest. 

Todd, does Real Logic have a means to test interoperability of the different implementations, or do you plan to do so?

**Comment by tmontgomery** [comment]
@donmendelson the C++ codec has a few unit tests that assert byte-by-byte layout according to the spec. It's not a full test suite, though. @mjpt777 and I have no current plans to do something like that at the moment. But would definitely have some thoughts on how it could be done.

**Comment by donmendelson** [comment]
@tmontgomery I did put together a conformance test in project [FIXTradingCommunity/fix-sbe-conformance](https://github.com/FIXTradingCommunity/fix-sbe-conformance) and used it to test interop of another SBE implementation with Real Logic. This was the proof needed to certify that the SBE version 1.0 standard had two interoperable implementations

The principle of the thing is to use one implementation to encode a buffer, then use the other implementation to decode it. Then it makes a round trip through another message type and compares values in the second message to expected values. Currently, the test is quite rudimentary. I welcome any contributions or ideas for improvement.

**Comment by mmcilroy** [comment]
I implemented basic Python support a few years ago but seems to have been lost along the way. Suspect a lot has changed since then. Here're my commits in case they are useful

https://github.com/real-logic/simple-binary-encoding/commits?author=mmcilroy

**Comment by billsegall** [comment]
>
> Todd, does Real Logic have a means to test interoperability of the
> different implementations, or do you plan to do so?
>

Both the Golang and C# backends have an interop test against a captured
Java byte array using the Car example for both little and big endian cases.
It's notexhaustive but it does test interoperability across quite a bit of
the spec.

Bill.

**Comment by tmontgomery** [comment]
@mmcilroy I think that your version eventually got too out of date as we changed things around. And so eventually got dropped when we did a cleanup. It could probably be resurrected, though.

**Comment by willguxy** [comment]
@tmontgomery @mmcilroy :+1: for resurrection.

**Comment by willguxy** [comment]
and I'd call for Python 3 support as well.

**Comment by kizzx2** [comment]
Here is a pure Python implementation that doesn't involve codegen https://github.com/kizzx2/sbe-python in case anyone finds it useful
