### ISSUE TITLE
Decoder.append(stringbuilder) to shift limit by the size of variable data 

### ISSUE THREAD

**Issue by anton-anufriev** [real-logic/simple-binary-encoding#542]
Decoder that has repeating groups with variable data does not shift the limit by the length of the data when appending to string builder. 

This causes the next row to start at the "length" field.

**Comment by anton-anufriev** [comment]
The append method only prints the length of the variable data but does not shift the limit as it is done in getXxxxx() method.

Xxxxx is a name of the variable data field.

**Comment by mjpt777** [comment]
Can you  provide an example and can you confirm the language used?

**Comment by anton-anufriev** [comment]
Hi Martin,
The language is java.

The test is  [here](https://github.com/anton-anufriev/sbe-append/blob/master/src/test/java/org/dev4fx/sbe/TestMessageEncodingTest.java) 

My fix is [here](https://github.com/anton-anufriev/sbe-append/blob/master/src/main/java/org/dev4fx/sbe/fix/TestMessageDecoder.java#L366)

Thanks,
Anton

**Comment by mjpt777** [comment]
Thanks. I was just pushing a fix as this arrived ;-)
