### ISSUE TITLE
Questions on meta attributes and Java generator

### ISSUE THREAD

**Issue by karypid** [real-logic/simple-binary-encoding#554]
Hi,

I noticed that the SBE generator creates a meta attribute method in both the encoder and decoder class in some cases, but not in others.

1) So my first question is: is there some conscious decision on when and where these methods are generated?

For instance looking at [the vanilla example schema](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml) you will see that the 3 data elements in the end of the message have meta attribute methods in both encoder and decoder:

```
        <data name="manufacturer" id="18" type="varStringEncoding" />
        <data name="model" id="19" type="varStringEncoding" semanticType="Automobile" />
        <data name="activationCode" id="20" type="varStringEncoding" />
```

The only interesting thing there is that the presence is required (not optional). At the same time however, fields of the message only have this method generated in the decoder class, even when using non-default presence, for example:

`        <field name="discountedModel" id="8" type="Model" presence="constant" valueRef="Model.C" />
`

...the above only has this method in the decoder class only:

```
    public static String discountedModelMetaAttribute(final MetaAttribute metaAttribute)
    {
        switch (metaAttribute)
        {
            case EPOCH: return "unix";
            case TIME_UNIT: return "nanosecond";
            case SEMANTIC_TYPE: return "";
            case PRESENCE: return "constant";
        }

        return "";
    }
```

2) Which also brings me to my second question: why does the method provide values for the EPOCH and TIME_UNIT meta attributes when they clearly are not applicable to discounted model?

The same happens for the attribute methods that are generated in both encoder and decoder for the 3 data elements: they always return for EPOCH and TIME_UNIT.

**Comment by mjpt777** [comment]
On point 1 there should have been symmetry and I've just fixed that. For point 2 it is historical. Those meta attributes where required in early revisions of the standard that were later dropped. We kept them from backwards compatibility.
