### ISSUE TITLE
Use multiple xml files?

### ISSUE THREAD

**Issue by noahtaylor** [real-logic/simple-binary-encoding#556]
Is it possible to use includes with sbe?  I want to have multiple schema that have some common types.  For example I want to have a common file that has the message header in it.  Then have to other files that use the same message header.  Is this possible?

**Comment by tmontgomery** [comment]
Sadly, not possible to do Xinclude and validate with schemas. https://stackoverflow.com/questions/1098116/xinclude-schema-namespace-validation

We chose to promote schemas and to not make this complicated by also supporting Xinclude. It would just make things very complicated configuration wise as well as be very error prone.

It's possible to use Xinclude and XSLT or just simple XML tools to build a complete XML file to feed to SbeTool that does not contain the Xinclude.

**Comment by noahtaylor** [comment]
Yeah ok.  Thanks for getting back to me!
