### ISSUE TITLE
Support for hierarchy of messages

### ISSUE THREAD

**Issue by puiuvlad** [real-logic/simple-binary-encoding#558]
Hi,

I have a two level hierarchy of objects: (1) the base level object contains some fixed length fields and some variable length fields; (2) the derived objects similarly contain some fixed length fields and some variable length fields.

One obvious but tedious way to generate codecs for my set of message types would be to create a schema where I repeat the base fields in every derived message, eventually changing the order of the fields to conform to the recommended pattern (fixed length fields first followed by variable length fields).

Is there any other way? Something like defining a base message type and specifying a hierarchy of messages in the schema, and generating a hierarchy of codecs? Do you have any examples?

Thanks,
Vladimir

**Comment by mjpt777** [comment]
Common fields can be grouped into a component and reused across messages.  See the use of the `Engine` in the `Car` example.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml#L44

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/example-schema.xml#L78

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java#L123

**Comment by puiuvlad** [comment]
Hi Martin, thanks for your reply. I have not seen an example where a composite has a reference to a String and I am not quite sure whether it's supported or not.

I tried this:
```
        <composite name="Base">
            <type name="pubType" primitiveType="int8"/>
            <type name="requestId" primitiveType="int64"/>
            <ref name="subject" type="varStringEncoding"/>
        </composite>
```

I was expecting my generated BaseEncoder class to have a subject(String) method similar to
```
   public CarEncoder manufacturer(final String value)
```
in your example code, but that does not seem to be the case.

Any suggestions?

Thanks,
Vladimir

**Comment by mjpt777** [comment]
Strings and var data are only allowed at the end of a message or repeating group. Therefore it would not be possible to do what you are suggesting even with inheritance. The [SBE specification](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) is strict on how messages can be laid out.

**Comment by puiuvlad** [comment]
Thanks Martin
