### ISSUE TITLE
suppress output of otf IrDecoder (c++)

### ISSUE THREAD

**Issue by hbcoba** [real-logic/simple-binary-encoding#559]
I am using the IR OTF decoder to get a readable ascii representation of SBE messages (c++ version). 
The IrDecoder.h currently does some output to std::cout, which makes it difficult to be used in a command line tool: our tool is meant to only output the ascii message representation and nothing else (to be usable in combination with classic text processing tools like sed, awk, grep, etc).

I would suggest to remove any output of IrDecoder or at least make it optional.

**Comment by mjpt777** [comment]
I agree this would make sense. @tmontgomery any reason for the output to be in there?

**Comment by tmontgomery** [comment]
No reason other than debugging.

**Comment by hbcoba** [comment]
Great, thank you!
