### ISSUE TITLE
Specifying constants on messages

### ISSUE THREAD

**Issue by darthninja1** [real-logic/simple-binary-encoding#561]
In reference to this [issue ](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/64#issuecomment-395421281) on the FIX SBE project. I get an error when I specify a constant in a message as - 

>         <field id="4"  name="constant4"  type="uint8"    presence="constant">1</field>

> Exception in thread "main" java.lang.IllegalStateException: type is not of constant presence
> 	at uk.co.real_logic.sbe.xml.EncodedDataType.constVal(EncodedDataType.java:295)
> 	at uk.co.real_logic.sbe.xml.IrGenerator.add(IrGenerator.java:472)
> 	at uk.co.real_logic.sbe.xml.IrGenerator.addAllFields(IrGenerator.java:184)
> 	at uk.co.real_logic.sbe.xml.IrGenerator.generateForMessage(IrGenerator.java:84)
> 	at uk.co.real_logic.sbe.xml.IrGenerator.generate(IrGenerator.java:60)
> 	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:199)

I am using release 1.8.1. Let me know if there are plans to support this in a future release?

Thanks

**Comment by mjpt777** [comment]
This is not valid XML given the 1.0 release schema and thus not currently supported.

We may support 2.0 if someone is willing to sponsor the development.
