### ISSUE TITLE
Is null value in line with the specification?

### ISSUE THREAD

**Issue by karypid** [real-logic/simple-binary-encoding#562]
Hello,

I have noticed that SBE tool always creates a null value in enumerations, using the maximum value of the encoding (255 for uint8, 65535 for uint16 - presumably because these are the default null values for these encoding types).

[The specification does not mention anything about enumerations being optional and what their null value should be](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v2-0-RC1/doc/04MessageSchema.md#enumeration-encodings) (there are no presence or nullValue attributes there).

In fact, there is even [an example of required and optional boolean fields, using enumeration encodings where it is shown that the presence should be handled at the field level](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v2-0-RC1/doc/02FieldEncoding.md#boolean-encoding).

As another note, if I define a valid value for implicit null that SBE tool introduces, those collide. This:

```
        <enum name="t_enum_uint16" encodingType="uint16">
            <validValue name="A16">0</validValue>
            <validValue name="B16">256</validValue>
            <validValue name="C16">65535</validValue>
        </enum>
```

Generates this (Java):

```
public enum T_enum_uint16
{
    A16(0),

    B16(256),

    C16(65535),

    /**
     * To be used to represent not present or null.
     */
    NULL_VAL(65535);
```

EDIT: opened clarification request on specification side at https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/85

I think specification should make it illegal to use an encoding type whose null value collides with any of the enumeration's valid values. Then SBE tool can safely pick the null value from the encoding type for the "extra entry".

Hoewever, if the encoding type has "presence=required" the null value should NOT be added at all by SBE tool: it should not create the illusion of an optional enum in that case.

**Comment by mjpt777** [comment]
As fields can be optional then all types must support some sort of null value to be consistent. I've found there are numerous inconsistencies in the SBE spec when trying to implement it. The presence being on both type and field makes for a bit of a mess here. The null value needs to be provided in the type if any field can possibly be null. We also optionally generate an unknown type to support the issues that versioning can bring up. Throwing exceptions can raise performance issues due to compiler optimisation restrictions.

Feel free to sponsor work in this area if you would like to see it improved or offer a PR.

**Comment by karypid** [comment]
I am trying to implement a code generator but with a non-XML input (i.e. an open source DSL specifically for SBE) and ran into quite a few ambiguities.

In the 2.0 release candidate, the presence and null value have been removed from types and are only specified at the field level and in composites. That would make picking up the null value and presence from the type impossible (presence null are illegal there).

**Comment by mjpt777** [comment]
I know. I was the one that suggested it.

**Comment by karypid** [comment]
So you are saying you want to revisit this and have presence/null associated with types?

**Comment by mjpt777** [comment]
No

**Comment by karypid** [comment]
The 2.0 schema now defines simple types as:

```
	<xs:complexType name="simpleDataType">
		<xs:simpleContent>
				<xs:extension base="xs:token">
				<xs:attribute name="name" type="sbe:symbolicName_t" use="required"/>
				<xs:attribute name="description" type="xs:string"/>
				<xs:attributeGroup ref="sbe:primitiveTypeAttributes"/>
				<xs:attributeGroup ref="sbe:versionAttributes"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:attributeGroup name="primitiveTypeAttributes">
		<xs:attribute name="primitiveType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="char" />
					<xs:enumeration value="int8"/>
					<xs:enumeration value="int16"/>
					<xs:enumeration value="int32"/>
					<xs:enumeration value="int64"/>
					<xs:enumeration value="uint8"/>
					<xs:enumeration value="uint16"/>
					<xs:enumeration value="uint32"/>
					<xs:enumeration value="uint64"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="double"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="length" type="xs:nonNegativeInteger" default="1"/>
		<xs:attribute name="characterEncoding" type="xs:string" />
	</xs:attributeGroup>
```

I was also told that length and characterEncoding only apply to the 'char' type.

Does simple type then even make sense anymore?  I can not see a reason to define a simple type other than to define a new fixed-length character array. The purpose of the version attributes is to track when each character array flavor was added?

**Comment by mjpt777** [comment]
Length did, and I assume still will, apply to all as it represents an array, e.g. an array of ints which is useful. characterEncoding only makes sense for char where char is a single byte type as variable length would not make sense.

Version is for when the type was added.
