### ISSUE TITLE
C++17 constexpr

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#573]
Hello devs!

C++ generated code is looks like `constexpr` friendly. Only need to fix constructors to initialize all members. So, is it possible to add `SBE_CONSTEXPR` for each function in generated class?

Thanks

**Comment by tmontgomery** [comment]
Sorry for the delay, I did not see any indication of this issue.

This might be possible. Worth checking out with Visual Studio to make sure it doesn't break anything.
