### ISSUE TITLE
How can I generate sbe/sbe.h

### ISSUE THREAD

**Issue by tanaynv** [real-logic/simple-binary-encoding#577]
I have used to sbe tool to generate cpp code. All the generated files have the include directive: "#include <sbe/sbe.h>" but that file has not been generated. How can I generate that file as well?

**Comment by mjpt777** [comment]
They are not generated. You can find them in the [repo](https://github.com/real-logic/simple-binary-encoding/tree/master/sbe-tool/src/main/cpp/sbe) or bundled into the sbe-tool.jar.
