### ISSUE TITLE
sbe-tool/src/main/cpp/CMakeLists.txt uses "java" and not the java found earlier in the build process

### ISSUE THREAD

**Issue by mattgodbolt** [real-logic/simple-binary-encoding#579]
I have `JAVA_HOME` set, but `java` is not on my path. The CMake process correctly finds java:

```
-- Found Java: /opt/jdk1.8.0_181/bin/java (found version "1.8.0_181") 
```

but later on, assumes `java` is on the path:

```
/bin/sh: 1: java: not found
sbe-tool/src/main/cpp/CMakeFiles/ir_codecs.dir/build.make:57: recipe for target 'sbe-tool/src/main/cpp/CMakeFiles/ir_codecs' failed
```

I believe this is due to https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/cpp/CMakeLists.txt#L19 just using `java` and not a CMake variable found with `find_executable` or similar.

The workaround is to path up the java version also specified in JAVA_HOME.

**Comment by tmontgomery** [comment]
Good call. Will have to check into what the find package exports.

**Comment by mattgodbolt** [comment]
It seems the benchmarks are the source of the "Found Java" part:

```
sbe-benchmarks/src/main/cpp/CMakeLists.txt
```

mentions it and seems to use `Java_JAVA_EXECUTABLE` (which might be the right way to do this - I'm definitely no CMake expert!)

Thanks for the quick response!

**Comment by tmontgomery** [comment]
Yes. Looks like `Java_JAVA_EXECUTABLE` from https://cmake.org/cmake/help/v3.5/module/FindJava.html

**Comment by tmontgomery** [comment]
I pushed this change. 7b3420e0 see if it works for you if you can. Thanks!

**Comment by tmontgomery** [comment]
Looks like either I missed this when I was cleaning some things up.... or it got changed at one point back to using java directly.

**Comment by mattgodbolt** [comment]
Thanks for the super fast response @tmontgomery :) Confirmed fixed!

**Comment by tmontgomery** [comment]
Sweet! Thanks!
