### ISSUE TITLE
No `install` target in CMakefiles

### ISSUE THREAD

**Issue by mattgodbolt** [real-logic/simple-binary-encoding#580]
I'm trying to integrate SBE into a [conan](https://conan.io) project, and I'm using the usual scaffolding for CMake<->conan. That relies on there being an install step, which there isn't for SBE:

```$ make install
make: *** No rule to make target 'install'.  Stop.
```

It would be great to support installing to a prefix directory (`CMAKE_INSTALL_PREFIX`) to help integration with other tools.

**Comment by tmontgomery** [comment]
👍 Agreed. Need to add this. I'll take a shot at it soon.

**Comment by mattgodbolt** [comment]
No worries; thanks for the quick reply! I'd issue a PR but I'm still learning what bits of SBE should be part of the install (by trying to import it into another project, so I might find out enough to be confident!)

**Comment by tmontgomery** [comment]
No worries. It has very little to install. A few headers is all, I think, since the tool is in Java.

**Comment by dxwu88** [comment]
When I used SBE-Tool-1.6.1 to generate C# code, it gave me error message. Could anyone help me on this? Thanks!

**Comment by tmontgomery** [comment]
@dxwu88 going to close this issue. If you add an issue with your error maybe someone will take a look. But this issue is not the correct place for the issue.
