### ISSUE TITLE
Common message parts in different projects

### ISSUE THREAD

**Issue by puiuvlad** [real-logic/simple-binary-encoding#581]
Hi,

Here is my use case: 

Project A defines a set of messages with a common base (BasePub is a <types><composite> that is referenced in every <sbe:message> object in project A).

Project B which depends on A and uses the objects defined in A adds new messages that have the same base BasePub. Project A does not need to be aware of Project B objects, and project B need only be aware of the 'common' objects.

Is there a way to generate the objects of project B without copying all the common objects from project A in B's schema? (It appears that the SBE tool is able to generate codecs from a single schema.xml file.) 

Thanks,
Vladimir

**Comment by mjpt777** [comment]
Unfortunately this is how the specification is defined. Version 2.0 is close to being ratified. It would be worth you voicing your requirements to the spec committee. https://github.com/FIXTradingCommunity/fix-simple-binary-encoding
