### ISSUE TITLE
Allowed primitive types for Exchange semantic type

### ISSUE THREAD

**Issue by RFrenkel** [real-logic/simple-binary-encoding#590]
Happy Friday everyone.

Wandering if Exchange semantic type is limited only to either 4 byte fixed string primitive type (MIC) or enumeration type.

Can it be used with 8 byte string primitive type if the values supported by the feed are not MICs, but exchange or venue names (ex. CME instead of 'XCME')

Example from SBE spec:
type name="EurexMarketID" semanticType="Exchange" primitiveType="char" length="4" description="MIC code" presence="constant">XEUR</type

field type="EurexMarketID" name="MarketID" id="1301" / 
"
Proposed option:
type name="MarketID" semanticType="Exchange" primitiveType="char" length="8" description="Exchange, venue name"></type

field type="SecurityExchange" name="MarketID" id="207" /

**Comment by mjpt777** [comment]
Semantic Type is a FIX thing. See the spec for how it is used. Best to ask questions about it on that repo.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/02FieldEncoding.md
