### ISSUE TITLE
Unused field in flyweight cpp

### ISSUE THREAD

**Issue by kdoherty2** [real-logic/simple-binary-encoding#596]
SBE Tool v1.7.9

Problem:
 Message with only fixed fields contain an attribute in the cpp encoder/encoder called `m_positionPtr` that is never used. This attribute taking up 8 bytes. We suggest to remove this for optimization.

Given the following schema: 
```
 <types>
 <enum name="EnumSBESample" encodingType="uint8" semanticType="EnumSBESample">
 <validValue name="a">0</validValue>
 <validValue name="b">1</validValue>
 </enum>
 </types>

<sbe:message name="MsgSBESample" id="1023" semanticType="MsgSBESample">
 <field name="fieldConstant" id="1" type="EnumSBESample" presence="constant" semanticType="EnumSBESample" valueRef="EnumSBESample.a" />
 </sbe:message>
```

Remove   `std::uint64_t *m_positionPtr;` that is not being read in the flyweight

```
class MsgSBESample
 {
 private:
 char *m_buffer;
 std::uint64_t m_bufferLength;
 std::uint64_t *m_positionPtr;
 std::uint64_t m_offset;
 std::uint64_t m_position;
 std::uint64_t m_actingBlockLength;
 std::uint64_t m_actingVersion;

inline void reset(
 char *buffer, const std::uint64_t offset, const std::uint64_t bufferLength,
 const std::uint64_t actingBlockLength, const std::uint64_t actingVersion)
{ m_buffer = buffer; m_offset = offset; m_bufferLength = bufferLength; m_actingBlockLength = actingBlockLength; m_actingVersion = actingVersion; *m_positionPtr = &m_position;* position(offset + m_actingBlockLength); } 
inline void reset(const MsgSBESample& codec)
{ m_buffer = codec.m_buffer; m_offset = codec.m_offset; m_bufferLength = codec.m_bufferLength; m_actingBlockLength = codec.m_actingBlockLength; m_actingVersion = codec.m_actingVersion; m_positionPtr = &m_position; m_position = codec.m_position; } 

```

**Comment by mjpt777** [comment]
Flyweights are by their nature used to flyweight over many other objects. This means that you typically only need one per thread per message type. If repeating groups, or var data, is used in a message then the `m_positionPtr` is required. This feels like an optimisation that would provide negligible benefit. Can you highlight where this optimisation would provide noticeable benefit?

**Comment by kdoherty2** [comment]
The low latency app that raised this issue seeks to eliminate all non-essential fields
for message with only fixed fields

**Comment by mjpt777** [comment]
That does not count as evidence that the effort to support this would make a noticeable difference. :-)

**Comment by mjpt777** [comment]
Closing as effort to address this is not likely to produce noticeable benefit yet would introduce complexity that may cause new issues.

**Comment by mjpt777** [comment]
Having looked at this some more, if the goal is to save on space, then a bigger win would be to adjust the types so that smaller types, e.g. for acting version and block length, could be used instead of only using the largest possible type in all cases.
