### ISSUE TITLE
For variable-length fields SBE forces the client to copy data to its own buffer

### ISSUE THREAD

**Issue by kdoherty2** [real-logic/simple-binary-encoding#600]
An example generated stub `MessageRejectedDecoder`

provides only

```java
public int getOriginalMessage(final MutableDirectBuffer dst, final int dstOffset, final int length)
```

and

```java
public int getOriginalMessage(final byte[] dst, final int dstOffset, final int length)
```

It requires the client to copy data into its own buffer. 

The SBE-generated stub could provide a convenient method to get a wrapped buffer view to the variable data field to prevent copying.

**Comment by vontikov** [comment]
Does it make sense to provide the getter for the private DirectBuffer?

**Comment by daabramoff** [comment]
This issue is Java-related

**Comment by tmontgomery** [comment]
A wrapper object will need to be passed in to use. Something like the following.

```
public void getOriginalMessage(final DirectBuffer bufferToWrap)
```

What this would do is call `bufferToWrap.wrap` and provide a view on the original buffer that includes just the field value so that the copy can be avoided (if desired).

**Comment by mjpt777** [comment]
A wrap method has been generated that allows a view unto the field.

```java
final DirectBuffer wrapBuffer = new UnsafeBuffer(); // can be retained to avoid allocation.

msg.wrapOriginalMessage(wrapBuffer);

final byte firstByteOfOriginalMessageMember = wrapBuffer.getByte(0);
final int originalMessageLength = wrapBuffer.capacity();
```
