### ISSUE TITLE
Message field id

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#608]
Hello devs,

Is `id` of `field` should be unique inside of a `message`? It's a restriction of SBE standard or restriction of the tool?

Thanks

**Comment by tmontgomery** [comment]
The spec requires the field ids must be unique within a message. More than that, it normally requires these to be equivalent to FIX tags in that they must be the same between messages. The implementation does not check for that, though.

**Comment by ksergey** [comment]
Thank you
