### ISSUE TITLE
Fixed length arrays of composites, enums, etc

### ISSUE THREAD

**Issue by kdkavanagh** [real-logic/simple-binary-encoding#612]
Is there a mechanism to specify a fixed length array of non-primitive types?  E.g I can declare an array of ints using `<type description="" length="10" name="IntArray" primitiveType="uint32"/>`, but I can't seem to find a way to represent an array of non-primitives, e.g `<ref description="" length="10" name="FixedArrayEnum" type="TestEnum"/>`

**Comment by mjpt777** [comment]
I believe only primitive types are supported for fixed length arrays under the [spec](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/02FieldEncoding.md). You may want to ask this question on the spec repo.
