### ISSUE TITLE
MaxValue for uint32 type validated against int32.max

### ISSUE THREAD

**Issue by kdkavanagh** [real-logic/simple-binary-encoding#615]
Checking to see if this validation implementation is intentional.  My expectation was that a uint32 max value would be checked against uint32.max, not int32.max

From CompositeType.java:
```java
            final long maxInt = INT32.maxValue().longValue();
            if (primitiveType == UINT32 && longValue > maxInt)
            {
                XmlSchemaParser.handleError(node, String.format(
                    "maxValue greater than allowed for type: maxValue=%d allowed=%d", longValue, maxInt));
            }
```

**Comment by kdkavanagh** [comment]
Guess based on the related generated code for dimension en/decoders that there is some requirement that both blockLen and numInGrp are always <= int32. 

Related to #609

**Comment by mjpt777** [comment]
This is correct. The spec recommends `UINT8` and `UINT16` for the types. We allow a bit of flexibility in going larger but given the limitations of the Java language we limit to max signed int.

**Comment by kdkavanagh** [comment]
SBE also enforces unsigned types for numInGrp.  Should this restriction be relaxed to allow 2^31 (int32) objects in a repeating group?  While semantically a signed count doesn't make a ton of sense, there is a big difference between 2^16 and 2^31

**Comment by mjpt777** [comment]
That is a question for the spec more so than this implementation.
