### ISSUE TITLE
variable length array

### ISSUE THREAD

**Issue by lapetiteclef** [real-logic/simple-binary-encoding#618]
I needed to add some variable length arrays. Noticed that only character and blobs was supported.
Still the declaration of types and reference works: for example:

	<composite name="varLong">
		<type name="length" primitiveType="uint8" />
		<type name="varData" primitiveType="int64" length="0" />
	</composite>
	<composite name="varInt">
		<type name="length" primitiveType="uint8" />
		<type name="varData" primitiveType="int32" length="0" />
	</composite>

Code generation works with the above example but the actual get/set methods are not generated, for example someTypeEncoder.variableName( long []data ). I checked the code and its just few lines missing in the Java generator. 

Looks like its a design/spec choice? I think it would be good to support primitive type arrays when generator already supports the parsing/generation of the types but without needed get/set methods.

Its possible to model around it with repeating groups. In our case the schema for some products starts to look a bit too complex with nested groups reflecting fields.

If possible I would have added it locally but our B2B customers are using a supplied SBE schema and default SBE generator. Is there any chance to add support this "almost already implemented" feature?

**Comment by mjpt777** [comment]
Only strings and binary blogs are supported under the spec. If you want to make a suggestion to improve the spec then do it [here](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding).
