### ISSUE TITLE
MetaAttribute enum

### ISSUE THREAD

**Issue by odeheurles** [real-logic/simple-binary-encoding#62]
I've just ported the MetaAttribute related functionality and I was wondering why we generate the enum in each class and not use a single, well known, enum?

I understand that the code generated to access the meta attributes of each field can differ  on a per field basis but the enum itself is always the same (at least for now).

Is there a good reason to generate a new enum for each class or could we actually use a single one?

**Comment by mjpt777** [comment]
Buffer choice now available as a system property.
