### ISSUE TITLE
Method For Setting Null Value in Required Fields

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#622]
Just a quick question regarding null values for required fields

For example if a timestamp field (uInt64) is specified with presence="required" then why is there a method for setting/getting null value for a required field? If a field is required then there should ideally be no setter method for setting a null value for it

Encoding:

public static long requestTimestampNullValue() {
  return -1L;
}

public static long requestTimestampMinValue() {
  return 0L;
}

public static long requestTimestampMaxValue() {
  return -2L;
}

public XXXXXXXXEncoder requestTimestamp(long value) {
  this.buffer.putLong(this.offset + 64, value, ByteOrder.LITTLE_ENDIAN);
  return this;
}
 
 
Decoder:

public static long requestTimestampNullValue() {
  return -1L;
}

public static long requestTimestampMinValue() {
  return 0L;
}

public static long requestTimestampMaxValue() {
  return -2L;
}

public long requestTimestamp() {
  return this.buffer.getLong(this.offset + 64, ByteOrder.LITTLE_ENDIAN);
}

**Comment by mjpt777** [comment]
Simplicity of code generation. Checking presence indicates if it is required rather than if a null value is defined.
