### ISSUE TITLE
namespace conflict c++

### ISSUE THREAD

**Issue by sfodor2** [real-logic/simple-binary-encoding#626]
Hello,
Generated classes use ::sbe::MetaAttribute, is it possible to use the namsepace given in -Dsbe.target.namespace? In my project i link to a library that also uses sbe and i get conflicts on enum sbe::MetaAttribute.

Thanks

**Comment by mjpt777** [comment]
We have considered generating the sbe.h for each project as an option.  Would your company be interested in sponsoring that work?

**Comment by tmontgomery** [comment]
This has now been added to the message class itself. Feel free to take a look.
