### ISSUE TITLE
Inconsistency in C++ array property accessors and mutators

### ISSUE THREAD

**Issue by denizevrenci** [real-logic/simple-binary-encoding#637]
https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1266

defines `put` for null-terminated strings and uses the size of the type multiplied by the array length as the total byte length for copying. 

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1254

Does the same for the accessor.

While the `std::string` and `std::string_view` versions

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1309

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1325

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1280

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java#L1291

only copy the length of the array in bytes.

I think we need to multiply with the size of the array elements in both cases.

Ideally, the c string versions could be called from the `std::string` and `std::string_view` versions to ensure common implementation.

**Comment by ksergey** [comment]
Is SBE spec describe size of char? `std::string` and `std::string_view` added only if field is array of chars.
There is a problem in bit compatibility in case of size of char not equal to 1

**Comment by denizevrenci** [comment]
Sorry, didn't notice the condition around the block. This issue can be disregarded.
