### ISSUE TITLE
libsbe.a in 1.12.0

### ISSUE THREAD

**Issue by wpgabriel** [real-logic/simple-binary-encoding#642]
In the past, when I've built the ccpbuild version, I'd get a lib/libsbe.a built in my project build directory. This was true through 1.11.0. When I build 1.12.0, I cannot find the library anymore. Did something change about the build process--do I need to change the way I build?

**Comment by tmontgomery** [comment]
The library has been changed into an interface negating the need for the dummy lib. It was never really needed. Was just cleaned up thanks to 28025368f8ebd5284e1e56aa5dbee381d6aac08e from @denizevrenci

**Comment by wpgabriel** [comment]
Got it, thanks. I linked to the library in the past, not realizing it was just a dummy lib. Took it out and compiled my project just fine.
