### ISSUE TITLE
IrDecoder::decode(char *buffer, std::uint64_t length) ignores function parameters.

### ISSUE THREAD

**Issue by jsarbakatmarketfactorydotcom** [real-logic/simple-binary-encoding#643]
I would like to use this decode method (listed below), however it ignores the provided buffer.  The subsequent call to decodeIr()  munges an m_buffer pointing to null memory.  

I don't want to have to call the file-based decode method.  

It's an operational hassle to have to reference an sbeir file everytime a tool needs it.  It would be much simpler if (c++ based) tools could simply reference the sbeir file contents that is embedded in the program.  But to do this, one must be able to pass an sbeir bytearray into a decode method that doesn't ignore it.

Would you please provide a way to pass in the buffer and length to the decode method?  Perhaps an overloaded version of decode will do.

Thank you.
Joe
   
 int decode(char *buffer, std::uint64_t length)
    {
        m_length = length;
        return decodeIr();
    }

**Comment by tmontgomery** [comment]
The method should now be usable.

However, you that realize that:
1. The SBEIR file must be generated for use by C++ anyway (as opposed to Java, which could get away without using a file and instead use the schema directly), and
1. That the `IrDecoder` object is meant to be reused between messages, etc. and should only need to be decoded once
