### ISSUE TITLE
C# Generated code - certain variables change constantly over time (possibly VS only?)

### ISSUE THREAD

**Issue by mdesorcy** [real-logic/simple-binary-encoding#645]
I've recently pulled and generated C# SBE code, and although it seemed to go well at first, there looked to be a serious issue, one that is more prevalent if the program is being debugged, but also exists when longer messages are being decoded. The issue even happens with the sample car program.

Over time, certain variables will change their values. This most commonly seems to be the Limit and Size variables within the main message object (i.e. 'car'), or the ActingBlockLength and Count variables within repeated groups (i.e. PerformanceFigures). The latter two in particular tend to result in either out-of-range-index exceptions or attempts to iterate too many or too few repeated groups.

Since I have not seen any other issues like this reported, it is possible that the issue may lie with my personal machine, how I generated the code, or with Microsoft Visual Studio. Screenshots and examples can be provided upon request.

**Comment by billsegall** [comment]
This feels like memory corruption which can result from things as simple as using freed memory as an example. Do you have a simple example program which exhibits this?

**Comment by mdesorcy** [comment]
An example program that was exhibiting this was the "car" sample that was included in the code generation. Doing any sort of debugging revealed the issue - even simply changing whether I was viewing local variables in decimal or hex form would cause the changes, which does indeed sound like memory corruption.

Running the entire program without any break points did allow the program to conclude without any crashes or errors in the data, but the returned size of the car object, 153, seems a little too big. But making even one breakpoint can result in erroneous data.

**Comment by billsegall** [comment]
I can't duplicate this. I've just:
* Taken a fresh checkout of head
* run gradle to generate csharpcodecs
* used visual studio community 2017 to build the car example
* stepped through the CarExample.cs:Car.Decode() function

153 would seem about right to me. The actual captured bytes from the Java Example are embedded in InteropTests.cs .

Are you using net45? Are you using VS? Which version? Are you pulling current head? Anything else in your environment I should know?

Bill.

**Comment by mdesorcy** [comment]
Sorry for the wait. The fact that you can't recreate it seems to indicate it's an issue with my machine, although I can't prove this at the moment.

I am using VS Community 2017 to build this. Although the car properties window reveals only a greyed-out Target framework box, the app.config file does reveal it is using an sku of of net45.

I tried running InteropTests.cs myself. Running it through all the way worked, but attempting a step-by-step debug caused the error again, this time crashing with the following error at the following line:
`var fuelFigures = Car.FuelFigures`

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=limit=213 is beyond capacity=211
  Source=SBE
  StackTrace:
   at Org.SbeTool.Sbe.Dll.DirectBuffer.CheckLimit(Int32 limit) in C:\Users\MDesorcy\Source\Repos\simple-binary-encoding\csharp\sbe-dll\DirectBuffer.cs:line 133
   at Baseline.Car.set_Limit(Int32 value) in C:\Users\MDesorcy\Source\Repos\simple-binary-encoding\csharp\sbe-generated\baseline\Car.cs:line 65
   at Baseline.Car.FuelFiguresGroup.WrapForDecode(Car parentMessage, DirectBuffer buffer, Int32 actingVersion) in C:\Users\MDesorcy\Source\Repos\simple-binary-encoding\csharp\sbe-generated\baseline\Car.cs:line 486
   at Baseline.Car.get_FuelFigures() in C:\Users\MDesorcy\Source\Repos\simple-binary-encoding\csharp\sbe-generated\baseline\Car.cs:line 455
   at Org.SbeTool.Sbe.Tests.InteropTests.InteropDecodeTest() in C:\Users\MDesorcy\Source\Repos\simple-binary-encoding\csharp\sbe-tests\InteropTests.cs:line 78

I will attempt to pull head again to see if that fixes the issue.

**Comment by JPWatson** [comment]
VS will evaluate fields if you're looking at them in the debugger and some fields will mutate values.
For example if VS evaluates the `Car.FuelFigures` field, `FuelFiguresGroup.WrapForDecode` will cause the Car's Limit to be bumped up:

 `_parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;`

It's only supposed to be called once but the debugger might call it multiple times, which will result in incorrect values.

```
public FuelFiguresGroup FuelFigures
{
    get
    {
        _fuelFigures.WrapForDecode(_parentMessage, _buffer, _actingVersion);
        return _fuelFigures;
    }
}


...

public sealed partial class FuelFiguresGroup
{
    private readonly GroupSizeEncoding _dimensions = new GroupSizeEncoding();
    private Car _parentMessage;
    private DirectBuffer _buffer;
    private int _blockLength;
    private int _actingVersion;
    private int _count;
    private int _index;
    private int _offset;

    public void WrapForDecode(Car parentMessage, DirectBuffer buffer, int actingVersion)
    {
        _parentMessage = parentMessage;
        _buffer = buffer;
        _dimensions.Wrap(buffer, parentMessage.Limit, actingVersion);
        _blockLength = _dimensions.BlockLength;
        _count = (int) _dimensions.NumInGroup;
        _actingVersion = actingVersion;
        _index = -1;
        _parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;
    }
...
```

**Comment by mdesorcy** [comment]
Hi JP

Your explanation does make sense. If VS debugger has the possibility of mutating fields like this, what would you recommend to debug SBE projects properly?

**Comment by JPWatson** [comment]
`Console.WriteLine` :)

**Comment by mdesorcy** [comment]
Alright. This still feels like an oversight for C# generation tools, so I will leave this open.

**Comment by billsegall** [comment]
I think this is safe to close
