### ISSUE TITLE
Build errors when running incremental build

### ISSUE THREAD

**Issue by aalmiray** [real-logic/simple-binary-encoding#652]
Running the command `./gradlew :sb-benchmarks:build` twice results in an error since the build was migrated from `4.10.3` to `5.2.1`.

Build scans:

 success: https://scans.gradle.com/s/rg3beefdz7jo4/
 failure: https://scans.gradle.com/s/6zckguqi3rb7s/

Workaround:
Run `./gradlew clean :sb-benchmarks:build` with local build cache enabled to mitigate waiting times.

 1. create a file named `gradle.properties` at the root of the project.
 2. add the following content

    org.gradle.daemon  = false
    org.gradle.caching = true

Disabling the Gradle daemon also seems to work.

**Comment by mjpt777** [comment]
Thanks for the help @aalmiray.
