### ISSUE TITLE
[C#] Length of var data cannot be queried

### ISSUE THREAD

**Issue by EddPorter** [real-logic/simple-binary-encoding#660]
It is not currently possible to determine the length of a variable sized field outside of the generated class. This makes it hard (impossible?) to allocate a byte[] of the correct size to hold the extracted data. Worse still, even though the "Get" method will return the number of bytes read, you can't loop on it with increasing buffer size as the _parent.Limit is updated on the first call. You'd have to reinstantiate the class and start from the beginning.
The only alternatives I can think of are
* using the HeaderSize field to determine the number of bytes used to store the length and allocating a (potentially) large array to hold the maximum data size
* allocating another array the size of the message, minus the sum of the fixed length fields and headers - this gets less accurate with multiple variable sized fields.

**Comment by mjpt777** [comment]
The Java implementation generates a method to query the length when the C# could also do.

**Comment by EddPorter** [comment]
Alternatively, could the `Get` method could allocate the array of the correct size and just return it?

**Comment by billsegall** [comment]
I think adding a ```...Length()``` method makes sense.

Adding a Get that performs the allocation also make sense. Is a ```Span<byte>``` return desirable?

Bill.

**Comment by EddPorter** [comment]
The Get would have to allocate a `byte[]` anyway, so could just return that. My understanding of `Span<>` is that is allows windowing onto an underlying array. Would the Get allocate a new array (in which case just return it) or wrap the `Span<>` around the underlying array?
