### ISSUE TITLE
Null value decoding in java

### ISSUE THREAD

**Issue by SamBarker** [real-logic/simple-binary-encoding#669]
I'm trying to write an SBE implementation of at least a subset of the OpenRTB 2.5 specification [pdf](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf) in an attempt to replace a JSON based implementation. 

To make the SBE and JSON encoded messages equivalent I need to encode and decode null values for String fields. However I can't see an effective way in the generated java classes to detect a null string. A sample generated decoder looks like:

```java
public String bidId()
    {
        final byte[] dst = new byte[36];
        buffer.getBytes(this.offset + 36, dst, 0, 36);

        int end = 0;
        for (; end < 36 && dst[end] != 0; ++end);

        return new String(dst, 0, end, java.nio.charset.StandardCharsets.US_ASCII);
    }
```

Which when encountering a null value in the buffer will call `new String` with an end value of `0` which produces an empty but not null String. 

Patching the java generator to add

```java
if(end == 0 && dst[0] == bidIdNullValue()) {
    return null;
 }
```
before the return `new String(...)`

Is fairly simple but that causes tests to fail as now its impossible to distinguish between `null` and an empty string in the decoder.

Is there a better way to distinguish the two cases? Or to detect `null` values in the message?

**Comment by mjpt777** [comment]
This is an issue with the SBE specification. I pointed this out early on and was argued down. They argue that there is no difference between and empty string and null which I don't agree with. A negative value for length could have indicated null. Same issue exists with repeating groups. You could take it up with the maintainers of the specification. https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

**Comment by mjpt777** [comment]
@domejan Null value checks on members which have semantic support for null could be added. We would happy take a PR or sponsorship to do it. Regarding changes to the spec, this is not the right place to have that discussion as I have pointed out above.
