### ISSUE TITLE
Can one XML depend on another XML?

### ISSUE THREAD

**Issue by lsingal** [real-logic/simple-binary-encoding#671]
The SBE depends on XML file to generate the encoder and decoders. Can we define another XML which has some common definition  being used in the original XML. This will help to avoid writing same message types used my multiple services.

**Comment by mjpt777** [comment]
Yes see this example.

https://github.com/real-logic/simple-binary-encoding/tree/master/sbe-samples/src/main/resources

**Comment by lsingal** [comment]
Thanks. Thats helpful.
