### ISSUE TITLE
[C++] Encoding double/float

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#672]
Hello,

There is no way to check field represent null value in generic way in case of `double` (and may be `float`, not checked)  type (because https://godbolt.org/z/OeQpL5).

I mean code below is not working for doubles
```c++
if (msg.price() == msg.priceNullValue()) {...}
```

Will be good to have in generated code something like:
```c++
if (msg.priceIsNull()) { ... }
```

Where `priceIsNull()` is:
```c++
// In case of null value is std::numeric_limits<double>::quiet_NaN();
return std::isnan(price());
// and otherwise
return price() == priceNullValue();
```

Thanks

**Comment by tmontgomery** [comment]
I think this needs to be left to the application to do appropriately. In Java and in C++, the use of IEEE-754 means `Float.isNan` as well as `std::isnan` is required if NaN is in play. This is more of an SBE spec issue, I think.... maybe @mjpt777 has a different view, though.

**Comment by tmontgomery** [comment]
BTW, according to IEEE-754, you can always test for nan via testing against itself. `x != x`....

**Comment by mjpt777** [comment]
I agree with @tmontgomery that is is more a spec issue and we leave it to the application to do the appropriate thing. `NaN` is one issue but also comparing floating point in general for equality is an issue. The application should consider comparing the difference between numbers to an epsilon.  There is `FLT_EPSILON` and `DBL_EPSILON` defined for C++ which you could consider. 

http://www.cplusplus.com/reference/cfloat/

Maybe start a discussion on the spec and if there was an agreed approach then we could support that along with other implementations. https://github.com/FIXTradingCommunity/fix-simple-binary-encoding
