### ISSUE TITLE
FIX SBE decoder, with C++ - missing data

### ISSUE THREAD

**Issue by MiguelAngelArnedo** [real-logic/simple-binary-encoding#680]
I have done a FIX SBE decoder, with C++

Unfortunately I am missing decoding some data, and can not figure out where the problem is. Could anyone help by directing me to a helpful and nice :) person to whom I could share my code ?

Thank you !

**Comment by MiguelAngelArnedo** [comment]
Thank you so much for your answer. I do understand. I might consider the
consulting services. Let me explain you shortly:

 I have bin files that correspond to FIX messages. They were coded by
someone else, whom I can not reach anymore... I do believe that my C++ FIX
decoder should work quite well, however it expects the Message Header at
the very first byte if this bin file, as it should (?). This bin file comes
with a payload before, I am afraid, because my decoder does not read
correctly this header. Would it be a possible way to distinguish from which
offset the FIX message does begin ?

 Thanks,
Miguel Arnedo

Il giorno mer 8 mag 2019 alle ore 14:37 Martin Thompson <
notifications@github.com> ha scritto:

**Comment by mjpt777** [comment]
Without sample data, SBE schema, and the code it is difficult to judge.

**Comment by donmendelson** [comment]
@MiguelAngelArnedo it sounds to me like the issue is about framing of messages. SBE protocol does not provide message delimiters. Rather, communications (or reading messages from a file) depends upon another layer to do that. For example, WebSocket is a framing protocol. On a TCP stream, you need a message delimiter such as [FIX Simple Open Framing Header](https://www.fixtrading.org/standards/fix-sofh/) (SOFH). The small header just gives the size of the message and a code for encoding type so the correct number of bytes can be turned over the appropriate decoder.

**Comment by billsegall** [comment]
Can you send me one of the .bin files?

Bill.

**Comment by MiguelAngelArnedo** [comment]
Hi Bill and Martin,

Thank you very much... it is a big .bin file, however the smaller that I
could find among all I have.

 Attached hereafter the zip, with:

1) the code: histMktDataGen/dev/src/histMarket.cpp

The function of interest where the decoding begins is
decodeSymbol_fromBinaryFile(). And the most reliable function that is being
called afterwards is decode_MDIncrementalRefreshBook32(). Please ignore the
rest of the code (which basically selects the appropriated bin file, based
on a list of trading symbols and channels). Each binary file belongs to a
trading channel.

2) and one sample of binary file, within the data folder. As we stated, the
first thing to kindly verify is the format/contents of the .bin file

 histMktDataGen.zip
<https://drive.google.com/file/d/1MmTYCAPu2Gq0orzWuIdbeB0OF0N6v2R-/view?usp=drive_web>
  If you think you could fix it, please kindly let me first know your
conditions.

 Thank you,
Miguel ArnedoBill

Il giorno sab 11 mag 2019 alle ore 01:34 Bill Segall <
notifications@github.com> ha scritto:

**Comment by MiguelAngelArnedo** [comment]
Bill and Martin,

 I hope you are doing great. Might I kindly ask if you had to time to take
a look to the binary file ?

 Thank you,
Miguel


Il giorno mar 14 mag 2019 alle ore 12:48 Miguel Ángel Arnedo <
arnedo.miguelangel@gmail.com> ha scritto:
