### ISSUE TITLE
help using Rust generator for streaming input

### ISSUE THREAD

**Issue by ian-p-cooke** [real-logic/simple-binary-encoding#684]
I just downloaded the project and am running through the Rust example but I've hit upon a problem:  if you're reading a stream of data and you don't know what the type of each message is going to be then how do you start decoding it?  the `start_decoding_` methods assume you know what type you'll be decoding.  

What I'm imagining is that you'd read the header first, look at the template_id, and the call the decoder for that.  But `ScratchDecoderData` is private and the `wrap` methods are private so there's not much you can do except look at the buffer without decoding it, get the templateid, and then decode from the same place.  That seems clunky.

Any suggestions?

I think what I want is something like:
```Rust
let (header, remaining) = start_decoding_message_header(&buffer)?;
match header.template_id {
   CarMessageHeader::TEMPLATE_ID => {
      let car = CarFieldsDecoder::wrap(remaining);
     //process car
   },
   _ => panic!("unknown template_id!");
}
```

note that I'm also imagining that the block_length, template_id, schema_id, and version would be added as associated constants.

**Comment by ian-p-cooke** [comment]
#685 are what I was thinking of.  does that make sense?

**Comment by mjpt777** [comment]
The Rust codec seems close to abandoned. I was considering removing it to avoid confusion. If someone is willing to properly maintain it I'd be happy for it to remain. Is @dm3 or @ZackPierce still interested in it?

**Comment by dm3** [comment]
According to the Rust mailing list [thread on SBE](https://users.rust-lang.org/t/zero-cost-abstraction-frontier-no-copy-low-allocation-ordered-decoding/11515/9) @ZackPierce doesn't have the resources to maintain the codec. I don't plan to enhance it further either. The decoder works for my use cases as it is right now.

If the Rust codec isn't good enough quality to keep in the SBE tree we should probably keep it somewhere else as it's at least a working implementation. Can be useful as a starting point to someone else interested in writing a better or enhancing the current version.

**Comment by mjpt777** [comment]
Is this OK to close now?

**Comment by ian-p-cooke** [comment]
Yes, #685 closes this issue.  feel free to @ me on issues regarding the Rust codec.  I can't be an official maintainer but I'm happy to help if I have time.
