### ISSUE TITLE
[C++] Fixed length string reset method

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#686]
Hello Devs!

For non-array types I can write:
```c++
msg.setValue(msg.valueNullValue());
```
But there is no way to write the same one-liner for array types. Will be good to see in generated code something like that:
```c++
Msg& resetValue() { ... }
```
or 
```c++
Msg& fillValue(char value) { ... }
...
msg.fillValue(msg.valueNullValue());
```

Thanks

**Comment by tmontgomery** [comment]
There is a means to set an array property via an array. For example, from the Car schema.
```cpp
Car &putSomeNumbers(const char *const src) SBE_NOEXCEPT
```

Making a constant/static/etc. that is based on the null value is pretty easy. So, not sure generating a specific call to set NULL values is needed.

Alternatively, it is easy to set each element via.
```cpp
Car &someNumbers(const std::uint64_t index, const std::uint32_t value)
```

While that is not easy, it does allow for the use case you want (fluent API to grab NULL value and set).

**Comment by ksergey** [comment]
I found solution for myself:
```
msg.value(0, msg.valueNullValue());
```
I think It will be enough to decoding strings on other side via `getValueAsString`/`getValueAsStringView`.

**Comment by tmontgomery** [comment]
Will work for US-ASCII and UTF just fine. Or should. Other encodings might work if the NULL is setup as well.

Glad you found something that works for you.
