### ISSUE TITLE
[C#] Generated code for Acting Version doesn't always compile.

### ISSUE THREAD

**Issue by JulianBirch** [real-logic/simple-binary-encoding#687]
Issue found in 0.1.8.1-beta-1

The generated code can contain lines such as

```cs
if (_actingVersion < 10) return null;
```

If this is generated for an enum, it fails to compile. (The line is also incorrectly indented, but that's not a crisis.)

This can be easily fixed in more recent versions of C# by instead generating
```cs
if (_actingVersion < 10) return default;
```

which works for classes and structs, or 
```cs
if (_actingVersion < 10) return 0;
```

for structs only on older versions of C#.

**Comment by billsegall** [comment]
Julian,

That sounds logical. Do you have some example xml?

Bill.

**Comment by mjpt777** [comment]
@JulianBirch Can you please follow up with an example schema to demonstrate the issue?

**Comment by mjpt777** [comment]
Closing as no reproducer has been provided.
