### ISSUE TITLE
Is presence=optional inferred when using sinceVersion?

### ISSUE THREAD

**Issue by jiteshvassa** [real-logic/simple-binary-encoding#691]
In the context of adding a new field, the Message Versioning documentation (https://github.com/real-logic/simple-binary-encoding/wiki/Message-Versioning) states:

> The new field should have its sinceVersion attribute set to be the version number that has been used for the new schema and its presence=optional attribute set.

I understand that newly added fields can only be optional.  I was therefore thinking that if sinceVersion was set on a field, then by definition that field must be optional.  I was wondering whether it was therefore a hard requirement to add "presence=optional" to the schema given that this can be inferred?

**Comment by mjpt777** [comment]
It is a hard requirement however it is not easy to enforce with the XSD 1.0. I think it is better to be explicit than have "magic" behaviour applied implicitly.

**Comment by jiteshvassa** [comment]
Thanks for the clarification.
