### ISSUE TITLE
[C#] Groups do not implement IEnumerable<T>

### ISSUE THREAD

**Issue by JulianBirch** [real-logic/simple-binary-encoding#694]
They implement .NET 1.0 IEnumerable, and the code to implement (.NET 2.0) IEnumerable<T> is the same. The work-around is simple, just add in the correct implementation in the partial class, but I thought it worth logging.

**Comment by damageboy** [comment]
I understand your need, but honestly, I feel that for high perf code like this, it is completely an anti-pattern, given that providing this incurs an allocation by definition.

Do you think that from an API design standpoint, SBE generated code should encourage this sort of usage?
