### ISSUE TITLE
How do you build this code?

### ISSUE THREAD

**Issue by turk182** [real-logic/simple-binary-encoding#696]
Sorry, I am kind of new to GitHub and don't know exactly how you ask questions about a repo. I download this SBE repo, load it into Intellij and try to build. I get this error: error: - Error fetching URL: https://static.javadoc.io/org.agrona/agrona/1.0.3/ Any ideas on how to solve this build error?

**Comment by mjpt777** [comment]
Try building on the command line first. https://github.com/real-logic/simple-binary-encoding#build

Why do you need to build rather than use it as a dependency pulled from Maven Central?

**Comment by turk182** [comment]
Again I am new to GitHub, a big thanks for marking my post as a question and responding to it! I will try building from the command line and see how that goes. (I guess I have become an IDE guy.) I loaded the project in the IDE and click build and let the tool do the work. It is in the build.gradle file where the dependencies on Agrona is specified:

 dependencies {
        checkstyle 'com.puppycrawl.tools:checkstyle:8.22'

        **compile 'org.agrona:agrona:1.0.3'**
        
        testCompile 'org.hamcrest:hamcrest:2.1'
        testCompile 'org.mockito:mockito-core:2.28.2'
        testCompile 'junit:junit:4.12'
    }

Is there a way I can set this up as a dependency rather than compile it? Thanks for the help!

**Comment by mjpt777** [comment]
This is not a GitHub thing.  Gradle will fetch it dependencies and cache them locally. Your IDE should be able to do that. If you have imported into IntelliJ IDEA for example you will see the gradle pull out on the left. Click on it and then click the rebuild icon (circular arrows) and it will build. If you are using another IDE then do whatever that IDE requires to do a full build, i.e. not just a compile.

I'm going to close this as this is a basic development question and not related to SBE.

**Comment by turk182** [comment]
Got it built, thanks for the help!
