### ISSUE TITLE
Adding new field varDataEncoding to a existing message

### ISSUE THREAD

**Issue by johnny-yue** [real-logic/simple-binary-encoding#701]
Hi,

I wanted to extend an existing SBE structure by adding a varDataEncoding.
It does not compile when I put presence="optional" there, so the following is what i have now.
It seems to be working, my application can run new version of the schema to read old messaged encoded by the previous version. 

However, print message tools I wrote using SBE OTF tools do not work properly. It always says decode error, when reading old messages.

Is this supported behavior?

<sbe:message name="Car" id="1">
        <field name="car_id" id="2" type="uint32"/>
        <field name="owner" id="3" type="Text32"/>
        <group name="records" id="4" dimensionType="groupSizeEncoding">
            <field name="recordid" id="5" type="uint32"/>
            <field name="timestamp" id="6" type="uint64"/>
        </group>
        <data name="info" id="10" type="varDataEncoding" sinceVersion="1"/>
    </sbe:message>

**Comment by mjpt777** [comment]
SBE 1.0 does not support optional var-data or group members. I argued for this but was voted down by the committee. Their argument is that a var-data member with a length of 0 is sufficient which I do not agree with. SBE 2.0 supports extension by variable length members. [SBE Spec](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding)
