### ISSUE TITLE
Java String encoding doesn't take ByteOrder into account

### ISSUE THREAD

**Issue by yoran112** [real-logic/simple-binary-encoding#706]
See below code fragment, generated by SBE for .

value.getBytes always return the result in BigEndian and adds a byte order mark, even if the ByteOrder in the SBE xml file is set to LittleEndian.

It could be fixed by adding the byteOrder as a parameter to the getBytes method:
`value.getBytes(byteOrder == ByteOrder.LITTLE_ENDIAN ? UTF_16LE : UTF_16BE);`

When using java.nio.ByteOrder the try-catch can also be removed.

```java
public XxxCommandEncoder myString(final String value)
    {
        final byte[] bytes;
        try
        {
            bytes = value.isEmpty() ? org.agrona.collections.ArrayUtil.EMPTY_BYTE_ARRAY : value.getBytes("UTF-16");  //This is incorrect!!
        }
        catch (final java.io.UnsupportedEncodingException ex)
        {
            throw new RuntimeException(ex);
        }
        final int length = bytes.length;
        if (length > 64)
        {
            throw new IllegalStateException("length > maxValue for type: " + length);
        }
        final int headerLength = 1;
        final int limit = parentMessage.limit();
        parentMessage.limit(limit + headerLength + length);
        buffer.putByte(limit, (byte)length);
        buffer.putBytes(limit + headerLength, bytes, 0, length);

        return this;
    }
```

**Comment by mjpt777** [comment]
For var data this should work fine as when not specifying byte order UTF-16 allows for a BOM (Byte Order Mark) to be used in the first word to indicate byte order.

https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html#UTF_16
