### ISSUE TITLE
Question: What would the XPath for  XmlSchemaParser be to get the comments in the file?

### ISSUE THREAD

**Issue by turk182** [real-logic/simple-binary-encoding#711]
I see the XmlSchemaParser uses an XPath to get desired nods in the XML schema file. I am trying to get the 'comment' nodes in my XML file and have not found the correct XPath. So for example, to get the messages nodes the code does:

 public static final String MESSAGE_XPATH_EXPR =
        "//*[local-name() = 'message']";
...
forEach((NodeList)xPath.compile(MESSAGE_XPATH_EXPR).evaluate(document, XPathConstants.NODESET),
            (node) -> addMessageWithIdCheck(distinctNames, messageByIdMap, new Message(node, typeByNameMap), node));

I have tried many XPaths like:

public static final String COMMENT_XPATH_EXPR =
        "//*[local-name() = 'comment']";

or

"//*[local-name() = 'comment()']";
"//comment()";
...

Any ideas what the correct XPath would be to get the comment nodes?

Thanks.

**Comment by turk182** [comment]
I found a solution: this code seems to work:

 String COMMENT_XPATH_EXPR =
                "//comment()";
     
        forEach((NodeList)xPath.compile(COMMENT_XPATH_EXPR).evaluate(document, XPathConstants.NODESET),
                (node) -> System.out.println("!! Node:" + node.toString() + ' ' + node.getNodeValue() + ' '));

**Comment by mjpt777** [comment]
This has nothing to do with SBE. Please direct to an appropriate XML/XPath source.
