### ISSUE TITLE
[C++] JSON serialization

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#718]
Hello SBE devs!

SBE codec is not escapes characters reserved by JSON during serialization.
It produces invalid JSON in cases when symbols like `"` present in text fields.

Thanks

**Comment by mjpt777** [comment]
This is not something we make use of. Feel free to send a PR to address it.

**Comment by rigtorp** [comment]
There is no builtin JSON serialization in the C++ codecs is there?

**Comment by ksergey** [comment]
@rigtorp there is JSON-like serialization. Serialization code don't escape JSON control chars in strings.

**Comment by ksergey** [comment]
I think better solution to have something like exists in `rapidjson` library:
https://rapidjson.org/md_doc_sax.html#Reader

**Comment by mjpt777** [comment]
I've pushed a change which will Json escape var data strings in UTF-8 or ASCII will is a subset and this is use for the pretty printing. Raw binary will be summarised as "x bytes of raw data".
