### ISSUE TITLE
[C#] C# stub classes should use description attributes from XML file

### ISSUE THREAD

**Issue by rca22** [real-logic/simple-binary-encoding#727]
The description fields for messages should result in C# comments in the generated code.

e.g.
`<sbe:message name="MyMessage" id="201" semanticType="V" description="This is my message type.">
<field name="MarketDepth" id="264" type="uint8" description="0=Full Book, 1=Top of Book, n=Number of Levels."/>
...
`

should result in 
```
/// <summary>
/// This is my message type
/// </summary>
public sealed partial class MyMessage
{
...
        /// <summary>
        /// 0=Full Book, 1=Top of Book, n=Number of Levels.
        /// </summary>
        public byte MarketDepth
        {
        ...
        }
}
```
This will aid in understanding the C# classes without having to refer back to the XML frequently.

**Comment by mjpt777** [comment]
We would welcome a PR for this or accept sponsorship for the development.
