### ISSUE TITLE
[C++] Invalid JSON output

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#734]
Hello devs!

C++ implementation generates invalid JSON for double in case of `nan` value. i.e.
```json
{"value": nan}
```
Is it possible to fix somehow? I didn't found a valid value for `nan` inside JSON. 

In most (my) cases `NaN` represent a null value inside SBE.  In JSON  `null` is valid keyword and could be used instead of `nan`.

Thanks

I used `sbe-all-1.14.0-all.jar`.

**Comment by ksergey** [comment]
_(Better solution is implement a reader interface like inside [SAX](https://rapidjson.org/md_doc_sax.html) parser =))_

**Comment by mjpt777** [comment]
If you want a SAX like parser then use [OTF](https://github.com/real-logic/simple-binary-encoding/wiki/Cpp-OTF-User-Guide).

We merged the pretty printing support for C++ thinking it may be useful for the community. It is not something we use ourselves. I may look at this a little tomorrow but I'm coming to the point of regretting merging this. It was not intended to be a JSON lib. We do SBE :-)

**Comment by ksergey** [comment]
@mjpt777 thanks. Feel free to close the issue. I'll check OTF.
