### ISSUE TITLE
[Java] method appendTo at Decoders - not sensitive enough for data elements

### ISSUE THREAD

**Issue by ariksher-nex** [real-logic/simple-binary-encoding#736]
It might throw **IndexOutOfBoundsException** on fields of data section (var length ones).
lets say we have message with one data element:

```
<type name="ModelYear" primitiveType="uint16" semanticType="ModelYear"/>
<type name="VehicleCode" primitiveType="char" length="6" semanticType="VehicleCode"/>

<sbe:message name="Car">
  <field name="modelYear" id="1" type="ModelYear"/>
  <field name="vehicleCode" id="2" type="VehicleCode"/>
  <data name="make" id="3" type="varDataEncoding"/>
</sbe:message>
```

Now, lets say that creator of message did **not** populate the data field of make.
in that case the encodedLength would be 8 (2bytes of  modelYear + 6characters of vehicleCode), 
hence the bounded size of buffer as 8.

Now, when decoder tries to reach for length of field **make** , it is at offset 8 (internal data memeber named limit), and it causes the **IndexOutOfBoundsException**.

snippet of exception
```
java.lang.IndexOutOfBoundsException: index=8 capacity=8
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck
	at org.agrona.concurrent.UnsafeBuffer.getShort
	at abc.CarDecoder.getMake
        at abc.CarDecoder.appendTo
```

**Comment by mjpt777** [comment]
That is the contract for SBE. You have to encode and then decode *all* the members in order. Adding extra checks and initialisation would reduce performance.
