### ISSUE TITLE
poor experience with debuggers

### ISSUE THREAD

**Issue by mgaunard** [real-logic/simple-binary-encoding#737]
Given the library design it is very difficult to print anything meaningful in a debugger.

**Comment by mjpt777** [comment]
There is a `toString()` method on the decoders for Java, and `<<` operator for C++. Those are the main codecs we support. The other are a contribution and if you would like a better experience them please contribute.

**Comment by mgaunard** [comment]
You cannot call functions from a debugger inspecting a core file.

That the reference implementation for SBE isn't even concerned about debugging quality is quite concerning.

I believe that is a strong argument for not using your implementation.
