### ISSUE TITLE
Reading capture data from the CME

### ISSUE THREAD

**Issue by poisedleft** [real-logic/simple-binary-encoding#740]
Apologies if this is not the correct place to post: this is my first one on Github, if there's a more appropriate forum I'd be glad to hear it. 

I've been adapting this code to read market data from packet captures from the CME. It's taken a while to figure out, though I've learned a lot (and still puzzling out some aspects of the structure to give output in the form in which I can parse it to my research project). 

I wasn't able to find any open source that read this code out of the box - there were one or two that nominally should have done so, but failed for some reason or another. The encoding seems non-standard.. close to a network capture but not exactly. In the end, my solution involved jumping over the correct number of bytes in each packet (as well as light modification to read from a file). 

My code at the moment is a bit of a mess -- I'm a trader and quant by profession, and it's also been years since I've touched Java. But is there a place where this particular use case might be shared (if not on this project, which seems to be general, than somewhere else?) I'd imagine there are others that would use this case.. although it's possible that for the majority of people doing this type of work are sophisticated enough that given the example, the solution is obvious, I know it would have been to the developers I've worked with in the past, who were writing high-performance code internally at large proprietary trading post. 

Perhaps a medium post breaking down the process I went through solving the problem (e.g. looking at the file in hex, trying to match what I saw with the specs in the template, looking through this code to see how it did and didn't match with that particular file format?). 

One motivation is that I know my code is *very* ad-hoc (I modified the OTF example), I'm sure that it isn't the intended way of using the code; and that the actual solution -actually using the example as an *example* would probably be quite simple. I know I would benefit from getting feedback on writing higher quality code, and the general approach of making use of a project of this type to solve a real-world problem (whether it is the CME market data I am working with or some other problem). 

Additionally, I know that parsing this type of data can't really be considered proprietary information at all - it's probably been done dozens if not hundreds of time - but most people doing so are locked behind quite strong legal restrictions. I'm in a position where I am not (at least not for general-purpose things like this). If there are other people in the same boat, we might benefit from pooling our resources.

**Comment by mjpt777** [comment]
This project is focused on the SBE implementation.
