### ISSUE TITLE
[C#] sbe-tool generate non-working code

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#748]
Hello devs!

For types like below C# generator makes non-compilable code.

```xml
        <composite name="Rate">
            <type name="rate" primitiveType="uint16"/>
            <type name="per" primitiveType="uint16" presence="constant" description="interval in ms">1000</type>
        </composite>
```
Error: CS0542 'Rate': member names cannot be the same as their enclosing type.

**Comment by mjpt777** [comment]
This is a C# restriction. Why not name the member `rate` something like `quantity` per `interval`?

```xml
    <composite name="Rate">
         <type name="quantity" primitiveType="uint16"/>
         <type name="interval" primitiveType="uint16" presence="constant" description="interval in ms">1000</type>
    </composite>
```

**Comment by ksergey** [comment]
@mjpt777 I already updated my schema. 

> This is a C# restriction

Anyway it should be mentioned somewhere in wiki. 

Feel free to close
