### ISSUE TITLE
Some common interfaces / abstract classes for SBE codecs

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#751]
If you're writing a library or framework that uses SBE codecs it's very hard to abstract over common operations from SBE codecs. This could be resolved with the addition of a common interface or abstract class. The kind of common operations that would be useful to abstract over would be:

 * `int sbeBlockLength()`
 * `StringBuilder appendTo(final StringBuilder builder)`
 * `int sbeTemplateId()`
 * `int sbeSchemaId()`
 * `int sbeSchemaVersion()`
 * `Encoder wrap(final MutableDirectBuffer buffer, final int offset)`
 * `Encoder wrapAndApplyHeader(
        final MutableDirectBuffer buffer, final int offset, final MessageHeaderEncoder headerEncoder)`

I'm happy to spend time to implement this - I don't think it would take long to be honest but I wanted to open an issue for feedback / discussion before starting.

**Comment by mjpt777** [comment]
Most of these already exist.

https://github.com/real-logic/agrona/tree/master/agrona/src/main/java/org/agrona/sbe

**Comment by RichardWarburton** [comment]
Thanks for pointing that out @mjpt777 - is there a configuration option that I need to use in order to generate them? At the moment all the codecs that I've seen generated don't implement these interfaces.

**Comment by mjpt777** [comment]
`sbe.java.generate.interfaces`

https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

**Comment by RichardWarburton** [comment]
Thanks.
