### ISSUE TITLE
can i use sbe on premises?

### ISSUE THREAD

**Issue by ambareldad** [real-logic/simple-binary-encoding#756]
Trying to implement sbe on our site.
The server we are running it on doesn't have internet connection, but can be connected to our organazation artifactory.
can i work in this architecture?
Thanks,
Eldad.

**Comment by mjpt777** [comment]
I'm assuming you are not build SBE from source. If you are a user and not a builder then you can download the all JAR from Maven Central and use it locally in your build.

https://search.maven.org/artifact/uk.co.real-logic/sbe-all
