### ISSUE TITLE
[Java] sbe-tool Provision for Enum to support non Java Identifier

### ISSUE THREAD

**Issue by peterdsdoyle** [real-logic/simple-binary-encoding#760]
Currently SBE Schema supports Enums with arbitrary named values, however when the sbe-tool generates the corresponding Enum java code, Value names that do not conform to Java Identifier standards will not compile. 
The JavaGenerator should detect these non conformant Enums and alter the Identifer value to conform to the Java standard however the original 'name' of the enum value should still be available such that string evaluation ie: valueOf() returns the enum corresponding to the schema named value

**Comment by mjpt777** [comment]
Please provide an example which demonstrates the failure.

**Comment by peterdsdoyle** [comment]
This is a feature request rather than a failure. The feature would allow for enum values to be non Java Identifiers Eg.

<enum name="LegSecurityType" encodingType="int8" description="To indicate the leg type for a single or multi-leg product. In the case of a FXSWAP, this refer to the near or far leg.">
    <validValue name="FXSPOT">0</validValue>
    <validValue name="FXFWD">1</validValue>
    <validValue name="FXSWAP-NEAR">2</validValue>
    <validValue name="FXSWAP-FAR">3</validValue>
    <validValue name="FXNDF">4</validValue>
    <validValue name="T-OPTION">5</validValue>
    ...
</enum>

The example above makes use of 'int8' for compactness, the names contain non valid Java Identifier as they include '-' and therefore the generated Java code would not compile. The feature would allow for arbitrary names.

**Comment by mjpt777** [comment]
This would have difficulty mapping to most languages. Better to define a schema with more practical names. How about you use underscores rather than hyphens?

This is unlikely to be implemented and no one willing to sponsor the development has ever suggested it.

**Comment by peterdsdoyle** [comment]
We would be capable of developing this change, its just a matter of the best approach. There are a number of options
1)   Relax the schema so that enum values aren't strict Identifiers, code generators would then detect this and create appropriate enum values/names
2) Introduce and altName into the schema/ir, again code generatros would use the name/altName values to contstruct the enum values/names.

can you suggest another approach ?

**Comment by mjpt777** [comment]
Note that we cannot change the schema without going via the standards process.

**Comment by peterdsdoyle** [comment]
Is that a lengthy process ? In the interrim we can place altName in the description and have the code Generator use that, Not ideal...

**Comment by billsegall** [comment]
I like altName as it allows you to work with multiple languages not just
Java.

Bill.

**Comment by mjpt777** [comment]
We have seen issues in the past where schemas were designed using language keywords for names. Our solution to this was to provide an option to append an underscore when generating. A similar approach could be taken that some characters get substituted.

Getting changes to the standard can be a slow process. SBE 2.0 has not as yet been finalised so you may make that release. 

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding

Many benefit from using SBE, but like most open source, people are happy to consume it but not so happy to contribute to the development by sponsorship.

**Comment by peterdsdoyle** [comment]
I agree the Code Generator should be responsible for correcting identifiers it cannot cope with rather than restricting the DSL. To that point my preference would be to lift the restriction on the enum sbe:validValue attribute 'name' type 
from 
`<xs:simpleType name="symbolicName_t">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="64"/>
            <xs:pattern value="([A-Z]|[a-z]|_)([0-9]|[A-Z]|[a-z]|_)*"/>
        </xs:restriction>
    </xs:simpleType>`
to
`   <xs:simpleType name="name_t">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="64"/>
            <xs:pattern value="([ -~-[&quot;&apos;`]])+"/>
        </xs:restriction>
    </xs:simpleType>
`
This will open up the name to printable chanraters excluding quotes and tick

**Comment by mjpt777** [comment]
The XSD is outside the scope of this project.  This needs to be taken up with the standards body.

**Comment by mjpt777** [comment]
For reference, why are messages schemas being created with names that clearly will not map to identifiers in most, if not all, languages?

**Comment by mjpt777** [comment]
You then have question of if the tool transforms names that are domain specific or they are transformed upstream and not coupled with the tool.

**Comment by mjpt777** [comment]
I'm going to close this as the conversation should happen in relation to the SBE standard.
