### ISSUE TITLE
[C#] SinceVersion checks use type's version, not the field

### ISSUE THREAD

**Issue by EddPorter** [real-logic/simple-binary-encoding#763]
When generating fields, the `encodingToken` is passed to the `generate*Property()` methods and the properties from the enclosing `signalToken` are ignored. In particular, using `sinceVersion` on a field has no effect. Any fields using primitive types will never output code from `generateFieldNotPresentCondition()`. Also, and misleadingly, fields using custom or composite types will output version checking code based on the `sinceVersion` specified in the `type`.

**Comment by mjpt777** [comment]
The `sinceVersion` on the type should be considered but it is overridden by the value on the field. The value from the field will be set in the IR based on the type if none is set on the field. The C# codes should use the value from the field. The Java and C++ codecs use the value from the field. In the past this was confused as the standard moved around on this topic.

**Comment by mjpt777** [comment]
@billsegall can you check if my change generates the correct code for you?
