### ISSUE TITLE
[C] Question, is the C generator stable now?

### ISSUE THREAD

**Issue by lygstate** [real-logic/simple-binary-encoding#767]

**Comment by mjpt777** [comment]
@denizevrenci should be able to give a view on this.

**Comment by denizevrenci** [comment]
Functionality-wise it can be considered to be stable.
As for the API, it is on par with the C++ generator from a year ago so it is missing a few new features. Another thing to consider is whether or not to divide encoder and decoder functionality to separate namespaces like the Java generator. And lastly, we need to decide between snake case and camel case. Ultimately, it would be nice to add an option to be able to choose between the two in the generated code but for now, we should probably pick one to move forward.

**Comment by lygstate** [comment]
@denizevrenci Any demo for C generator? I can not found the document about C geneartor

**Comment by denizevrenci** [comment]
No demo per se but the tests show the usage. They are located here: https://github.com/real-logic/simple-binary-encoding/tree/master/sbe-tool/src/test/c

**Comment by lygstate** [comment]
@denizevrenci I've looking into the demo code found it's rather complicated, any idea to simplify it?

**Comment by lygstate** [comment]
May be using function pointer is a good idea.

**Comment by denizevrenci** [comment]
Could you give an example about what you mean by simplifying with function pointers?

**Comment by lygstate** [comment]
```
    struct sbe_messageHeader messageHeader;
    struct sbe_account account;
    struct sbe_balance wallet;
    struct sbe_account_orders orders;
    struct sbe_order order;

    sbe_messageHeader_wrap(&messageHeader, buffer, 0, 1, bufferLength);
    sbe_messageHeader_set_blockLength(&messageHeader, sbe_account_sbe_block_length());
    sbe_messageHeader_set_templateId(&messageHeader, sbe_account_sbe_template_id());
    sbe_messageHeader_set_schemaId(&messageHeader, sbe_account_sbe_schema_id());
    sbe_messageHeader_set_version(&messageHeader, sbe_account_sbe_schema_version());

    sbe_account_wrap_for_encode(&account, buffer, sbe_messageHeader_encoded_length(), bufferLength);
    sbe_account_set_id(&account, 100);
    sbe_account_put_name(&account, "Test", strlen("Test"));

```
turn out to be
```
    struct sbe_messageHeader messageHeader;
    struct sbe_account account;
    struct sbe_balance wallet;
    struct sbe_account_orders orders;
    struct sbe_order order;

    sbe_messageHeader_wrap(&messageHeader, buffer, 0, 1, bufferLength);
    sbe_messageHeader_set_blockLength(&messageHeader, sbe_account_sbe_block_length());
    sbe_messageHeader_set_templateId(&messageHeader, sbe_account_sbe_template_id());
    sbe_messageHeader_set_schemaId(&messageHeader, sbe_account_sbe_schema_id());
    sbe_messageHeader_set_version(&messageHeader, sbe_account_sbe_schema_version());

    sbe_account_wrap_for_encode(&account, buffer, sbe_messageHeader_encoded_length(), bufferLength);
    account.set_id(&account, 100);
    account.put_name(&account, "Test", strlen("Test"));
    
```

**Comment by tmontgomery** [comment]
I don't see why we should add function pointers. It simply creates unnecessary space in the codecs that provides no real value.
