### ISSUE TITLE
Import common encodings - maven build

### ISSUE THREAD

**Issue by puiuvlad** [real-logic/simple-binary-encoding#776]
I am using the SBE Tool as part of my Maven build, as suggested here: https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Maven

To re-use common encodings I have added the sbe.xinclude.aware system property and the xi:include XML element in my schema file which references the file where the common encodings are defined, as suggested here:
https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

However, when I execute mvn:install the common encodings are not found and the tool does not generate the codecs.

Any suggestion on how to get around?

I am using version 1.8.1 of the SBE tool.
 
Thanks,
Vladimir

**Comment by mjpt777** [comment]
Your version of SBE is previous to the support being used for include. Please upgrade.

**Comment by puiuvlad** [comment]
Indeed, that was the issue. Thanks Martin
