### ISSUE TITLE
[C#] update package on NuGet.org

### ISSUE THREAD

**Issue by idlem1nd** [real-logic/simple-binary-encoding#781]
Hi, I notice the C# project here targets net45 and netstandard2.0: 
https://github.com/real-logic/simple-binary-encoding/blob/8e208923c72c699977b404b5c04b639f2857ff03/csharp/sbe-dll/sbe-dll.csproj#L3

but the package on NuGet.org has not been updated since 2014 and targets net40.

Can a new version of the package be built and published please?

**Comment by billsegall** [comment]
You're probably looking for this one: https://www.nuget.org/packages/sbe-tool/

**Comment by tmontgomery** [comment]
Closing as question is answered.
