### ISSUE TITLE
C++ generator MSVC warming about -2147483648

### ISSUE THREAD

**Issue by lygstate** [real-logic/simple-binary-encoding#788]
```
    enum Value
    {
        OK = 0,
        ERROR = 1,
        RECORDING_UNKNOWN = 2,
        SUBSCRIPTION_UNKNOWN = 3,
        NULL_VALUE = -2147483648
    };

    static ControlResponseCode::Value get(const std::int32_t value)
    {
        switch (value)
        {
            case 0: return OK;
            case 1: return ERROR;
            case 2: return RECORDING_UNKNOWN;
            case 3: return SUBSCRIPTION_UNKNOWN;
            case -2147483648: return NULL_VALUE;
        }
```

**Comment by mjpt777** [comment]
The literal `-2147483648` does not exist, it is a unary negation of `2147483648`. We could use `(-2147483647 - 1)`. @tmontgomery do you have a view on this?

**Comment by lygstate** [comment]
prefer INT32_MIN and INT32_MAX

**Comment by tmontgomery** [comment]
The SBE spec has specific values.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/02FieldEncoding.md#range-attributes-for-integer-fields

So, we are limited to those values.

According to what I can see on gcc/clang:

INT32_MIN = (-0x7FFFFFFF - 1) = -2,147,483,648

and

-2^31 = -0x80000000 = -2,147,483,648

So, if Windows libs can be verified to have equivalent value, I'm fine.
