### ISSUE TITLE
SbeMarshalling.go file generated by SBE Tool is empty

### ISSUE THREAD

**Issue by ntrifunovic** [real-logic/simple-binary-encoding#789]
This seams to be introduced in commit: real-logic/simple-binary-encoding@bf01599 by excluding golang/templates when building jars. Files from golang/templates are used to generate `SbeMarshalling.go` which is empty.

**Comment by mjpt777** [comment]
@vyazelenko can you have a look?

**Comment by vyazelenko** [comment]
@mjpt777 on it

**Comment by vyazelenko** [comment]
Fixed by https://github.com/real-logic/simple-binary-encoding/commit/c60d8cf44eebd01d573da651ec29207254817149
