### ISSUE TITLE
Generated Message Collection class

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/simple-binary-encoding#8]
For an entire schema of multiple messages, it would be useful to auto-generate a collection class that can parse a header and dispatch to various classes. The lookup could be a perfect hash on an ordered list of template IDs.

A possible implementation could be along these lines (for Java).

public interface IProcessMsg
{
   void process(DirectBuffer buffer, int offset);
}

public class MyMessageType implements MessageFlyweight, IProcessMsg …
<this delegates to the generated code… kind of like wrapping the generated code>

<decode header and grab templateId>
IProcessMsg msg = map.get(templateId);        // lookup template and return wrapped message class
msg.process(buffer, offset + header.size());     // process message

**Comment by mjpt777** [comment]
Closing for now due to inactivity.
