### ISSUE TITLE
Is it possible to map this json with SBE?

### ISSUE THREAD

**Issue by cbranca** [real-logic/simple-binary-encoding#804]
Let's say that I have all fields with fixed length. Is it possibile to put a repeated group ("markets") inside a composite ("body") that is inside a message?

This json describes the structure I would like to map:
```javascript
{
    "header": {...},
    "body": {
        "res": 1,
        "markets":[ 
            { "market": "mkt_1", "id": 1 },
            { "market": "mkt_2", "id": 2 },
            { "market": "mkt_3", "id": 3 },
            { "market": "mkt_4", "id": 4 }
        ]
    }
}
```

Thank you in advance.

**Comment by mjpt777** [comment]
It is not possible to put a group or var data member in a composite. The specification does not allow for this.

You could model this as a protocol with a header message followed by a number of `market` messages.
