### ISSUE TITLE
C++ getters are not const, preventing const-correctness/using const char*

### ISSUE THREAD

**Issue by cpp77** [real-logic/simple-binary-encoding#805]
Firstly thanks for writing this.

I'm having issues because I want to pass a const char* but m_buffer of each class is char*. I realised this is because certain getter functions modify the buffer, for example in MDDefinitionFutures54.h retrieving the displayFactor is non-const:

```
    SBE_NODISCARD Decimal9 &displayFactor()
    {
        m_displayFactor.wrap(m_buffer, m_offset + 99, m_actingVersion, m_bufferLength);
        return m_displayFactor;
    }
```

because m_displayFactor is a member of MDDefinitionFutures54 and is modified.

Would it be possible to decode on-the-fly, so getters can be const?

**Comment by mjpt777** [comment]
This is not so easy because the same flyweight is used for both encode and decode operations. If someone was interested in sponsoring the development of separate encoders and decoding in a similar fashion to how the Java codecs work then we would be interested.

**Comment by rogerorr** [comment]
We could get *slightly* closer, without a big redesign, by adding a `const` overload:

```
 SBE_NODISCARD const Decimal9 displayFactor() const
    {
        return Decimal9(m_buffer, m_offset + 99, m_actingVersion, m_bufferLength);
    }

**Comment by tmontgomery** [comment]
Don't think that buys you much. The right way to handle this is to split the decoder/encoder.

**Comment by mjpt777** [comment]
Closing as a split encoder and decoder Java is a better design.
