### ISSUE TITLE
When Encoding: Can messageHeaderVersion != Car::sbeSchemaVersion()  ?

### ISSUE THREAD

**Issue by chtrading** [real-logic/simple-binary-encoding#810]
This wiki page 
https://github.com/real-logic/simple-binary-encoding/wiki/Cpp-User-Guide
 
there is:
 // Encode the header
    hdr.wrap(buffer, offset, messageHeaderVersion, bufferLength)

I want to understand: Could messageHeaderVersion have other value than Car::sbeSchemaVersion() when we want to encode?

I understand that we can have different Message Schema version when decoding (chapter 5 of the specification), but can a normal well formed program have messageHeaderVersion different than Car::sbeSchemaVersion() at Encoding?

**Comment by mjpt777** [comment]
You should encode with the current version of the generated codec and then when decoding you read the version it has been encoded with and that becomes the acting version when decoding. Time and versions can separate the encoding and decoding.
