### ISSUE TITLE
I can't access "data" part of Var-Len Data

### ISSUE THREAD

**Issue by chtrading** [real-logic/simple-binary-encoding#811]
I have the following composite type:

![image](https://user-images.githubusercontent.com/52830872/89846709-5c474100-db58-11ea-9a75-a83c7a6f8a04.png)
_________________________________________________________

The header generated was:

[var.log](https://github.com/real-logic/simple-binary-encoding/files/5054260/var.log)
_________________________________________________________

The problem is: I can't access data part! I can access only length.

The documentation says:

![image](https://user-images.githubusercontent.com/52830872/89846727-7123d480-db58-11ea-838b-07ead564c367.png)
_________________________________________________________

But I can not see any function member like this.

If I search "m_offset + " in the header, I can see only this:

image
![image](https://user-images.githubusercontent.com/52830872/89846742-7a14a600-db58-11ea-8c25-621dd5bd3cc7.png)
_________________________________________________________
EDIT:
Of course, i could access buffer pointer and add +2 (uint16 from length). But this wouldn't be elegant.

**Comment by tmontgomery** [comment]
You might want to use "varData" instead of "data".

**Comment by chtrading** [comment]
> You might want to use "varData" instead of "data".

There is not "varData".
The generated header VarAsciiString.h is attached (var.log).

**Comment by tmontgomery** [comment]
Well, if you are using it as a variable length encoding, the generator expects it to be named "varData". A 0 length "data" field is probably not going to work out well as that should be a constant and thus different.

I'm guessing, though, as you can look at the example [schema](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-samples/src/main/resources/common-types.xml) and see the name is `varData` for the variable length encoding.

**Comment by chtrading** [comment]
I changed to varData. The new generated header is the same except that it now has different names, from data to varData.

**Comment by tmontgomery** [comment]
You do realize that for variable-length data fields that you don't use that composite directly, right? The code you quote from the sample doesn't use the composite, it uses the field name. i.e. `getManufacturer`, `getModel`, `getActivationCode`. The composite is used only for layout purposes and for generating the IR, etc. Using it directly is not the intended way to utilize it.

**Comment by chtrading** [comment]
> You do realize that for variable-length data fields that you don't use that composite directly, right? The code you quote from the sample doesn't use the composite, it uses the field name. i.e. `getManufacturer`, `getModel`, `getActivationCode`. The composite is used only for layout purposes and for generating the IR, etc. Using it directly is not the intended way to utilize it.

Yes! I know. 
The documentation says:
![image](https://user-images.githubusercontent.com/52830872/89852897-49d40400-db66-11ea-8107-f550309cdaaa.png)
___________________________

The problem is: I am not being able to take the "getheadline", so I am trying to do the work in some way! I will explain:

This is the message that I need to decode:
![image](https://user-images.githubusercontent.com/52830872/89853018-98819e00-db66-11ea-97c6-90e81a897f73.png)
___________________

The headline has type Var-Len Data. But the News doesn't have the getHeadline. As you can see:
![image](https://user-images.githubusercontent.com/52830872/89853150-0fb73200-db67-11ea-908f-91b2f9869aaa.png)
_____________________________

**Comment by chtrading** [comment]
I think I know what the problem is.

headline should not be "field", it should be "data". I will try it.

**Comment by chtrading** [comment]
:) Solved.

![image](https://user-images.githubusercontent.com/52830872/89853482-e34fe580-db67-11ea-8d9b-1fcae647c0bc.png)

**Comment by chtrading** [comment]
@tmontgomery , But you are right: it needs to be varData even if I correct it from "field" to "data". Otherwise, the output is:

ERROR: at <sbe:message name="News_5"> <data name="headline"> composite for variable length data encoding must have "varData"
ERROR: at <sbe:message name="News_5"> <data name="text"> composite for variable length data encoding must have "varData"

**Comment by mjpt777** [comment]
@chtrading Please follow the examples and only change the types if you are very comfortable with the basics.
