### ISSUE TITLE
[Rust] Reinstatement of Rust support in SBE

### ISSUE THREAD

**Issue by NiinS** [real-logic/simple-binary-encoding#813]
Hi @mjpt777 and team ,

Hope you are doing well. I was looking at the commit hash: **46753167d9e98228b18c7fdc367580bee10f468b** which removed the Rust support from SBE.

There may be reasons you can probably share as the removal comment says "lack of community support".

Can we reinstate Rust in SBE and I'm happy to help with maintenance? 

The last fully working tag for Rust support in SBE was **1.16.3** which I checked out and was able to successfully use to generate Rust codecs..

**Here are the steps:**

1. (To generate Rust codecs) ./gradlew generateRustCodecs
2. (Build and run Rust car example)  In a Rust enabled environment:

- Change dir to "../sbe/rust/car_example" folder 
- (Build) cargo build
- (Run) cargo run

A sample run is showing this output:

![image](https://user-images.githubusercontent.com/3360301/90624317-1aef1980-e25b-11ea-85fc-47c503286328.png)

This is from VS Code targeting a WSL (Windows subsystem for Linux) installation with a proper Rust installation. 

**- Note there are 27 warnings in the the generated code which can be addressed.**

**Comment by mjpt777** [comment]
The reason for removal was simple. The implementation was incomplete and being left to rot with many issues remaining. We don't see the point is keeping an implementation that the community is willing to maintain. Multiple times we were told effort would be put in but that effort never materialised.

If a PR is submitted which re-enstates the Rust implementation AND has substantially improved the codecs so they are as functional as the Java implementation then we would be willing to accept it again.

**Comment by NiinS** [comment]
Thanks @mjpt777 .. Much appreciated.

**Comment by NiinS** [comment]
Should one need to be a contributing member in this repo since when I attempted to push an initial branch to work on this issue, it showed a failed authentication?

I have confirmed my credentials are correct and I can successfully push to my own repos.

**Comment by tmontgomery** [comment]
Only a few can branch or merge into the repo. It's better to fork and then send a PR.

**Comment by NiinS** [comment]
> Only a few can branch or merge into the repo. It's better to fork and then send a PR.

Thanks @tmontgomery .. I'd follow that approach.

**Comment by NiinS** [comment]
hi @mjpt777 ,

I did some comparison on the SBE fork for Rust's reinstatement. Can more information be provided what exactly is missing in terms of Rust's implemented functionality?

e.g. looking at the main driver code in rust/main.rs - its reading the SBE data file generated by Java example stub. It can successfully decode that and can successfully compare against its own encoded version.

Are we talking about missing Gradle tasks (e.g. a missing generateRustIrCodecs) or OTF (on the fly) samples?

Once we know what is not there in a fuller Rust support, we'd make an effort to fill that gap first followed by bringing the Rust implementation to expected Java standard.

regards

**Comment by mjpt777** [comment]
I'd like to see new codecs fully support the car schema and extension that the Java one currently does plus OTF.

**Comment by NiinS** [comment]
Thanks for your comments.

**Comment by JulienBe** [comment]
@NiinS Hello, are you still working on this ?

**Comment by NiinS** [comment]
> @NiinS Hello, are you still working on this ?

I had done some work locally on it although not fully done.  The branch I resurrected locally was based on the repo state prior to commit hash: 4675316..

If you are interested, we might probably sync up. 

Please note that I'm a day time Java programmer and Rust is not my core strength therefore treading slowly.

**Comment by mward** [comment]
@NiinS I recently submitted a PR to add a Rust code generator: https://github.com/real-logic/simple-binary-encoding/pull/860

I believe this should resolve the issue.  Please let me know if you have any questions/comments.  Thanks!
