### ISSUE TITLE
[Java] Java OTF decoder dispatch by message across multiple schemas

### ISSUE THREAD

**Issue by donmendelson** [real-logic/simple-binary-encoding#82]
Some applications need to decode messages from multiple message schemas. The C++ implementation supports this. The IrCollection class can load multiple IR files into memory and supports look-up of IR by template ID and version. However, the Java implementation lacks an equivalent of IrCollection.

**Comment by mjpt777** [comment]
Java and C++ now take the same approach to OTF. IR is a one-to-one mapping to schema. An application can choice which IR to use based on schema version.
