### ISSUE TITLE
[C] Bug in  *_wrap_and_apply_header() in generated C code

### ISSUE THREAD

**Issue by danielcranford** [real-logic/simple-binary-encoding#822]
Generated C code has a bug in the generated function *_wrap_and_apply_header() The argument order when it calls *messageHeader__wrap() is wrong. It seems like an easy mistake to make as there is very little consistency in argument order between version and bufferLength in the generated code.

**Comment by mjpt777** [comment]
I agree there is a consistency issue here. @denizevrenci should we make these consistent within the C codecs and make it consistent with the C++ codecs?

**Comment by denizevrenci** [comment]
Sorry for the late response. It seems like the issue is already resolved but I am also in favor of keeping consistency with the C++ codecs as C codecs were originally modeled from them.
