### ISSUE TITLE
SBE 1.20.3 is generating C++ code with incorrect macro __cplucplus

### ISSUE THREAD

**Issue by samkhopkar** [real-logic/simple-binary-encoding#824]
Below is a sample of generated code. The macro is missing a "s"

Needs to be __cplusplus instead of _cplucplus

#if __cpluplus >= 201703L
        length += std::apply(SymbolResponses::computeLength, e);
        #else
        length += SymbolResponses::computeLength(std::get<0>(e), std::get<1>(e));
#endif

**Comment by samkhopkar** [comment]
Will the correction be available in SBE 1.20.4 jar ?

**Comment by mjpt777** [comment]
Yes. That will be released sometime this month.

**Comment by samkhopkar** [comment]
Thanks. Do you know when the C# nuget package for SBE 1.20.4 will be available ?
The latest one available seems to be 1.17.1

**Comment by mjpt777** [comment]
Maybe @billsegall can push the next release to NuGet when we release in a few weeks?

**Comment by billsegall** [comment]
Can do.

Bill

**Comment by mjpt777** [comment]
Thanks @billsegall

**Comment by billsegall** [comment]
nuget package is there - would appreciate if it were checked @samkhopkar?

**Comment by samkhopkar** [comment]
Thanks Bill. Will download and check it out

Sam

**Comment by samkhopkar** [comment]
@billsegall has the java version changed for the jar file ? If yes, which java version are the SBE jar classes compiled with ?

Was able to generate for C++ with Java 8 (1.80.25) and SBE 1.20.3

Cannot generated for C++ with Java 8 (1.80.25) and SBE 1.20.4 - see error below

[sam@ch0-skhop-03 sbe]$ make sbe
java -Dsbe.target.language="cpp" -Dsbe.cpp.namespaces.collapse="true" -Dsbe.output.dir=. -jar /home/sam/vendor/reallogic/Linux-x86_64/bin/sbe-all-1.20.4.jar template/GV_Price_Feed_SBETemplate.xml
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/co/real_logic/sbe/SbeTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
make: *** [Makefile:13: com_gelbergroup_gv_prices_dd] Error 1

[sam@ch0-skhop-03 sbe]$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
[sam@ch0-skhop-03 sbe]$

Thanks
Sam

**Comment by samkhopkar** [comment]
@billsegall No worries. I upgraded my box to Java 15 and it generates fine. Thank you.

**Comment by samkhopkar** [comment]
@billsegall please let us know the min java version needed to use the SBE jar file in SBE 1.20.4. Thanks

**Comment by billsegall** [comment]
I was using:
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

I'm unsure what the officially supported range is.

Bill.

**Comment by samkhopkar** [comment]
Thanks Bill. That is a problem. If you have the jar created with Java 15
then it does not work with older versions of Java. Various teams here are
all using Java 8 and it fails. However SBE 1.20.3 works fine with Java 8.

Can you build the jar with Java 8 and redeploy the nuget package for
1.20.4. Then I can try again with Java 8

Thanks
Sam

**Comment by mjpt777** [comment]
@billsegall This should be built with Java 8.

**Comment by billsegall** [comment]
I can try but not until the 27th of December sorry. Right now I'm on a
beach 🏖️ using my cell.


I'll see if I can pull the nuget package.

Bill

**Comment by billsegall** [comment]
@samkhopkar 1.20.4 is deprecated and 1.20.4.1 built with Java 8 is at
nuget.org.

Would appreciate another test.

Thanks,
Bill.

**Comment by samkhopkar** [comment]
Thanks, I'll check it out.

**Comment by samkhopkar** [comment]
Works with Java 8. Thanks Bill.

Sam
