### ISSUE TITLE
Invalid Javadoc can be generated from SBE xml files for > and <

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#826]
SBE generates javadoc from description tags in SBE xml files. It converts HTML escaped < and > characters `&lt;` and `&gt;` into plaintext ones, which then generates invalid javadoc. If the escaped HTML characters were preserved then correct javadoc would be generated. Examples below:

**SBE description tag**
`description="Price of this fill reason or allocation. Required if NoFills(1362) &gt; 0. Same as LastPx(31)"`

**Currently generated Javadoc**
`* @return PRICE9Decoder : Price of this fill reason or allocation. Required if NoFills(1362) > 0. Same as LastPx(31)`

**Javadoc tool error**
`/path/to/SomeFile.java:2594: error: bad use of '>'
         * @return PRICE9Encoder : Price of this fill reason or allocation. Required if NoFills(1362) > 0. Same as LastPx(31)`

**What I would expect for Javadoc**
`* @return PRICE9Decoder : Price of this fill reason or allocation. Required if NoFills(1362) &gt; 0. Same as LastPx(31)`

**Comment by mjpt777** [comment]
This can bring up a complex topic. How far do we go for all possible formatting in javadoc? Beyond escaping HTML characters there are the special characters in javadoc such as `@` and all code formatting combinations. I've done the minimum for now.

**Comment by RichardWarburton** [comment]
Thanks Martin. I've just tested this and it works on my example. IMHO just the HTML escape characters is fine. The thing is that `&lt` and `&gt` are characters that people do use in SBE protocol documentation - the error was actually generated from an SBE xml file from CME for example. If you do something weird with code formatting - I think it's reasonably to punt that onto the maintainer of the file XML file to fix.
