### ISSUE TITLE
[Documentation] SBE not suitable for describing existing binary wire protocols!

### ISSUE THREAD

**Issue by hrstoyanov** [real-logic/simple-binary-encoding#830]
Can you please document somewhere that **SBE is not suitable for describing existing protocols** and is mostly meant for defining new custom protocols? I wish I knew that when I started, would have saved a lot of hours!

SBE requires a very specific message header (which makes sense, if you are designing from scratch)  but is not easy to retrofit into other binary protocol message headers. 

For example, I was trying to describe DTS - [Microsoft's SQL Server wire protocol](https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-sqlprotlp/f16558b2-4561-45be-89c9-6f9114514c97) when I realized that the DTS message header (called PacketHeader, defined in section 2.2.3.1.3) while  also having a  **length** field, actually is the length of the entire packet, which makes it incompatible with SBE message header length field defined as "_...The length of the message root block before repeating groups or variable data commences_".

**Comment by mjpt777** [comment]
I think you misunderstand how protocols can be constructed. The total length is often contained in a framing protocol, e.g. [Aeron](https://github.com/real-logic/aeron/wiki/Transport-Protocol-Specification) and [SOFH](https://www.fixtrading.org/standards/fix-sofh/). Good protocol design is layered with layer have a good separation of concerns.

**Comment by hrstoyanov** [comment]
@mjpt777 I think you misunderstood my problem, which is: **Can SBE be used effectively to code/decode legacy binary protocols, over which one has no design control, such as  MS SQL wire protocol** rather than [implementing codecs manually as this developer did](https://github.com/MindFlavor/TDSBridge/tree/master/TDSBridge/TDSBridge.Common). The issue with the "length" I described above is just one of several I bumped into ...

The answer so far seems to be, that SBE can be partially useful if you throw away the message header/coder/decoder and just use the other generated codecs  for composite types, etc. Unfortunately the SBE tool insist on message header/schema and one has to cheat by creating a fake one.

**Comment by mjpt777** [comment]
I don't understand what you expect or feel you are entitled to. This project is an implementation of the [SBE](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) standard and does not define the SBE standard, which we link from our the main README. I don't see how you think it is reasonable to expect an open source project to which you do not contribute, or pay support for, to be perfect for your project so you can save time. If you have feedback for the standards body then best to address feedback to them.
