### ISSUE TITLE
[Java] big/little Endian issue?

### ISSUE THREAD

**Issue by hrstoyanov** [real-logic/simple-binary-encoding#831]
SBE message schema accepts **byteOrder** attribute and applies it for everything in it. Can one override the byte order at the type level? For example, I would have expected that in the below case, **position** and **length** methods in the generated encoder/decoder will be using Big Endian byte order, but seems like  the schema default of Little Endian was used?
```
<sbe:messageSchema
                   description="MS SQL TDS schema."
                   id="1"
                   version="1"
                   semanticVersion="5.2"
                   byteOrder="littleEndian">
<types>
       <composite name="preLoginOption" description="Pre-login request option">
             ...
            <type name="position" primitiveType="uint16" byteOrder="bigEndian"/>
            <type name="length" primitiveType="uint16" byteOrder="bigEndian"/>
        </composite>
</types>
...
```
Generated code:
```
   //Encoder
    public PreLoginOptionEncoder position(final int value)
    {
        buffer.putShort(offset + 1, (short)value, java.nio.ByteOrder.LITTLE_ENDIAN);
        return this;
    }
    ...
    //Decoder
    public int position()
    {
        return (buffer.getShort(offset + 1, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF);
    }
```

**Comment by mjpt777** [comment]
The SBE standard does not support this.

**Comment by hrstoyanov** [comment]
... Ok, but: 
a. do you find the above request reasonable , and if so :
b. Can I contribute a PR for it in this project ?
c. .. or Do I have to convince the "SBE protocol owners" first, and then submit a PR here?

**Comment by mjpt777** [comment]
That would not be within the SBE 1.0 final specification. Engaging with the standards body for a future version of the standard would be the way to approach this.

**Comment by hrstoyanov** [comment]
@mjpt777 I am not winning hearts and minds in the SBE group for this change, but I am still up for contributing a patch in this roject, if allowed - I turns out that currently you can mix LE and BE in the XML specs and there are no validation issues, just the emitted code ignores the per-filed LE/BE attribute. I can fix that?

**Comment by mjpt777** [comment]
Adding a `byteOrder` attribute will not pass validation when the XSD is applied. SBE tool could be modified to do this in a non-standard way as an option. However I not minded to support or even consider going against the standard without good reason from a paying support customer.
