### ISSUE TITLE
E0304 / C2664 errors VS C++ 2019

### ISSUE THREAD

**Issue by GreenwichDairy** [real-logic/simple-binary-encoding#835]
Every time I use one of the by SBE tool generated .h files, part of the code is failing (for CME).
I get the following errors:
Severity	Code	Description	Project	File	Line	Suppression State

Error (active)	E0304	no instance of function template "mktdata::MDIncrementalRefreshBook46::NoMDEntries::forEach" matches the argument list	MDIncrementalRefreshBook46.h	1863	
and
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void mktdata::MDIncrementalRefreshBook46::NoMDEntries::forEach<mktdata::MDIncrementalRefreshBook46::skip::<lambda_0bdb07a2c8818c1943745681993c3a58>>(Func &)': cannot convert argument 1 from 'mktdata::MDIncrementalRefreshBook46::skip::<lambda_0bdb07a2c8818c1943745681993c3a58>' to 'Func &'	MDIncrementalRefreshBook46.h	1863	

The C++ code that is generated is:
```cpp
void skip()
{
    noMDEntries().forEach([](NoMDEntries e) //JC
    {
        e.skip();
    });
    noOrderIDEntries().forEach([](NoOrderIDEntries e)
    {
        e.skip();
    });
}
```

How can I solve this?

**Comment by mjpt777** [comment]
Can you send a minimum example that reproduces the issue and indicate which version of SBE tool you are using?

**Comment by GreenwichDairy** [comment]
Hi Martin,
Thanks for getting back so quick.
I generated the files using the following command:
java -Dsbe.target.language=CPP -jar C:\Users\User\Downloads\simple-binary-encoding-master\simple-binary-encoding-master\sbe-all\build\libs\sbe-all-1.20.5-SNAPSHOT.jar templates_FixBinary.xml

The templates_FixBinary are from the CME website (version 9).
I include one of the .h files that is being generated. Just by including this file, I get the errors in my project. (lines 1185-1188 are the culprit) 
[MDIncrementalRefreshOrderBook47.zip](https://github.com/real-logic/simple-binary-encoding/files/5849527/MDIncrementalRefreshOrderBook47.zip)

Thank you very much
Best regards
Jerome

**Comment by mjpt777** [comment]
I mean please send a sample schema which illustrates the issue. You could do this by extracting only the parts of the CME schema which cause the issue for you. Without a support contract we limit our public effort to those who make it as easy as possible for us to investigate.

**Comment by GreenwichDairy** [comment]
Got it:

Please find the relevant part attached:

    <ns2:message name="MDIncrementalRefreshOrderBook47" id="47" description="MDIncrementalRefreshOrderBook" blockLength="11" semanticType="X" sinceVersion="9">
        <field name="TransactTime" id="60" type="uInt64" description="Start of event processing time in number of nanoseconds since Unix epoch" offset="0" semanticType="UTCTimestamp"/>
        <field name="MatchEventIndicator" id="5799" type="MatchEventIndicator" description="Bitmap field of eight Boolean type indicators reflecting the end of updates for a given Globex event" offset="8" semanticType="MultipleCharValue"/>
        <group name="NoMDEntries" id="268" description="Number of entries in Market Data message" blockLength="40" dimensionType="groupSize">
            <field name="OrderID" id="37" type="uInt64NULL" description="Order ID" offset="0" semanticType="int"/>
            <field name="MDOrderPriority" id="37707" type="uInt64NULL" description="Order priority for execution on the order book" offset="8" semanticType="int"/>
            <field name="MDEntryPx" id="270" type="PRICENULL9" description="Order price" offset="16" semanticType="Price"/>
            <field name="MDDisplayQty" id="37706" type="Int32NULL" description="Visible order qty" offset="24" semanticType="Qty"/>
            <field name="SecurityID" id="48" type="Int32" description="Security ID " offset="28" semanticType="int"/>
            <field name="MDUpdateAction" id="279" type="MDUpdateAction" description="Order book update action to be applied to the order referenced by OrderID" offset="32" semanticType="int"/>
            <field name="MDEntryType" id="269" type="MDEntryTypeBook" description="Market Data entry type " offset="33" semanticType="char"/>
        </group>
    </ns2:message>

**Comment by mjpt777** [comment]
That is not a complete schema I can drop into a test.

**Comment by mjpt777** [comment]
Even better is you supply a patch or PR with a failing tests.

**Comment by GreenwichDairy** [comment]
Sorry about that. I thought you only wanted the part I referred to in the .h file I gave you below. 
Please find the fill xml attached. Does that work?

[templates_FixBinary.zip](https://github.com/real-logic/simple-binary-encoding/files/5849959/templates_FixBinary.zip)

**Comment by GreenwichDairy** [comment]
Regarding the test - just by including the .h file, the project will generate compile errors. No code needed. There is no template for: 

foreach([] (NoMDEntries e){});

That is causing this issue.

Thanks vm for all your help!

**Comment by GreenwichDairy** [comment]
One last remark... It is for EVERY .h file I include that is generated. If it were just one, I could easily fix it, but every .h file I include has this issue

**Comment by mjpt777** [comment]
That is the full XML schema. Can you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by GreenwichDairy** [comment]
Please find attached a minimal.xml as well as a test VS C++ project that shows what the error is. 
Thank you so much for your help!
[minimal_FixBinary.zip](https://github.com/real-logic/simple-binary-encoding/files/5863285/minimal_FixBinary.zip)
[Test.zip](https://github.com/real-logic/simple-binary-encoding/files/5863282/Test.zip)

**Comment by mjpt777** [comment]
I've improved the skip code to be more efficient in passing by reference rather than value for the entries. When tested against all our compilers in CI, which include MSVC, the test passes.

**Comment by GreenwichDairy** [comment]
THANK YOU!
