### ISSUE TITLE
Issue upgrading SBE tool from 1.20.4 --> 1.21.0

### ISSUE THREAD

**Issue by hrstoyanov** [real-logic/simple-binary-encoding#836]
Hi,
A recent  change to make generated codec classes final is breaking my code. I use the fact that the generated classes are not final to override and compensate for some [missing feature in SBE](https://github.com/real-logic/simple-binary-encoding/issues/831) like so:

```
//Generated decoder
public class PacketHeaderDecoder implements CompositeDecoderFlyweight
{
 //generated methods with  little endians only.
...
}

//This class overrides little endian to big endian encoding for certain methods of the generated class only, allowing a mix.
class PacketHeaderDecoder extends com.my.generated.PacketHeaderDecoder {

    @Override
    public int packetLength() {
        return (buffer().getShort(offset() + 2, ByteOrder.BIG_ENDIAN) & 0xFFFF);
    }

    @Override
    public int packetSPID() {
        return (buffer().getShort(offset() + 4, java.nio.ByteOrder.BIG_ENDIAN) & 0xFFFF);
    }

}
```

I can understand why one would want to generate final codecs in the  default case. All I am asking is to provide a SBE tool configuration switch, so I can turn off emitting 'final'. **I can contribute such patch, if allowed**, since it is a showstopper for me!

I love SBE and Agrona and how they  allow me to avoid writing  stupid boring buffer-mapping  code!

**Comment by mjpt777** [comment]
Yes we can consider a PR with this option.

**Comment by hrstoyanov** [comment]
Found other solution
