### ISSUE TITLE
The c++ demo can't compiled successfully, however using the 1.16.0 is ok, can someone help fix it

### ISSUE THREAD

**Issue by LavenXu** [real-logic/simple-binary-encoding#842]
C++:
$ mkdir -p cppbuild/Debug
$ cd cppbuild/Debug
$ cmake ../..
$ cmake --build . --clean-first
$ ctest

errors like this ：‘group_with_data_testMessage2::buffer’缺少初始值设定 [-Werror=missing-field-initializers]

**Comment by mjpt777** [comment]
I see no warnings or errors with the head of the repo. What version are you using?
