### ISSUE TITLE
SBE 2.0 status and plans

### ISSUE THREAD

**Issue by hassila** [real-logic/simple-binary-encoding#843]
Hi,

Just wanted to ask a few questions:
- Do you intend to update this project to support SBE 2.0 (https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) - and how does the relationship with the actual FIX standardisation look like?
- If so, what are the plans for such?
- Are you taking PR:s for additional language support if feature complete / with full test suite (specifically Swift)?

Cheers,

Joakim

**Comment by mjpt777** [comment]
We will update the project to support SBE 2.0 if we have commercial sponsorship. At present no customer has been willing to pay for this.

We are more reserved than we have been for supporting new programming languages. In the past we have had contributions, e.g. Rust, that effectively become abandonware and caused a drag on our resources. We are open to PRs if the scope is defined and we understand commitment.

**Comment by hassila** [comment]
Thanks for clarifications @mjpt777, much appreciated.
