### ISSUE TITLE
SBE_NOEXCEPT

### ISSUE THREAD

**Issue by samkhopkar** [real-logic/simple-binary-encoding#851]
Currently C++11 generated code every header has the following

#if __cplusplus >= 201103L
#  define SBE_CONSTEXPR constexpr
#  define SBE_NOEXCEPT noexcept
#else
#  define SBE_CONSTEXPR
#  define SBE_NOEXCEPT
#endif

Is there a way to disable SBE_NOEXCEPT during generation in case we want exceptions thrown for bad corrupt messages sent ?

Thanks
Sam

**Comment by samkhopkar** [comment]
The issue here is when bad/corrupt data is parsed by SBE generated method in the header and it is declared with noexcept and throws exception that causes the app to terminate (throwing exception violates noexcept and calls std::terminate)

We want to be able to catch exceptions for bad data rather than terminate the app. Hence need the ability to optionally remove SBE_NOEXCEPT during generation.

**Comment by ksergey** [comment]
Could you please show generated method with `noexcept` which throws exception?

**Comment by samkhopkar** [comment]
Here is an example from one of our developers for the following schema snippet

    <enum name="PriceType" encodingType="uInt8NULL">
            <validValue name="Limit" description="Limit">1</validValue>
            <validValue name="Market" description="Market">2</validValue>
            <validValue name="Default" description="Default">10</validValue>
    </enum>

   <sbe:message name="OrderSpecSubmitRequest" id="1004">
      <field id="1" name="session_id" type="SessionId"/>
      <field id="2" name="spec_id" type="uInt64"/>
      <field id="3" name="order_contract" type="String16"/>
      <field id="4" name="price_type" type="PriceType"/>
      <field id="5" name="order_market_side" type="MarketSide"/>
      <field id="6" name="time_in_force" type="TimeInForce"/>
      <field id="7" name="post_only" type="BooleanNULL"/>
      <field id="8" name="manual" type="BooleanNULL"/>
   </sbe:message>


static PriceType::Value get(const std::uint8_t value)
    {
        switch (value)
        {
            case 1: return Limit;
            case 2: return Market;
            case 10: return Default;
            case 255: return NULL_VALUE;
        }
        throw std::runtime_error("unknown value for enum PriceType [E103]");
    }

 SBE_NODISCARD PriceType::Value price_type() const SBE_NOEXCEPT
    {
        std::uint8_t val;
        std::memcpy(&val, m_buffer + m_offset + 32, sizeof(std::uint8_t));
        return PriceType::get((val));
    }

**Comment by samkhopkar** [comment]
Apologies. It turns out the above code was generated with 1.14.1 jar.
This is now fixed when generated with latest 1.20.4.1 jar.
Thanks for your patience.
