### ISSUE TITLE
Technical Specification version for SBE the tool can support

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#856]
- what's the latest SBE Technical Specification version can support
- what's the latest C++ version sbe.target.language can support

**Comment by chengm349** [comment]
I used

$ mkdir -p cppbuild/Debug
$ cd cppbuild/Debug
$ cmake ../..
$ cmake --build . --clean-first
$ ctest

but seems $ cmake --build . --clean-first not very good. please check attached and advise.
[result.txt](https://github.com/real-logic/simple-binary-encoding/files/6821981/result.txt)

**Comment by chengm349** [comment]
is there another way to ask question for example by email? Keen to have early reply so I can move my project.

**Comment by tmontgomery** [comment]
SBE version can be found in the XSD. https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/resources/fpl/sbe.xsd#L6 (i.e. Version 1.0 Draft standard.)

C++11 is the minimum as can be seen at https://github.com/real-logic/simple-binary-encoding/blob/master/CMakeLists.txt#L50

Try using `cppbuild` as mentioned in the README. You should look at the GItHub Actions to see any additional details of the vast array of platforms and compilers we run our CI on.

We get to questions as we can. But is often delayed by a while. If you require more support, we offer commercial support. Feel free to reach out to myself or @mjpt777 for details on commercial support offerings.

**Comment by chengm349** [comment]
Hi Todd,

The ticket (#856) was closed. Assume I got jar file correctly eventually and I may run command like this:


java -Dsbe.target.language=cpp98 -jar simple-binary-encoding-1.1.7-RC2/build/libs/sbe-all-1.1.7-RC2.jar templates_FixBinary.xml

should I still use cpp98 or possible C++11 or newer?

I did use cppbuild. If C++11 is the minimum requirement, should I modify some file under cppbuild? Please kindly check the attached result.txt in #856.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tmontgomery** [comment]
SBE Cpp generator only generates C++11.

**Comment by chengm349** [comment]
Hi Todd,

I ran

$ mkdir -p cppbuild/Debug
$ cd cppbuild/Debug
$ cmake ../..
$ cmake --build . --clean-first
$ ctest

But step $ cmake --build . --clean-first not very good (result.txt has all output of this step).

issue #858 advice by Dmitry Vyazelenko<https://github.com/vyazelenko>


java -Dsbe.target.language=cpp -jar ./simple-binary-encoding/sbe-all/build/libs/sbe-all-1.23.1-SNAPSHOT.jar  ilinkbinary.xml
works.

However I’d like to confirm that those error msgs appear in result.txt are acceptable.

Warm Regards.
Ming Cheng

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mjpt777** [comment]
@chengm349 Can you please stop posting a different subject to what the issue title suggests. Either use appropriate subject titles for issues or I will have to block you. Simple rule - one subject per issue.
