### ISSUE TITLE
sbe-tool-1.23.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#858]
I ran 

$ ./gradlew
successfully and only got sbe-tool-1.23.1-SNAPSHOT.jar under sbe-tool/build/libs
I tried to run command

$ java -Dsbe.target.language=cpp98 -jar ./simple-binary-encoding/sbe-tool/build/libs/sbe-tool-1.23.1-SNAPSHOT.jar ilinkbinary.xml

but got error:
no main manifest attribute, in ./simple-binary-encoding/sbe-tool/build/libs/sbe-tool-1.23.1-SNAPSHOT.jar

**Comment by vyazelenko** [comment]
@chengm349 The correct command you are looking for is:
```bash
java -Dsbe.target.language=cpp98 -cp ./simple-binary-encoding/sbe-tool/build/libs/sbe-tool-1.23.1-SNAPSHOT.jar uk.co.real_logic.sbe.SbeTool ilinkbinary.xml
```
Note that the jar is specified for a classpath attribute and that the main class `uk.co.real_logic.sbe.SbeTool` is specified explicitly.

**Comment by vyazelenko** [comment]
@chengm349 You should either:
- Use `sbe-all` jar, i.e. run:
  ```bash
  java -Dsbe.target.language=cpp98 -jar ./simple-binary-encoding/sbe-all/build/libs/sbe-all-1.23.1-SNAPSHOT.jar  ilinkbinary.xml
  ```
- Or you'll have to manually specify the classpath including the Agrona dependency, i.e. something along the lines of:
  ```
  java -Dsbe.target.language=cpp98 -cp ./simple-binary-encoding/sbe-tool/build/libs/sbe-tool-1.23.1-SNAPSHOT.jar;~/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/1.11.0/22fcd9d1091f13e7fcd89cc16784f24dfc843c59/agrona-1.11.0.jar uk.co.real_logic.sbe.SbeTool ilinkbinary.xml
  ```
  Note, that you also have to specify the main class `uk.co.real_logic.sbe.SbeTool` in this case.
