### ISSUE TITLE
C++ Build using CMake error

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#859]
I ran (my cmake version is of 3.20):

$ mkdir -p cppbuild/Debug
$ cd cppbuild/Debug
$ cmake ../..
$ cmake --build . --clean-first
$ ctest

But step 4 (cmake --build . --clean-first) prompted some error as recorded in the attached file. Just want to know whether these errors are acceptable or I should solve them.
[result.txt](https://github.com/real-logic/simple-binary-encoding/files/6835817/result.txt)

**Comment by mikeb01** [comment]
This set of commands works fine with GCC 10.  The error suggests that you are not using a C++ 11 compliant compiler.

**Comment by lynxzp** [comment]
Hi, I'm not about this error, but about another error with gcc 11.1.0 and gtest.

I had only one error: `simple-binary-encoding/cppbuild/Release/thirdparty/gtest/src/gtest/googletest/src/gtest-death-test.cc:1301:24: error: dummy may be used uninitialized [-Werror=maybe-uninitialized]`
after changing 1301 line to `int dummy=0;` gtest will successfully built and pass

This is offtop, maybe not issue, but can help.

**Comment by chengm349** [comment]
I checked CMakeCXXCompiler.cmake content:
set(CMAKE_CXX_COMPILER "/bin/c++")
set(CMAKE_CXX_COMPILER_ARG1 "")
set(CMAKE_CXX_COMPILER_ID "GNU")
set(CMAKE_CXX_COMPILER_VERSION "4.8.5")
set(CMAKE_CXX_COMPILER_VERSION_INTERNAL "")
set(CMAKE_CXX_COMPILER_WRAPPER "")
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "98")

by running
/bin/c++ --version
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I thought I was using C++ 11 compliant compiler. I have c++20 GCC compliant compiler. please advice how to force "$ cmake --build . --clean-first" to use latest compiler on my platform.

**Comment by mikeb01** [comment]
https://www.google.com/search?channel=fs&client=ubuntu&q=cmake+set+compiler

**Comment by chengm349** [comment]
Hi Michael Barker,

Everything is ok now.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
