### ISSUE TITLE
Project icon

### ISSUE THREAD

**Issue by MarcinOrlowski** [real-logic/simple-binary-encoding#864]
We need something better than this:

![logisim-icon-128](https://user-images.githubusercontent.com/8041294/129462363-cb0aed55-830d-4689-a042-7e5e812242b2.png)

Anyone with artistic skills, please contribute. 

The only requirement for your contributions: it **MUST** be a SVG (vector) file. [Inskape](https://inkscape.org/)? [Krtita](https://krita.org/en/)? [Whatever](https://www.google.com/search?hl=en&q=free%20vector%20drawing%20app). Please contribute only SVG files though.

**Comment by mjpt777** [comment]
@MarcinOrlowski What is the relevance of this?

**Comment by MarcinOrlowski** [comment]
Interesting. I was intended to post it to completely different repo. Not sure how I even ended here :)
