### ISSUE TITLE
New string field after group block

### ISSUE THREAD

**Issue by samkhopkar** [real-logic/simple-binary-encoding#868]
I have the following SBE message to which I need to add second field after group block as shown below
```
<sbe:message name="SubscribeRequest" id="1007">
      <group dimensionType="groupSizeEncoding8" id="2" name="InternalSymbols">
          <field id="1" name="symbol" type="char20"/>
      </group>
  </sbe:message>
```

New field
`<field id="2" name="username" type="char30" sinceVersion="2"/>`

1) Is that valid to add a new field after group block - will it be backward compatible ?

2) Would the root block length be now 30 for new version and zero for old version ?

**Comment by mjpt777** [comment]
Adding new fields is possible and part of versioning support. You can read up on the [SBE specification](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding) or ask a question on Stackoverflow if you do not have commercial support from us.
