### ISSUE TITLE
Will the utility help to fill Message Size

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#873]
Let me take Negotiate200.h generated by real-logic tool as an example. A valid Negotiate200 message to CME should be Packet Header + MDP message as inidicated in the below link.

https://www.cmegroup.com/confluence/download/attachments/170262771/ConflatedTCPPacketStructure.png?version=2&modificationDate=1617896706155&api=v2 1

My code will provide Packet Header. Seems wrapAndApplyHeader() will fill Simple Binary Header part. Who will provide Message Size? Of course I can call sbeBlockAndHeaderLength() to fill it. Is there any better way?

BTW, when to call wrapForEncode()?

**Comment by ksergey** [comment]
>> Who will provide Message Size? 
you should calculate message size by yourself

>> Of course I can call sbeBlockAndHeaderLength() to fill it
it's not enough for messages with repeating groups or variable length fields

>> BTW, when to call wrapForEncode()?
don't need to call in case of `wrapAndApplyHeader()` called
