### ISSUE TITLE
Deprecated messages should result in their en/decoders marked with @Deprecated

### ISSUE THREAD

**Issue by ratcashdev** [real-logic/simple-binary-encoding#875]
given a definition like
```xml
<sbe:message name="MyDeprecatedMessage" id="123"
    description="old message that was deprecated in version 45" deprecated="45">
```
its respective java encoder and decoder should be marked with the `@Deprecated` annotation so that users get compile time warnings when still using old messages.

Happy to submit a PR, if this issue and objectives are accepted.

**Comment by mjpt777** [comment]
I'd be happy to review an PR on this.
