### ISSUE TITLE
How to add optional group

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#879]
Take CME's MDInstrumentDefinitionFX63 template for example. I now want to add a NoInstAttrib group entry.
assume I created a MDInstrumentDefinitionFX63 message m63:
MDInstrumentDefinitionFX63 m63{};
m63..wrapForEncode(buffer, 0, bsiz)); // bsiz is the size of buffer
I thought I should call:

auto& noInstAttrib = m63.noInstAttribCount(1);
My code crashed. I guess I might not use offset properly when I created m63.  please guide how to add an optional group. Here I am talking C++ env.

**Comment by chengm349** [comment]
I know it's just a question. Is there any simple-binary-encoding user group (not FIX one)? I tried FIX SBE user group, but people there said that mine should go to real logic bcos it's related an implementation.

**Comment by ksergey** [comment]
Where exactly your code crashes? 

The code should looks like
```
auto group = msg.noInstAttribCount(1);
group.next();
// now fill group entry
```

**Comment by chengm349** [comment]
Thanks. call next() solved the problem. And also found that when add an optional group, certain other group(s) is a must also.
