### ISSUE TITLE
Unable to access random elements from the message using C++ generated code

### ISSUE THREAD

**Issue by avikas974** [real-logic/simple-binary-encoding#881]
i got the schema as follows. I am creating the C++ object of TestFIX class and populating it manually. Now when i try to access value of group2 directly then it does not work and returns junk. Though it works fine if i access group1 first and call next() on that. Seems, m_position is not set correctly if values are not accessed in sequence.

c++ code
----------------------------
TestFIX testfix(buffer, 2048);
testfix.group2();
testfix.next();
std::cout << testfix.elem5() << std::endl;

schema
---------------------------
```
<sbe:message name="TestFIX" id="1" description="Parent">
  <field name="elem1" id="1" type="uint32" semanticType="int"/>
  <field name="elem2" id="2" type="fixedString30" presence="optional"/>
  <group name="group1" id="3">
      <field name="elem3" id="4" type="uint32"/>
  </group>
  <group name="group2" id="5">
      <field name="elem4" id="6" type="uint32"/>
      <field name="elem5" id="7" type="fixedString30" presence="optional"/>
      <group name="sgroup1" id="8">
        <field name="elem6" id="9" type="uint32"/>
        <field name="elem7" id="10" type="fixedString30"/>
      </group>
  </group>
</sbe:message>
```

**Comment by ksergey** [comment]
it feature, not a bug =)
https://github.com/real-logic/simple-binary-encoding/wiki/Design-Principles

**Comment by avikas974** [comment]
> it feature, not a bug =) https://github.com/real-logic/simple-binary-encoding/wiki/Design-Principles

I can see that elements can be accessed randomly since you know the offset already of each elements.

Only issue I see is with the groups and i can understand why because you dont know, how many repeating group elements will be added. I think that is easy to resolve if you add 1byte storing repeating group count for each group and then only start storing group elements. This was you can easily calculate offset of each group elements irrespective of repeating groups.

**Comment by ksergey** [comment]
repeating group could include another repeating group or groups or variable length fields

**Comment by avikas974** [comment]
> repeating group could include another repeating group or groups or variable length fields

I think that should be ok if you keep storing 1byte repeating group count info before each group.
Basically, you will know that each group will start with 1byte of group info that can be used to calculate the offset of any element inside that group.

**Comment by mjpt777** [comment]
@avikas974 SBE is a standard and discussing changes in the standard is not valid here. Please consider having such a discussion [here](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding).

**Comment by donmendelson** [comment]
A proposal has already been made for SBE v2.x to add fields to message header to support adding new groups and variable-length fields. You may review and comment in the standards project.

**Comment by avikas974** [comment]
> @avikas974 SBE is a standard and discussing changes in the standard is not valid here. Please consider having such a discussion [here](https://github.com/FIXTradingCommunity/fix-simple-binary-encoding).

Sure. Thx
