### ISSUE TITLE
Is it possible to create a generic base class of all the message class generated for C++

### ISSUE THREAD

**Issue by avikas974** [real-logic/simple-binary-encoding#883]
If all the message class generated for C++ can have a generic base class then it will make life very easy.

**Comment by mjpt777** [comment]
I'm closing this as it is too vague and not clear what the benefit is.

**Comment by avikas974** [comment]
> I'm closing this as it is too vague and not clear what the benefit is.

I am creating a factory of SBE messages and would like to return SBE object based on the basis of sbe message received but unable to return since actual SBE type is not known. If all SBE messages classes were derived from common SBE message class then i could have defined the factory method() returning the message base class that would have made my life easy.

**Comment by mjpt777** [comment]
We are happy to consider PRs and we also offer commercial support.
