### ISSUE TITLE
[Java] toString() shouldn't disturb repeating groups

### ISSUE THREAD

**Issue by spoerri** [real-logic/simple-binary-encoding#890]
Calling `toString()` in the middle of decoding a repeating group breaks the decoding of that group. For example, subsequent entries are skipped:

```
for (MyGroupDecoder member : decoder.myGroup()) {
    logger.debug(decoder);
    handle(member.myValue());
}
```
Only the first member of the repeating group will be handled.

The fix should be pretty simple: generate code into the `appendTo` method to save and restore `index` and `offset` when handling each group, similar to how it already saves and restores `limit`.

**Comment by krisso-rtb** [comment]
Is this fix merged to master?
I'm looking at `sbe-all-1.27.0` and it seems to missing the fix.

**Comment by krisso-rtb** [comment]
It looks like it's either partially merged or partially rolled back :) 
```
append(sb, indent, "int " + groupName + "OriginalOffset = " + groupName + ".offset;");
append(sb, indent, "int " + groupName + "OriginalIndex = " + groupName + ".index;");
```
Above is missing, below is present in `1.27.0`:
```
append(sb, indent, groupName + ".offset = " + groupName + "OriginalOffset;");
append(sb, indent, groupName + ".index = " + groupName + "OriginalIndex;");
```

**Comment by mjpt777** [comment]
@krisso-rtb If you think there is a remaining problem then please create a new issue with a test that demonstrates it.
