### ISSUE TITLE
[java] Provide a raw getter method for bitmaps

### ISSUE THREAD

**Issue by LucaMerello** [real-logic/simple-binary-encoding#893]
Exactly as it happens for enums, for which the decoder also provides a get method for the raw version of the data, for example:

     public byte exchangeCodeRaw ()
     {
         return buffer.getByte(offset + 18);
     }

     public ExchangeCode_enum exchangeCode ()
     {
         return ExchangeCode_enum.get(buffer.getByte(offset + 18));
     }

It would be useful to have the same raw information in the case of bitmaps. Now, to be able to get it, you need to have access to the buffer and the offset from outside the decoder and compose them as follows:

    decoder.mMProtections().buffer().getByte(decoder.mMProtections().offset());

It would be easier and safer to get the same data in the following way:

    byte bitmap = decoder.mMProtections().getRaw();

where MMProtections_setDecoder provides:

    public byte getRaw()
    {
        return buffer.getByte(offset);
    }

**Comment by tmontgomery** [comment]
This seems useful. @mjpt777 @vyazelenko @mikeb01 what do you all think?

**Comment by mjpt777** [comment]
I'd be fine with this.
