### ISSUE TITLE
Adding New Enums With SinceVersion

### ISSUE THREAD

**Issue by adkapur** [real-logic/simple-binary-encoding#901]
Hi I just wanted to follow up regarding this old issue to see if it was fixed or not —> https://github.com/real-logic/simple-binary-encoding/issues/411

CME is using RL version 1.8.1 and it is throwing an exception for an enum value added with a later since version for a consumer with an older schema version

There was a fix made for this as per —> https://github.com/real-logic/simple-binary-encoding/pull/548 in version 1.7.10 in which the if condition was removed for null value but not for unknown values

**Comment by mjpt777** [comment]
There is an option for code generation that lets you control the behaviour with `sbe.decode.unknown.enum.values`.

https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

**Comment by adkapur** [comment]
Thanks Martin
