### ISSUE TITLE
encoding order for field of an item in repeating groups

### ISSUE THREAD

**Issue by ssh352** [real-logic/simple-binary-encoding#905]
is it recommended to encode per declare order in schema file?

I ask the question because mDEntryPx().mantissa() can't be chained. So could I encode such types In the end?

**Comment by mjpt777** [comment]
The SBE specification requires fields to be encoded and decoded in order. There are some cases where this can be relaxed but unless you take time to understand the implementation then it is best sticking to the order. Decoding and encoding in order are the best way to get great performance.
