### ISSUE TITLE
No-copy encoding for varStringEncoding

### ISSUE THREAD

**Issue by RainM** [real-logic/simple-binary-encoding#907]
Hi,

Just working with SBE. I try to separate some layers of application logic between each other. Something like OSI encoding, where a message has header and 'payload' and payload could be decoded higher layer of logic. And I've faced an issue with copy-free encoding for such message. 

In XML schema I have something like:

```
<composite name="varStringEncoding">
    <type name="length" primitiveType="uint32" maxValue="1073741824"/>
    <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8"/>
</composite>
    ...
<sbe:message name="RequestMessage" id="4">
    <field name="requestId" id="5" type="uint32"/>
    <data name="payload" id="7" type="varStringEncoding"/>
</sbe:message>
```

And in Encoder I get three methods for payload encoding:

```
public RequestMessageEncoder putPayload(final DirectBuffer src, final int srcOffset, final int length)
public RequestMessageEncoder putPayload(final byte[] src, final int srcOffset, final int length)
public RequestMessageEncoder payload(final String value)
```

All three methods implicitly require some external buffer to be encoded somewhere outside. And all these three methods copy data from this buffer to underlying buffer.

So, is there any option to wrap ByteBuffer over existing buffer and get rid of this copy? I implemented 'manual' encoding (I write payload length and data directly to encoder's), but it looks really ugly. Or may be it's better to add this feature to sbetool?

--Sergey

**Comment by mjpt777** [comment]
If you are writing strings rather than binary primitives then the performance game is already lost for your main data. It's complex but possible to encode directly into the buffer and not something we recommend to customers unless all other options have been ruled out.
