### ISSUE TITLE
Groups  limit been removed ?

### ISSUE THREAD

**Issue by supergaga** [real-logic/simple-binary-encoding#912]
`When numInGroup type is set to uint8, a group element may contain up to 256 entities. This type can be set to uint16 in order for the group to contain up to 65,536 entities. A group cannot contain more than 65,536 entities.`

In the previous version, there was this description, but I can't find it now. Is this restriction removed?

**Comment by tmontgomery** [comment]
There is still a warning here. https://github.com/real-logic/simple-binary-encoding/blob/727281a26157a244947ec8c8afa92176c3f98a9b/sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/CompositeType.java#L207

**Comment by supergaga** [comment]
> 

Okay, Perhaps a more salient explanation in docs would have been helpful in the early use.

**Comment by tmontgomery** [comment]
Sure. Feel free to send us a PR that makes the most sense.
