### ISSUE TITLE
Is nullValue mandatory for enum with primitive encodingType?

### ISSUE THREAD

**Issue by isliser** [real-logic/simple-binary-encoding#916]
I don't understand why optional enum with primitive encodingType is failed to parse if there is no nullValue specified. I assume that the default primitive's nullValue should be used in that case. For example, XmlSchemaParser throws an exception for a schema with
```
<enum name="tradingStatus" encodingType="uint8" presence="optional">
    <validValue name="ACTIVE">0</validValue>
    <validValue name="CLOSED">1</validValue>
</enum>
```
Exception
`ERROR: at <types><enum name="tradingStatus"> presence optional but no null value found`
Is it a bug in the parser or the nullValue is mandatory here?

**Comment by jkolobok** [comment]
Which version are you using? this issue may be related https://github.com/real-logic/simple-binary-encoding/issues/917

**Comment by isliser** [comment]
1.19.0. Tried with with 1.27.0 is the problem is gone!
