### ISSUE TITLE
Regression: incorrect null value for char enums

### ISSUE THREAD

**Issue by jkolobok** [real-logic/simple-binary-encoding#917]
I use ilink binary schema.
For CmtaGiveUpCD enum it generates incorrect code for null value. 
generated:
    NULL_VAL((byte)48); //48=='0'
must be 
    NULL_VAL((byte)0);

it was working fine on 1.25.1 and got broken in 1.26

**Comment by jkolobok** [comment]
This issue probably caused the problem https://github.com/real-logic/simple-binary-encoding/issues/889

**Comment by mjpt777** [comment]
The iLink 3 schema defines `CmtaGiveUpCD`  of encoded type `charNULL`.

```xml
    <type name="charNULL" description="Char with null value" presence="optional" nullValue="0" primitiveType="char" semanticType="char"/>
```

This means the generated code is correct for a char type as "0" is 48 ASCII. Also note:

> Note that the code point U+0000, assigned to the null control character, is the only character encoded in Unicode and ISO/IEC 10646 that is always invalid in any XML 1.0 and 1.1 document.

https://en.wikipedia.org/wiki/Valid_characters_in_XML#Characters_allowed_but_discouraged

It would make sense to take up this issue with the CME. They could resolve this by not defining the `nullValue` attribute on `charNULL`.
