### ISSUE TITLE
Socket InputStream Java example

### ISSUE THREAD

**Issue by aesirot** [real-logic/simple-binary-encoding#920]
Hello, Please help with decoding from socket InputStream example, or just advice am I doing right.

My current logic:
1) read from input stream byte[] with fixed size 16000
2) check that full header is in byte[], then check that message is full. If yes - wrap() it, process and try to read next message in byte[] . If no - copy partial message and return to 1

Thanks

**Comment by mikeb01** [comment]
That logic is largely correct.  One optimisation I often use it is that in case of a short read (i.e. the full message is not received), rather than do the partial copy, reuse the buffer, but set the offset to the end of the fragment received and adjust the length accordingly.
