### ISSUE TITLE
Enum optional field with primitive encoding are not behaving as optional

### ISSUE THREAD

**Issue by bhaskar-galaxy** [real-logic/simple-binary-encoding#927]
SBE version 1.27.0

Enum type defined as below:
```  
    <enum name="OrderStatus" encodingType="uint8">
        <validValue name="OPEN">2</validValue>
        <validValue name="CANCELLED">5</validValue>
    <enum>
```    
in the message schema it is marked as optional
```
   <field name="orderStatus" id="11" type="OrderStatus"
               description="" presence="optional"/>    
```
The class is generated with a NULL_VALUE:

```

    /**
     * To be used to represent not present or null.
     */
    NULL_VAL((short)255);
```

When the field orderStatus is not set while encoding, it is not set to NULL_VALUE but instead gets the default primitive value of 0. so when the message is decoded it throws an exception:

```

java.lang.IllegalArgumentException: Unknown value: 0
	at codecs.OrderType.get(OrderType.java:48)
	
```

**Comment by tmontgomery** [comment]
Worse than that, it could be anything in the memory at that location. You will want to set the value when encoding. Just because it is not encoded doesn't mean it is set to NULL_VAL. It must be set to NULL_VAL.

**Comment by bhaskar-galaxy** [comment]
@tmontgomery thanks for responding. i had the same question after looking at code, how does "optional" fields work. Since codec uses previous allocated buffer and there is no default buffer that gets copied over that will reset the buffer, chances are if you have optional fields and don't specify a value it will be carry the previous message value.
