### ISSUE TITLE
SbeTool upgrade to support FIX -SBE Version 2.0–RC2 compatible code generation.

### ISSUE THREAD

**Issue by orsanakbaba** [real-logic/simple-binary-encoding#928]
I try to develop a simple sbe and netty co-working tutorial example on the github.
[orsanakbaba/sbe-netty-tcp-example](https://github.com/orsanakbaba/sbe-netty-tcp-example) project simply use netty-transport features for Client and Server TCP raw socket IPC method. I use sbe for encoder/decoder of raw socket messages.

When the Server read operation try to check whether all fragments of the sbe message arrived or not, netty(tutorials) suggest and i use following way to detect completeness of a message, if arrived length of byte array is not enough then simply return
```java
if (in.readableBytes() < MessageHeaderDecoder.ENCODED_LENGTH + CarDecoder.BLOCK_LENGTH) {
            ChannelFuture future = ctx.writeAndFlush(null);
            future.addListener(ChannelFutureListener.CLOSE);
            return;
}
```  
But 
```java 
(MessageHeaderDecoder.ENCODED_LENGTH + CarDecoder.BLOCK_LENGTH)
```   
expression solely return an empty Car message length (there is no neither repeating groups nor variable-length fields) with even empty strings. This not a convenient way then passing to the decoding phase because almost none of incoming messages is not empty, and the code will mostly try to decode incomplete messages. 

My investigation on [FIX Simple Binary Encoding (SBE) Technical Specification Version 2.0 – Release Candidate 2 – August 13, 2019 Section Message header schema](https://www.fixtrading.org/standards/sbe-online/#sbe-message-encoding-header) open the floodgates. 
MessageHeader composite have following (have ```xml <type name="numGroups" primitiveType="uint16" />, <type name="numVarDataFields" primitiveType="uint16" /> ```) fields in SBE V2-RC2.
```xml
<composite name="messageHeader" description="Template ID and length of message root">
    <type name="blockLength" primitiveType="uint16"/>
    <type name="templateId" primitiveType="uint16"/>
    <type name="schemaId" primitiveType="uint16"/>
    <type name="version" primitiveType="uint16"/>
    <type name="numGroups" primitiveType="uint16" />
    <type name="numVarDataFields" primitiveType="uint16" />
</composite>
```

As a conclusion, 

- if SbeTool code generation supports SbeTool SBE V2-RC2
- And, if generated header encoder classes have capability to calculate and set the blockLength, numGroups, numVarDataFields fields then aforementioned completeness test problem may not have arise.

Thanks.

**Comment by vyazelenko** [comment]
@orsanakbaba I don't see how having the `numGroups` and `numVarDataFields` fields will help with the length check?
What you are really after is the `totalLength` field that will contain the length of the entire message including the composites and var-length fields. You can provide your own framing protocol by wrapping each message in a custom header that will contain such field. 

NB: For the messages without composites and var-length fields the `BLOCK_LENGTH` is the length of the entire message.

**Comment by orsanakbaba** [comment]
> @orsanakbaba I don't see how having the `numGroups` and `numVarDataFields` fields will help with the length check? What you are really after is the `totalLength` field that will contain the length of the entire message including the composites and var-length fields. You can provide your own framing protocol by wrapping each message in a custom header that will contain such field.
> 
> NB: For the messages without composites and var-length fields the `BLOCK_LENGTH` is the length of the entire message.

You are right it is not completely help to get overcome to message incompleteness.
Adding a totalLength field to the messageHeader and on the encoding side fill it with (MessageHeaderEncoder.ENCODED_LENGTH + car.encodedLength()) is  removed the problem in that case, but also brakes the FIX standard compliance as well.

```xml
 <composite name="messageHeader" description="Message identifiers and length of message root.">
        <type name="blockLength" primitiveType="uint16"/>
        <type name="templateId" primitiveType="uint16"/>
        <type name="schemaId" primitiveType="uint16"/>
        <type name="version" primitiveType="uint16"/>
        <type name="totalLength" primitiveType="uint16"/>
    </composite>
```

Thanks a lot.

**Comment by mjpt777** [comment]
SBE is designed to be encapsulated in another protocol. This works well in Aeron for example. The FIX organisation recommend the use of [SOFH](https://www.fixtrading.org/standards/fix-sofh/) to encapsulate SBE.
