### ISSUE TITLE
Group of ref to message not supported?

### ISSUE THREAD

**Issue by haydenflinner** [real-logic/simple-binary-encoding#933]
I am surprised the xml compiler lets code be generated from this with no warnings, but maybe I am misunderstanding what `<ref>` is supposed to mean. The result is that in both Rust and C++ generated code there is no reference to this `refField` part of the MyUpdate.deltas. Only `normalField` is there.

```xml
    <message name="MyDelta" id="20" sinceVersion="0">
      <field name="field" id="0" type="int32" offset="0"/>
      <field name="amt" id="1" type="double"/>
    </message>

    <message name="MyUpdate" id="19" semanticType="d" sinceVersion="0">
      <field name="carId" id="0" type="uint32" offset="0"/>
      <group name="deltas" id="10" dimensionType="GroupSize">
        <!-- I assumed this would work more or less the same as inlining the MyDelta definition here, just accessed like curDelta.refField.field() -->
        <ref name="refField" id="1" type="MyDelta"/>
        <field name="normalField" id="2" type="int64"/>
      </group>
    </message>
```

**Comment by haydenflinner** [comment]
I adjusted that, still wasn't getting any of my fields on the composite type to appear. Turns out that this is another problem which the compiler allows / silently ignores: using 'field' rather than 'type' in a composite.

```
-        <composite name="MyDelta">
-            <field name="field" id="0" type="MyOtherType">
-            <field name="amt" id="1" type="double"/>
+        <composite name="MyDelta">
+            <ref name="field" type="MyOtherType"/>
+            <type name="amt" primitiveType="double"/>
```

**Comment by mjpt777** [comment]
Turn on schema validation to see what is allowed.

https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide

https://github.com/real-logic/simple-binary-encoding/blob/master/build.gradle#L263
