### ISSUE TITLE
about run SebTool error

### ISSUE THREAD

**Issue by kuangtu** [real-logic/simple-binary-encoding#934]
My simple-binary-encoding-master version is:1.27.1  Java version is:11.0.9
The Build Process is finished and output the jars.
sbe-benchmarks/build/libs
sbe-samples/build/libs
sbe-tool/build/libs
sbe-all/build/libs

But when I output source files with schema:
simple-binary-encoding-master\sbe-samples\build\resources\main\example-schema.xml
java -Dsbe.generate.ir=true -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe -Dsbe.output.dir=include/gen -Dsbe.errorLog=yes -jar sbe-all/build/libs/sbe-all-1.27.1-SNAPSHOT.jar  C:\tmp\simple-binary-encoding-master\sbe-samples\build\resources\main\example-schema.xml

The Error is:
ERROR: at <sbe:message name="Car"> <group name="fuelFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="fuelFigures"> <data name="usageDescription"> could not find type: varAsciiEncoding
ERROR: at <sbe:message name="Car"> <group name="performanceFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="performanceFigures"> <group name="acceleration"> could not find dimensionType: groupSizeEncoding
ERROR: at <sbe:message name="Car"> <data name="manufacturer"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="model"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="activationCode"> could not find type: varAsciiEncoding
Exception in thread "main" java.lang.IllegalStateException: had 7 errors
        at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit(ErrorHandler.java:107)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:140)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:331)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:232)

I copy the types in common-types.xml into example-schema.xml.
<?xml version="1.0" encoding="UTF-8"?>
<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe"
                   xmlns:xi="http://www.w3.org/2001/XInclude"
                   package="baseline"
                   id="1"
                   version="0"
                   semanticVersion="5.2"
                   description="Example base schema which can be extended."
                   byteOrder="littleEndian">
    <types>
        <composite name="messageHeader" description="Message identifiers and length of message root.">
        <type name="blockLength" primitiveType="uint16"/>
        <type name="templateId" primitiveType="uint16"/>
        <type name="schemaId" primitiveType="uint16"/>
        <type name="version" primitiveType="uint16"/>
    </composite>
    <composite name="groupSizeEncoding" description="Repeating group dimensions.">
        <type name="blockLength" primitiveType="uint16"/>
        <type name="numInGroup" primitiveType="uint16"/>
    </composite>

It generates source files and it's ok. Is there anything wrong? 
Thanks

**Comment by mjpt777** [comment]
Can you try with `-jar ...` as the first argument?

**Comment by vyazelenko** [comment]
@kuangtu Your error is due to the XSD includes not being resolved. You can fix it by adding the `-Dsbe.xinclude.aware=true` option before the `-jar`.

**Comment by vyazelenko** [comment]
@officialspicey It looks like you are seeing some sort of shell issue or a copy paste error which results in removal of the `-Dsbe` prefix from the system properties. Which renders the command invalid, i.e.:
```
$ java .generate.ir=true .target.language=Cpp .target.namespace=sbe .output.dir=include/gen .errorLog=yes -jar sbe-all/build/libs/sbe-all-1.27.1-SNAPSHOT.jar ...
```
See my reply in #935.

**Comment by kuangtu** [comment]
> @kuangtu Your error is due to the XSD includes not being resolved. You can fix it by adding the `-Dsbe.xinclude.aware=true` option before the `-jar`.

It works, Thanks!

**Comment by Scalaaaaaa** [comment]
在types便签里增加下面的配置，应该就可以了，我这样操作就可以

**Comment by Scalaaaaaa** [comment]
<composite name="groupSizeEncoding">
<type name="blockLength" primitiveType="uint16"/>
<type name="numInGroup" primitiveType="uint16"/>
<type name="numGroups" primitiveType="uint16" />
<type name="numVarDataFields" primitiveType="uint32" />
</composite>

**Comment by Scalaaaaaa** [comment]
在types里增加下面的配置就可以了，
```
<composite name="groupSizeEncoding">
<type name="blockLength" primitiveType="uint16"/>
<type name="numInGroup" primitiveType="uint16"/>
<type name="numGroups" primitiveType="uint16" />
<type name="numVarDataFields" primitiveType="uint32" />
</composite>
```
