### ISSUE TITLE
Cannot generate C++ stubs using the Java Compiler

### ISSUE THREAD

**Issue by officialspicey** [real-logic/simple-binary-encoding#935]
I ran the C++ Build using CMake as specified on the documentation. I didn't run into any errors and was able to generate .jar file in my sbe-all/build/libs/ folder. When I try to generate a C++ stub using the sbe-tool Java compiler, I run into errors. Running this command as specified on the docs 
```
java -Dsbe.generate.ir=true -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe -Dsbe.output.dir=include/gen -Dsbe.errorLog=yes -jar sbe-samples/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml
```

gets me this error:
```
Error: Could not find or load main class .generate.ir=true
Caused by: java.lang.ClassNotFoundException: /generate/ir=true
```
 
I tried this command based on what I saw from another website:
```
java -jar sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml -Dlanguage=Cpp -Dgenerate.ir=true
```

but it gives me this error:
```
ERROR: at <sbe:message name="Car"> <group name="fuelFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="fuelFigures"> <data name="usageDescription"> could not find type: varAsciiEncoding
ERROR: at <sbe:message name="Car"> <group name="performanceFigures"> could not find dimensionType: 
groupSizeEncoding
ERROR: at <group name="performanceFigures"> <group name="acceleration"> could not find dimensionType: groupSizeEncoding
ERROR: at <sbe:message name="Car"> <data name="manufacturer"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="model"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="activationCode"> could not find type: varAsciiEncoding
Exception in thread "main" java.lang.IllegalStateException: had 7 errors
        at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit(ErrorHandler.java:107)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:141)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:331)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:232)
```

I also added this flag `-Dsbe.xinclude.aware=true` as suggested from another website, but it yields a similar error.

Did I miss any intermediate steps prior to using the .jar file? I was able to do the C++ build with CMake and the corresponding ctest.

**Comment by vyazelenko** [comment]
You have to put all system properties before the `-jar` option otherwise they will be interpreted as the program arguments.

The following steps worked for me:
* Build SBE using `./gradlew assemble`.
*Run the following command from the project's root directory:
```bash
$ java -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe -Dsbe.output.dir=include/gen -Dsbe.errorLog=yes  -Dsbe.xinclude.aware=true -jar sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml
```

**Comment by officialspicey** [comment]
Hey @vyazelenko. Thank you for your response. I rebuilt SBE using `gradlew assemble` then ran the command you mentioned. I still get a similar error:
```
$ java -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe -Dsbe.output.dir=include/gen -Dsbe.errorLog=yes  -Dsbe.xinclude.aware=true -jar sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml
Error: Could not find or load main class .target.language=Cpp
Caused by: java.lang.ClassNotFoundException: /target/language=Cpp
```

**Comment by officialspicey** [comment]
Hey Dmitry. Thank you for your response. I rebuilt SBE using gradlew
assemble then ran the command you mentioned. I still get a similar error:

$ java -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe
-Dsbe.output.dir=include/gen -Dsbe.errorLog=yes
-Dsbe.xinclude.aware=true -jar
sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar
sbe-samples/src/main/resources/example-schema.xml
Error: Could not find or load main class .target.language=Cpp
Caused by: java.lang.ClassNotFoundException: /target/language=Cpp

**Comment by vyazelenko** [comment]
@officialspicey Your issue is between the `java` and your shell. 
You are trying to execute the following command:
```
$ java -Dsbe.target.language=Cpp -Dsbe.target.namespace=sbe -Dsbe.output.dir=include/gen -Dsbe.errorLog=yes  -Dsbe.xinclude.aware=true -jar sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml
```
But what seems to be executed is actually:
```
$ java .target.language=Cpp .target.namespace=sbe .output.dir=include/gen .errorLog=yes  .xinclude.aware=true -jar sbe-all/build/libs/sbe-all-1.29.0-SNAPSHOT.jar sbe-samples/src/main/resources/example-schema.xml
```
Note how `-Dsbe` disappeared from the command line. When this happens the `java` process will try to load a class named `.target.language=Cpp` which is reflected in the error you are getting.

Which platform your are on (Windows, Linux)?
Which Java version you are using?

**Comment by vyazelenko** [comment]
@officialspicey Try running that command in a different shell, e.g. PowerShell, cmd, git-bash etc.

**Comment by officialspicey** [comment]
Seems to be a shell issue indeed. It's working on command prompt. Thanks a lot @vyazelenko
