### ISSUE TITLE
Up to date templates_FixBinary.xml?

### ISSUE THREAD

**Issue by odeheurles** [real-logic/simple-binary-encoding#95]
I've added a build step on the .NET side to check that the templates_FixBinary.xml from CME generates valid stubs and compiles.

We recently introduced shemaId header field and I was wondering when a new templates_FixBinary.xml will be issued and will contain definitions for schemaId?

I've disabled this test for now and will re-enable once I have the latest xml.

**Comment by mjpt777** [comment]
Closing as C# is no longer supported as of RC3 unless someone wants to contribute a port.
