### ISSUE TITLE
Allow group after data

### ISSUE THREAD

**Issue by ratcashdev** [real-logic/simple-binary-encoding#954]
Given a message like:
```xml
    <group name="mygroup" id="100">
      <field name="entry" id="101" type="MyGroup"/>
    </group>

    <group name="mygroup2" id="200" sinceVersion="2">
      <field name="entry" id="201" type="MyGroup"/>
    </group>
    
    <data name="msg" id="1000" type="String"/>
```

the forward compatibility (Version2 message sent to Version1 receiver) is broken - the Version1 receiver will not be able to read the content of the `data` tag in a message generated by Version2 sender.

Based on my understanding of the way the decoders work, if  `mygroup2` followed after `data`, then the Version1 receiver would be able to read the `data` tag correctly. Unfortunately, build-time checks reject this kind of structure. The wiki also states that `All <group> elements must precede all <data> elements. ` with the explanation that `This ordering ensures that all fixed length fields are at the front of the message.` I don't see how not allowing `group` after `data` relates to the above, especially since `group` tags may contain nested  `data` tags.

Are there some other considerations that mandate data fields being the absolute last?

**Comment by mjpt777** [comment]
The SBE spec restricts the order of declaration.

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/resources/fpl/sbe.xsd

Adding a new group is not supported with version 1.0 of SBE. SBE 2.0 does support this but the spec if not yet final.

**Comment by mjpt777** [comment]
That would not work but this is turning into a bigger discussion on protocol design.
