### ISSUE TITLE
Bug introduced in 1.25.2 that generates wrong NULL_VAL for char type

### ISSUE THREAD

**Issue by xinxiangrbc** [real-logic/simple-binary-encoding#958]
Please refer to comments in https://github.com/real-logic/simple-binary-encoding/issues/889.

[michaelszymczak](https://github.com/michaelszymczak) already reported the change of behavior for NULL_VAL of char type. But it was dismissed with reference to SBE 1.0 final draft.

Below is the quote from SBE 1.0 final draft.

2.7.1.1	Range attributes for char fields
Valid values of a char field are printable characters of the US-ASCII character set (codes 20 to 7E hex.) The implicit nullValue is the NUL control character (code 0).

It is clear that char '0', or 48 decimal or 30 hex, is a printable, hence not a NULL_VAL. The NULL_VAL should be 0.

In practice, we are not able to upgrade to newer version due to this issue as we trade with CME, which happens to be right.

**Comment by mjpt777** [comment]
Yes the spec does say a code of 0 should be used for null. However the CME schema defines it as "0" which is a char. They could easily fix their schema by not defining the `nullValue` and thus go with the default.

```xml
        <type name="charNULL" description="Char with null value" presence="optional" primitiveType="char" semanticType="char"/>
        <enum name="CmtaGiveUpCD" encodingType="charNULL">
            <validValue name="GiveUp" description="Give Up">G</validValue>
            <validValue name="SGXoffset" description="SGX offset">S</validValue>
        </enum>
```

Results in the following code generation.

```java
public enum CmtaGiveUpCD
{
    /**
     * Give Up
     */
    GiveUp((byte)71),

    /**
     * SGX offset
     */
    SGXoffset((byte)83),

    /**
     * To be used to represent an unknown value from a later version.
     */
    SBE_UNKNOWN((byte)0),

    /**
     * To be used to represent not present or null.
     */
    NULL_VAL((byte)0);
```

Please take this up with the CME to fix their schema.

Consider the following, what would you expect the `NULL_VAL` to be?

```xml
        <type name="charNULL" description="Char with null value" presence="optional" nullValue="z" primitiveType="char" semanticType="char"/>
        <enum name="CmtaGiveUpCD" encodingType="charNULL">
            <validValue name="GiveUp" description="Give Up">G</validValue>
            <validValue name="SGXoffset" description="SGX offset">S</validValue>
        </enum>
```

You see the type is a `char` which is different from a code point.
