### ISSUE TITLE
Backward compatibility broken for char NULL_VAL by version 1.25.2

### ISSUE THREAD

**Issue by skaminen** [real-logic/simple-binary-encoding#961]
Please refer to comments in #889 #958 

The change #889 breaks backward compatibility. A system that is using code generated before version 1.25.2 can not talk to a system that is using code generated after version 1.25.2. michaelszymczak has shown that null value for CmtaGiveUpCD is (byte) 0 for code generated before 1.25.2 and (byte) 48 for code generated after.

Our cme production setup has lot of users who are using versions before 1.25.2. Is there a path for some of them to update and still be able to communicate with systems that are on versions before 1.25.2

**Comment by mjpt777** [comment]
Yes. The CME can fix their schema to not define the null value and instead rely on defaults.

**Comment by samc1213** [comment]
To handle this:

Update

```xml
<type name="charNULL" description="Char with null value" presence="optional" nullValue="0" primitiveType="char" semanticType="char"/>
```

to

```
<type name="charNULL" description="Char with null value" presence="optional" primitiveType="char" semanticType="char"/>
```

in the CME file
