### ISSUE TITLE
Group header unused/empty bytes

### ISSUE THREAD

**Issue by M0dEx** [real-logic/simple-binary-encoding#964]
Hi!

When reimplementing codec generation for Rust and Python using [genco](https://github.com/udoprog/genco) and testing the generated code on the `example-schema.xml`, we have noticed that the codec generators in this repository leave additional space of size `groupSizeEncoding` after the group header values.

This seems to be intentional (due to `.next()` or `.advance()` being called as the first thing on a group encoder), as it is present in all generated codecs, but does not make sense to us since the bytes serve no use 
, and the behaviour is undocumented, as far as we can tell.

Is there a reason for the additional bytes?

### Example
Binary data generated for tests in this repository (group with `blockLength: uint16` = 6 and `numInGroup: uint16` = 3:
`... <group start> 06 00 03 00 00 00 00 00 <first element data> ...`

**Comment by mjpt777** [comment]
Did you discover some mistake?

**Comment by M0dEx** [comment]
> Did you discover some mistake?

Mistake on my part, sorry for the disturbance.
