### ISSUE TITLE
Error: Could not find or load main class .target.language=CPP with tag:1.30.0

### ISSUE THREAD

**Issue by sandodo** [real-logic/simple-binary-encoding#975]
Hi,

After I downloaded the latest release tag 1.30.0 into local windows and executed .\gradlew.bat to compile the jar files.
all succeeded till now.

now when I ran:
java -Dsbe.target.language=CPP -jar .\sbe-all\build\libs\sbe-all-1.30.0.jar ./templates_FixBinary.xml

It reported: Error: Could not find or load main class .target.language=CPP

If I ran: java -jar .\sbe-all\build\libs\sbe-all-1.30.0.jar ./templates_FixBinary.xml, 
it generated messages structs in java files properly.

Looks like it does not compile CPP related jar files. It used to work for me, not sure what happened this time.
my JDK is with version:
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

I am not familiar with Java, may I know if it is because of wrong JDK I used?

Thanks in advance!

**Comment by vyazelenko** [comment]
@sandodo Can you try running:
```bash
java -Dsbe.target.language=CPP -cp .\sbe-all\build\libs\sbe-all-1.30.0.jar uk.co.real_logic.sbe.SbeTool ./templates_FixBinary.xml
```

**Comment by sandodo** [comment]
@vyazelenko Thanks, below is the test result, it still reported the same error
![image](https://github.com/real-logic/simple-binary-encoding/assets/8063796/cfa503e1-8608-4caf-abea-fc71013e083b)

**Comment by sandodo** [comment]
inside jar file, the files that might be related:
uk/co/real_logic/sbe/generation:
![image](https://github.com/real-logic/simple-binary-encoding/assets/8063796/fcd5c154-eea3-431f-851d-7efe0b5692bd)

inside cpp folder:
![image](https://github.com/real-logic/simple-binary-encoding/assets/8063796/94df47f1-8d4e-4652-8ca3-2a9927a5a9a9)

hopefully it can help to identify the issue.

**Comment by sandodo** [comment]
for your information that above commands were executed in windows powershell, which caused the issue. 
if I ran it in **cmd** or **git bash** environment, CPP message structs are generated correctly. 
My OS is Windows 11 Pro.
